### ISSUE TITLE
RBAC using JWT

### ISSUE THREAD

**Issue by limadelrey** [devopsfaith/krakend-ce#100]
Hi everyone,

I'm following KrakenD documentation in order to implement a working example of forcing requests to provide a token issued by a third party.

https://www.krakend.io/docs/authorization/jwt-validation/

My main issue is that I have to set every role that a given protected resource allows by using "roles_key" and "roles" keys:

> roles_key: When passing roles, the key name inside the JWT payload specifying the role of the user.
> roles: list. When set, the JWT token not having at least one of the listed roles are rejected.

Is there any way to set this roles dynamically by using a properties file or an external configuration file? I'm asking this because it would give the opportunity to change access policies using an UI or any given service.

Thanks in advance.

**Comment by kpacha** [comment]
hi @limadelrey, welcome to the KrakenD community!

the KrakenD does not reload its configuration after starting (#166). 

if you want to avoid repetitions or managing complex configurations in a single file, you can use the [flexibleconfig](https://github.com/devopsfaith/krakend-flexibleconfig) module. https://www.krakend.io/docs/configuration/flexible-config/

Cheers!

**Comment by limadelrey** [comment]
Thank you @kpacha.
