### ISSUE TITLE
krakend cluster aware

### ISSUE THREAD

**Issue by weworksonam** [devopsfaith/krakend-ce#108]
I don't see any documentation on KrakenD being cluster aware.  For example, is there some documentation on implementing rate limiting on a service that is on two KrakenD instances that are in a cluster?

**Comment by alombarte** [comment]
Hi @weworksonam, yes you are right, there is no documentation on such topic. But a KrakenD cluster is simpler than you might think

KrakenD does not need to be aware of the existence or absence of other nodes. The rate limiting is per instance. If you are trying to limit 10K requests per second and have 10 machines in the cluster, an approximate option is to set 1K per machine. This is much simpler and efficient than storing, managing and querying the state somewhere else.

There are **external mechanisms** that can be used to have a global state, or at least, to make central decisions that affect the cluster globally. A simple example can be the invalidation of a JWT to all nodes using the bloomfilter.

Bottomline: All nodes can report to a central place its metric and traces, or you can use a central place to communicate with all nodes (e.g: bloomfilter example), but the fact is that to operate the nodes they don't need to know about each other, and this is an architectural decision that brings a lot of benefits.

**Comment by kpacha** [comment]
I'd like to a little bit further on the main reason for not sharing counters (and other actions requiring consensus among the members of the cluster): linear scalability

the coordination overhead is the reason some projects do not scale out well after reaching a given size. Here you can see the actual performance of a cluster depending on the scaling model (ideal is a lineal scaling system, Amdahl’s models system with task that can't be parallelized and USL models an actual cluster with coordination)

![](https://wso2.com/files/Picture10.png)

https://en.wikipedia.org/wiki/Neil_J._Gunther#Universal_Law_of_Computational_Scalability

**Comment by weworksonam** [comment]
I do see the simplicity and it's benefits of the design.  Thanks @alombarte and @kpacha again.
