### ISSUE TITLE
Add a new feature to generate krakend json from swagger json

### ISSUE THREAD

**Issue by prakkarp** [devopsfaith/krakend-ce#118]
Add functionality to the krakenD designer to generate the endpoints from the swagger json. This would reduce the time taken to generate the krakend json using the designer. 
Most of the cloud API gateway like AWS api gateway, apigee and others offer this functionality. So this is something very useful to have.

**Comment by fvillain** [comment]
This would be indeed very useful !! Any timeline on that ?

**Comment by kpacha** [comment]
are you talking about the swagger definitions of your backends or the swagger file describing your desired KrakenD?

in my opinion, the first case would be very hard to solve, the second one will provide just a list of endpoints with not very much details and no backends.

do you have any suggestion?

**Comment by fvillain** [comment]
In my head it was the second option : swagger file describing our krakend configuration.
This means mapping with maybe others specfiles via refs in order to generate a complete doc of the exposed API (with full information: schemas, components, ...)

Do you have some documentation readable on the entrerpise tool your talking about ? To see how it works and if it would fit our use-case ?

**Comment by mattcamp** [comment]
I too would like to see the ability to import an OpenAPI document (aka "swagger doc") to configure KrakenD.  

Many other enterprise API managers (AWS API Gateway, Azure API Manager, IBM's API Connect, Apigee, etc) all support importing OpenAPI spec docs so this seems like a gap currently.

**Comment by AdityaBhansali1** [comment]
In our project, we take the backend service swagger as input to a swagger-codegen module which converts it to a kraken config file. In our case it is a 1-1 mapping with same API structure between the gateway and backend, so works well for us.

**Comment by kpacha** [comment]
This feature is included into the enterprise version

**Comment by mingfang** [comment]
what was the resolution to this issue?

**Comment by ozonni** [comment]
we also need this. We have like 200 different endpoints and we add new, doing it manually seems to be a hustle

**Comment by AdityaBhansali1** [comment]
@adebree, @saloni27singal : Apologies for the delay. Below are some more details on how we consume multiple backend service swaggers to generate a final krakend configuration dynamically.

We utilize the [swagger codegen project](https://github.com/swagger-api/swagger-codegen#overview) for the above transformation.
This project allows generating client libraries for various languages given an open api spec as input. It also has the flexibility to [customize the generator](https://github.com/swagger-api/swagger-codegen#customizing-the-generator). We wrote our own Config generator by extending DefaultCodegenConfig, and used mustache templates which would result in a krakend config file.

At a high level, the customized generator automatically extracts information from open api and then injects them into the mustache template and generates the resulting krakend config file which matches the template definition. All this happens using the single command as below.

```
for FILE in *.json; do
	java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
	-i $FILE \
	-l com.pega.platform.gateway.swaggergenerator.KrakenDConfigCodegen
done
```

The looped runs of above command will generate several multiple krakend config files which are several parts of krakend[ Flexible configuration](https://www.krakend.io/docs/configuration/flexible-config/#:~:text=The%20Flexible%20Configuration%20component%20is,for%20a%20more%20natural%20organization.). 

Finally we run krakend by running only the top level config file.

`krakend run -c "global.json"`

You can also pass environment variables to this command and utilize them in the mustache to generate different configs based on input properties. This is useful when your config generation happens inside a docker container initialized via a helm chart. The customization of the containers can happen during the start of containers by passing the desired environment variables.

Please let me know if you need more information.

**Comment by egandro** [comment]
> Please let me know if you need more information.

Multiple questions.

1) Can you share your "com.pega.platform.gateway.swaggergenerator.KrakenDConfigCodegen" and the teimplates?

2) Can you filter routes from the downstream microservices? e.g. only certain paths or only certain HTTP Verbs?

I found this for filtering the swagger files - https://github.com/Mermade/openapi-filter - eg. tagged with "API-Mobile" or "API-Web" and you can only export this routes/operations

3) I also like to ask if you integrated a tool like swagger-ui in krakend in your setup?

I am using swaggest/rest in go - so there is a Swagger/Open API that can be provided.

https://github.com/swaggest/swgui

**Comment by 1gravity** [comment]
Why was this issue closed? It's good to hear that someone has built a solution that works for them but that doesn't help anyone else. This should be out-of-the-box functionality, not every company has the resources to build their own codegen generator.

**Comment by LuciferSam86** [comment]
> 
> 
> Why was this issue closed? It's good to hear that someone has built a solution that works for them but that doesn't help anyone else. This should be out-of-the-box functionality, not every company has the resources to build their own codegen generator.

Seeing the enterprise edition there's a Swagger generator in their Kraken Studio. 
I'm afraid they're not interested to bring the swagger generator into the CE, but I hope I am wrong.

**Comment by alombarte** [comment]
We don't have today any tool, Enterprise or Open-Source, that is able to generate a krakend.json from an OpenAPI spec (but it exists the other way around).

If you are interested in this functionality, please **upvote the first comment**. In 2 years it had less than 30 votes.

As @1gravity pointed out, not everyone has the resources to build a codegen tool. We don't think we have the time and resources either to write a generic solution for everyone, with all the possible combinations, openapi versions, etc.

What we suggest is that anyone needing this (which is actually thinking KrakenD as a no-op proxy, instead of implementing a GW as it should be) writes a custom 20 lines script to do the magic. It can be in any language. If you are scared of Go, it doesn't have to be. The following snippet is **5 minutes of work** in a non-Go language. **Do not see it as a ready-to-use script**, neither a good practice, but a quick hack to demonstrate the simplicity of a generator.

```
<?php

$fc = file_get_contents('swagger.json');
$swagger = json_decode($fc, true);

// KrakenD config:
$k['version'] = 2;
$k['host'] = [( $swagger['schemes'][0] ?: 'http' ) . '://' . $swagger['host']];
$k['name'] =   $swagger['info']['title'];

$paths = array_keys($swagger['paths']);
foreach( $paths as $endpoint) {
    $methods = array_keys($swagger['paths'][$endpoint]);
    
    foreach( $methods as $method) {
        $k["endpoints"][] = array(
            "endpoint" => $endpoint,
            "method" => strtoupper($method),
            "output_encoding" => "no-op",
            "backend" => [
                "encoding" => "no-op",
                "url_pattern" => $endpoint
            ]
        );
    }
}
file_put_contents('krakend.json',json_encode($k, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
```
