### ISSUE TITLE
encoding "no-op" does not work as expected

### ISSUE THREAD

**Issue by vmartos** [devopsfaith/krakend-ce#130]
I have a simple use case where a backend is just responding for an endpoint /api/test a string with the Content-Type _text/plain; charset=utf-8_ set in the response headers. I then have the krakend.json with the following:

{
            "endpoint" : "/api/test",
            "output-encoding": "no-op",
            "method": "GET",
            "backend" : [
                {
                    "host": ["http://192.168.1.107:53895"],
                    "url_pattern": "/api/test",
                    "encoding": "no-op"
                }
            ]
        }

it is supposed to act as a proxy because the encoding is set to no-op, and the output-encoding as set also as no-op, it should mantain the Header value of the response Content-Type to text/plain, but it is application/json; charset=utf-8, and the content is an empty json object.

Is there something I'm missing in my endpoint config? or is it a bug?

Thank you

**Comment by kpacha** [comment]
hi, @vmartos and welcome to the KrakenD community!

There is a small typo in your config: `output-encoding` is not an config option. The option is `output_encoding`.

https://www.krakend.io/docs/endpoints/no-op/#example

cheers!
