### ISSUE TITLE
Docker readme confusing

### ISSUE THREAD

**Issue by earlonrails** [devopsfaith/krakend-ce#131]
I didn't know where to put this and I would be happy to open a PR to make this change. I noticed that the docker readme points to a sample file which uses 8000 and the docker run command on the readme exposes port 8080. I was just trying to demo the product and I wasn't hitting the right port which was frustrating. Looks like a very nice product so far though! I love the configuration designer.

**Comment by alombarte** [comment]
Hi @earlonrails !

This is the kind of error it's hard to catch by us... Thank you very much for spotting it. Feel free to open the PR and set it to the port `8080` which is our default port and we have you on board as contributor :)

Thanks for the nice feedback!

**Comment by alombarte** [comment]
Hi @earlonrails , if you still want to do the PR you only need to change the port in the file https://github.com/devopsfaith/krakend-ce/blob/master/krakend.json

Thanks!

**Comment by alombarte** [comment]
Solved by @Juandavi1
