### ISSUE TITLE
Response manipulation

### ISSUE THREAD

**Issue by gerardoman** [devopsfaith/krakend-ce#139]
Hi,

I'm having troubles following this documentation: 
https://www.krakend.io/docs/endpoints/response-manipulation/
https://www.krakend.io/docs/backends/data-manipulation/

I'm trying to aggregate a response from two backends from different api's. I can use all documented attributes (e.g. blacklist, whitelist, group...) but the complete response only comes the first time I request it or, sometimes, some requests later. In most cases I receive the response from one api and the other times the one from the other api.

I tried it many ways. I removed all cache and timeout definitions, reduced my configurations, etc. I don't know what more can I try.

Can someone help me?

Thanks in advance.

**Comment by kpacha** [comment]
hi @gerardoman and welcome to the KrakenD community.

in order to get a better idea of what your problem could be, can you share the configuration of the endpoint?

Also, what are the backend logs saying?

**Comment by gerardoman** [comment]
Hi,

These are the configurations I'm using:

_{
  "version":2,
  "name":"gateway",
  "port":"8090",
  "host":[
     "http://localhost:8080",
     "http://localhost:8088",
  ],
  "extra_config":{
     "github_com/devopsfaith/krakend-cors":{
        "allow_origins":[],
        "allow_methods":[
           "GET",
           "HEAD",
           "POST",
           "PUT",
           "DELETE",
           "CONNECT",
           "OPTIONS",
           "TRACE",
           "PATCH"
        ],
        "allow_headers":[
           "Origin",
           "Authorization",
           "Content-Type",
           "Access-Control-Allow-Origin",
           "Locale",
           "Accept",
           "X-Requested-With",
           "Cache-Control",
           "Postman-Token",
           "X-Tenant",
           "X-User-Id",
           "X-Correlation-Id",
           "X-Lang"
        ],
        "allow_credentials":true,
        "max_age":"1s",
        "expose_headers":[
           "Origin",
           "Authorization",
           "Content-Type",
           "Access-Control-Allow-Origin",
           "Locale",
           "Accept",
           "X-Requested-With",
           "Cache-Control",
           "Postman-Token",
           "X-Tenant",
           "X-User-Id",
           "X-Correlation-Id"
        ]
     }
  },
  "endpoints":[
     {
    "method": "GET",
    "endpoint": "/api/v1/labels/{id}",
    "headers_to_pass": [
      "X-Tenant",
      "X-User-Id",
      "X-Correlation-Id"
    ],
    "backend": [
		{
			"url_pattern": "/api/v1/labels/{id}",
      "encoding": "json",
			"host": [
				"http://localhost:8088"
			]
		},
    {
      "url_pattern": "/api/v3/users/46036d05-8602-48b8-9283-4f45c92cbfca",
      "encoding": "json",
      "blacklist": [
        "id",
        "name"
      ],
      "host": [
        "http://localhost:8080"
      ],
      "group": "user"
    }
	],
    "extra_config": {
      "github.com/devopsfaith/krakend-jose/validator": {
        "alg": "HS256",
        "jwk-url": "http://localhost:8080/jwk",
        "disable_jwk_security": true
      }
    }
  },
  {
    "method": "GET",
    "endpoint": "/api/v3/users/{id}",
    "headers_to_pass": [
      "X-Tenant",
      "X-User-Id",
      "X-Correlation-Id",
      "X-Lang"
    ],
    "backend": [
      {
        "host": "http://localhost:8080",
        "url_pattern": "/api/v3/users/{id}"
      }
    ],
    "extra_config": {
      "github.com/devopsfaith/krakend-jose/validator": {
        "alg": "HS256",
        "jwk-url": "http://localhost:8080/jwk",
        "disable_jwk_security": true
      }
    }
  }
  ]
}_

The backends are implemented in RxJava using Vert.X framework. When making requests without aggregation response they work properly. When trying to apply this configurations at certain point "Response is closed" for one of the backends. It doesn't follow a pattern, I mean, sometimes both works, sometimes the label's one is closed and sometimes the user's one is closed.

**Comment by kpacha** [comment]
try to add the logger at debug level (https://github.com/devopsfaith/krakend-playground/blob/master/krakend/krakend.json#L10-L15) and increase the global timeout `"timeout": "10s"`. It should help you debugging the issue

**Comment by gerardoman** [comment]
Applying your suggestions the logs return for all endpoints:

[KRAKEND] 2019/09/02 - 17:18:49.050 ▶ ERROR JOSE: no signer config /api/v1/labels/:id

However when making a request it never returned the complete response with information from both backends. Sometimes got response from labels and the other times response from users.
When making requests the logs does not seem to identify problems:

[GIN] 2019/09/02 - 17:20:27 | 200 |   23.068195ms |             ::1 | GET      /api/v1/labels/c3d76508-bb0c-4e7c-958a-d2888bba59e1

**Comment by kpacha** [comment]
@gerardoman I'm pretty sure it must be something related with the communication between the gateway and the backends. I've changed a little bit your config in order to consume 2 mocked endpoints and it works like a charm. Please, take a look:

```
{
	"version": 2,
	"name": "gateway",
	"port": "8090",
	"host": ["http://www.mocky.io"],
	"extra_config": {
		"github_com/devopsfaith/krakend-gologging": {
			"level": "DEBUG",
			"prefix": "[KRAKEND]",
			"syslog": false,
			"stdout": true
		}
	},
	"endpoints": [{
		"endpoint": "/api/v1/labels/{id}",
		"headers_to_pass": [
			"X-Tenant",
			"X-User-Id",
			"X-Correlation-Id"
		],
		"backend": [{
				"url_pattern": "/v2/5d779f343200005b00923f36?id={id}"
			},
			{
				"url_pattern": "/v2/5d779eee3200005200923f33?id={id}",
				"blacklist": [
					"id",
					"name"
				],
				"group": "user"
			}
		]
	}]
}
```

calling the exposed endpoint, you'll get the composed response:

```
$ curl -i localhost:8090/api/v1/labels/1
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Krakend: Version 0.10.0-dev
X-Krakend-Completed: true
Date: Tue, 10 Sep 2019 13:06:29 GMT
Content-Length: 110

{"bar":42,"foo":true,"id":"label12345","name":"label","user":{"bar":42,"email":"user@example.tld","foo":true}}
```

can you make 2 direct calls to your backends using just cURL and paste the response here? with that info, we'll be able to move forward with the troubleshooting

**Comment by gerardoman** [comment]
I made 3 cURL requests:

1st: request to label. 
```
curl -H 'Accept: application/json' -H "X-Tenant: i2s" localhst:8088/api/v1/labels/c3d76508-bb0c-4e7c-958a-d2888bba59e1

{
  "id" : "c3d76508-bb0c-4e7c-958a-d2888bba59e1",
  "id_trans" : "1d88ce47-40e8-4505-a5e6-8404429f578b",
  "id_lang" : "en_gb",
  "name" : "name",
  "definitions" : [ ]
}
```
2nd: request to user. 
```
curl -H 'Accept: application/json' -H "X-Tenant: i2s" localhst:8080/api/v3/users/46036d05-8602-48b8-9283-4f45c92cbfca

{
  "id" : "46036d05-8602-48b8-9283-4f45c92cbfca",
  "id_status_type" : "active",
  "name" : "name",
  "email" : "name@domain.com",
  "profile" : {
    "id_lang" : "en_gb"
  }
}
```

3rd: request through gateway. Expected an aggregate response from both backends
```
curl -H 'Accept: application/json' -H "Authorization: Bearer _token_" localhost:8090/api/v1/labels/c3d76508-bb0c-4e7c-958a-d2888bba59e1

{
  "id" : "46036d05-8602-48b8-9283-4f45c92cbfca",
  "id_status_type" : "active",
  "name" : "name",
  "email" : "name@domain.com",
  "profile" : {
    "id_lang" : "en_gb"
  }
}
```

4th: another request through gateway. Expected an aggregate response from both backends
```
curl -H 'Accept: application/json' -H "Authorization: Bearer _token_" localhost:8090/api/v1/labels/c3d76508-bb0c-4e7c-958a-d2888bba59e1

{
  "id" : "c3d76508-bb0c-4e7c-958a-d2888bba59e1",
  "id_trans" : "1d88ce47-40e8-4505-a5e6-8404429f578b",
  "id_lang" : "en_gb",
  "name" : "name",
  "definitions" : [ ]
}
```

5th: last try requesting through gateway. Expected an aggregate response from both backends
```
curl -H 'Accept: application/json' -H "Authorization: Bearer _token_" localhost:8090/api/v1/labels/c3d76508-bb0c-4e7c-958a-d2888bba59e1

{
  "id" : "c3d76508-bb0c-4e7c-958a-d2888bba59e1",
  "id_trans" : "1d88ce47-40e8-4505-a5e6-8404429f578b",
  "id_lang" : "en_gb",
  "name" : "name",
  "definitions" : [ ]
}
```

**Comment by alombarte** [comment]
I have spoken with @gerardoman on Slack.
> Now it’s working through cURL, but it’s not working on my Postman although it’s working fine on my colleague’s Postman. I’ll try to figure it out what’s happening with my Postman. I guess it’s not related to Krakend so for now I can consider my issue solved

**Comment by kpacha** [comment]
I'm closing this.

Please, reopen it if the issue re-emerges
