### ISSUE TITLE
rename collection item with mapping in krakend

### ISSUE THREAD

**Issue by even42** [devopsfaith/krakend-ce#14]
I have this output
``` json
{
  "pricing": [
    {
      "max_number": "10",
      "desc": "Sample description 1"
    },
    {
      "max_number": "42",
      "desc": "Sample description 2"
    }
  ]
}
```
I want this

```json
{
	"pricing": [{
			"maxNumber": "10",
			"description": "Sample description 1"
		},
		{
			"maxNumber": "42",
			"description": "Sample description 2"
		}
	]
}
```

**How can I do that  with krakend ?**

I tried do resolve it with this conf (sniped) :

    {
    	"endpoint": "/get/pricing",
    	"method": "GET",
    	"concurrent_calls": 1,
    	"backend": [{
    		"url_pattern": "/api/v1/get/pricing",
    		"encoding": "json",
    		"is_collection": true,
    		"mapping": {
    			"collection": "pricing",
    			"collection.desc": "description",
    			"collection.max_number": "maxNumber"
    		},
    		"host": [
    			"http://facke_server/"
    		]
    	}]
    }

**Comment by kpacha** [comment]
hi @even42!

unfortunately, the `mapper` does not work on collections yet

**Comment by even42** [comment]
Any fix planned ?

I can try to fix it, just tell me the file which  handle to that (to save time looking). May be can do a PR after that :)

Another question
Did you plan an  Enterprise edition ? An admin GUI to monitoring in real time ?

**Comment by kpacha** [comment]
No, it's not in the top of the backlog due it's performance implications, but we love contributions

Here is the related code: https://github.com/devopsfaith/krakend/blob/0.5-dev/proxy/formatter.go#L55

One last thing: you can also create a custom martian modifier for this backend and introduce your response customizations there. Here you have a nice post explaining how to do it: http://www.krakend.io/blog/website-development-as-a-sysadmin/

**Comment by kpacha** [comment]
@even42 check out the new flatmap filter!!!

**Comment by vladkras** [comment]
it's necroposting but for solution-seekers, you can do it with `flatmap_filter` on `backend` proxy

```
          "extra_config": {
              "github.com/devopsfaith/krakend/proxy": {
                "flatmap_filter": [
                    {
                        "type": "move",
                        "args": ["pricing.*.desc", "pricing.*.description"]
                    },
                    {
                      "type": "move",
                      "args": ["pricing.*.max_number", "pricing.*.maxNumber"]
                    }
                ]
            }
          }
```
