### ISSUE TITLE
Accessing nested response object from previous backend in a sequential proxy

### ISSUE THREAD

**Issue by martskins** [devopsfaith/krakend-ce#141]
I'm having some trouble using a nested object in the response from a previous backend in a sequential proxy scenario.

What I want to achieve is set up an endpoint with two sequential backends where the second backend should read the response from the first one and use a field in that response, that happens to be nested inside some other object.
So for example, if the first endpoint returned:

```
{
  "id": 1,
  "title": "hello",
  "user": {
    "id": 1
  }
}
```

The second backend would user the user id from the previous response. So essentially I want to access `user.id` in that response. As I understand it, I should be able to do that with `{resp0_user.id}`, but that doesn't seem to work, as I keep getting a 404 from the users endpoint, and I know for a fact that that user exists.

I've set up some json placeholder route to test this:
https://my-json-server.typicode.com/martskins/json-demo/posts/1
https://my-json-server.typicode.com/martskins/json-demo/users/1

And a basic krakend config that uses these endpoints to reproduce this issue:
```
{
  "version": 2,
  "timeout": "5s",
  "name": "Demo",
  "endpoints": [
    {
      "endpoint": "/v1/posts/{id}",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": { "sequential": true }
      },
      "backend": [
        {
          "url_pattern": "/martskins/json-demo/posts/{id}",
          "host": [ "https://my-json-server.typicode.com" ],
          "extra_config": {
            "github.com/devopsfaith/krakend/http": { "return_error_details": "posts" }
          }
        },
        {
          "url_pattern": "/martskins/json-demo/users/{resp0_user.id}",
          "group": "user",
          "host": [ "https://my-json-server.typicode.com" ],
          "extra_config": {
            "github.com/devopsfaith/krakend/http": { "return_error_details": "users" }
          }
        }
      ]
    },
    {
      "endpoint": "/v2/posts/{id}",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": { "sequential": true }
      },
      "backend": [
        {
          "url_pattern": "/martskins/json-demo/posts/{id}",
          "host": [ "https://my-json-server.typicode.com" ],
          "extra_config": {
            "github.com/devopsfaith/krakend/http": { "return_error_details": "posts" }
          }
        },
        {
          "url_pattern": "/martskins/json-demo/users/{resp0_userId}",
          "group": "user",
          "host": [ "https://my-json-server.typicode.com" ],
          "extra_config": {
            "github.com/devopsfaith/krakend/http": { "return_error_details": "users" }
          }
        }
      ]
    }
  ]
}
```

You'll notice that the posts endpoint returns both `"userId": X` and `"user": { "id": X }`, this was added just to test whether there was an issue with response parsing in general or just in the case of nested objects.
The first endpoint in that config (`/v1/posts/{id}`) will error on the second backend, while the second endpoint (`/v2/posts/{id}`) will succeed, and the only different is that the first one tries to get a nested field, while the second one uses a field in the root level of the response object.

**Comment by kpacha** [comment]
this is a known and fixed bug: https://github.com/devopsfaith/krakend/issues/330

next monday we plan to release v1.1.1 with the fix included
