### ISSUE TITLE
JWT validation: error in cryptographic primitive

### ISSUE THREAD

**Issue by thinkingmik** [devopsfaith/krakend-ce#142]
Hi,

I've got some problems with JWT validation using the `krakend-jose` plugin, probably I'm missing something or I'm wrong with some configurations.

**Problem**

I have a valid JWT generated from an external environment and signed with a shared secret key `4BzyO2wa`:
```
eyJhbGciOiJIUzUxMiIsImtpZCI6IjEifQ.eyJzdWIiOiJ1c2VyQGRheXJlcC5jb20iLCJpc3MiOiJhY21lIiwiYXVkIjoiaHR0cHM6Ly9qd3Qvand0IiwibmJmIjoxNTY3NTgyMTg0LCJleHAiOjE1OTkyMDQ1ODQsImlhdCI6MTU2NzU4MjE4NH0.i5gm2MoiRT4w7zK3aOM7FHa9n9xpLmeIWcYin99rfgNocL7UBCvRcBz3oZa0xZOBtIbPsrTmEFvHsLf_prfLfQ
```

Now I open [jwt.io](https://jwt.io/), set my shared secret key `4BzyO2wa` (**not flagged as base64 encoded**), I paste my JWT and it tells me that the signature it's ok.

In my Krakend configuration I've got this sample endpoint:
```json
{
  "version": 2,
  "name": "API Gateway",
  "port": 8000,
  "endpoints": [
    {
      "method": "GET",
      "endpoint": "/api/jwt/check",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "HS512",
          "issuer": "acme",          
          "disable_jwk_security": true,
          "jwk-url": "http://www.mocky.io/v2/5d6f99113100000d00660765"
        }
      },
      "backend": [
        {
          "host": [
            "http://localhost:8200"
          ],
          "url_pattern": "/api/jwt/check",
          "sd": " static ",
          "disable_host_sanitize": true
        }
      ]
    }
  ]
}
```

So, when I call this endpoint from curl or Postman with my bearer JWT token like this:
```
GET /api/jwt/check HTTP/1.1
Host: localhost:8000
Authorization: bearer eyJhbGciOiJIUzUxMiIsImtpZCI6IjEifQ.eyJzdWIiOiJ1c2VyQGRheXJlcC5jb20iLCJpc3MiOiJhY21lIiwiYXVkIjoiaHR0cHM6Ly9qd3Qvand0IiwibmJmIjoxNTY3NTgyMTg0LCJleHAiOjE1OTkyMDQ1ODQsImlhdCI6MTU2NzU4MjE4NH0.i5gm2MoiRT4w7zK3aOM7FHa9n9xpLmeIWcYin99rfgNocL7UBCvRcBz3oZa0xZOBtIbPsrTmEFvHsLf_prfLfQ
```

On Krakend I've got a `401` error that tells me: `Error #01: square/go-jose: error in cryptographic primitive`

**Question**

Why if I change the signature on [jwt.io](https://jwt.io/) and set the same secret shared key but **flagged as base64** and copy the new JWT, it works on Krakend?
Note: if I set the secret shared key as base64 the JWT change in:
```
eyJhbGciOiJIUzUxMiIsImtpZCI6IjEifQ.eyJzdWIiOiJ1c2VyQGRheXJlcC5jb20iLCJpc3MiOiJhY21lIiwiYXVkIjoiaHR0cHM6Ly9qd3Qvand0IiwibmJmIjoxNTY3NTgyMTg0LCJleHAiOjE1OTkyMDQ1ODQsImlhdCI6MTU2NzU4MjE4NH0.5AAG5pCnVibySrLklCDWehSWjOACyeSb5xOADTZRcZD7JY7dQxICnWE83dlUf6VoJ1JMrelRsgfCyicuo1U9jg
```

This token does not have the same signature of the original JWT provided to me from the external environment. So how can I validate the original JWT with `krakend-jose`?

**Comment by kpacha** [comment]
hi, @thinkingmik 

the JWT you pasted does not have a `kid` claim at the header section, so the jose module doesn't know which key it should use to verify the token.

also, remember you should define the `kid` for every key at the JWK

**Comment by thinkingmik** [comment]
Hi @kpacha,

I edited the original post by adding the `kid` info in the JWK and in the JWT header, but nothing changes. The problems is always the same :-(

**Comment by kpacha** [comment]
if you get this message `Error #01: square/go-jose: error in cryptographic primitive` there is a problem with your JWK.

here you have a simple script for creating your JWK definition. Notice the key must be base64 encoded

https://play.golang.org/p/nM1Vkb1DJ0b

**Comment by thinkingmik** [comment]
Thank you very much @kpacha! I was going crazy.
You're right, in the JWK the key is to set in base64 encode without paddings `=` like this:
```json
{
  "keys": [
    {
      "kid": "1",
      "kty": "oct",
      "k": "NEJ6eU8yd2E",
      "alg": "HS512"
    }
  ]
}
```
