### ISSUE TITLE
Access to roles_key that are in nested properties (krakend-jose/validator)

### ISSUE THREAD

**Issue by NoorKrichen** [devopsfaith/krakend-ce#146]
when using Krakend jwt validation,
how can i set the roles_key when the roles are under another element in my jwt ?

example 'roles' are under 'user-data':

{
  "iat": 1568477667,
  "nbf": 1568477667,
  "jti": "fac86d7d-0d59-425f-9400-ccb8ee7265c9",
  "exp": 1568478567,
  "identity": "user1",
  "user-data": {
    "roles": [
      "admin",
      "simple-user"
    ]
  },
  "fresh": false,
  "type": "access"
}

**Comment by kpacha** [comment]
Hi @NoorKrichen and welcome to the KrakenD community,

as you already pointed out, you can select the key containing the array of roles with the param `roles_key`.

Here you have 2 working examples from the playground

1: https://github.com/devopsfaith/krakend-playground/blob/master/krakend/krakend.json#L144 this endpoint uses tokens generated by auth0.

2: https://github.com/devopsfaith/krakend-playground/blob/master/krakend/krakend.json#L161 this endpoint uses the token generated by the mocked auth server (https://github.com/devopsfaith/krakend-playground/blob/master/data/token.json#L7)

cheers!

**Comment by NoorKrichen** [comment]
Thank you for your quick answer.
I can not edit the payload of my jwt 

In my jwt I do not have:
"roles": ["admin", "simple-user"]
but I have:
"user-data": { "roles": [ "admin", "simple-user"]},

"roles" is a field in the "user-data"

in the krakend.json I tried to put  
"roles_key": "user-data.roles",

but it did not work

**Comment by kpacha** [comment]
@NoorKrichen accessing nested properties is not supported, but I think it could be a nice feature! I'm adding it to the backlog.

thanks for the feedback!

**Comment by NoorKrichen** [comment]
I appreciate your reactivity
Thank you
Good work team

**Comment by NoorKrichen** [comment]
I appreciate your reactivity
Thank you
Good work team

**Comment by NoorKrichen** [comment]
I appreciate your reactivity
Thank you
Good work team
