### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Jeka-Dem** [devopsfaith/krakend-ce#15]
Hi guys!
I've an question about CORS:
On the main page there is a string "Cross-origin resource sharing (CORS)" in tool features description
But in documentation I can't find any info to how implement it / enable it
I have Kubernetes Cluster with some micro-services and deployed and configured KrakenD in front of them, when I send some request to service endpoint I get error in Chrome console:
"Failed to load https://integration.****.com/****: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dev.***' is therefore not allowed access. The response had HTTP status code 500."
I can try configure Kube Ingress to handle it, but I want to enable it in KrakenD
So, how I can implement it?
Thanks!

**Comment by kpacha** [comment]
Hi, @Jeka-Dem ,

The CORS module is not included in the released CE versions by default as it is problematic in the activation/desactivation. To use it you need to add it manually as in https://github.com/devopsfaith/krakend-examples/blob/053b842129fd984a36a8549ba124ffab70613283/jwt/main.go#L79

cheers

**Comment by alombarte** [comment]
We need to correct the page, noted.

Thanks for reporting @Jeka-Dem

**Comment by taik0** [comment]
Hi @Jeka-Dem we just created a CORS module so you can use it with your KrakenD installation.
To enable it in KrakenD-ce you should add the middleware in this line:
https://github.com/devopsfaith/krakend-ce/blob/master/executor.go#L38
With an statement like:
```
corsMw := gin.New(cfg.ExtraConfig)
...
MiddleWares: []gin.HandlerFunc{corsMw}
...
```
(Remember to import the new module)

You have gin and mux adapters to choose from.
