### ISSUE TITLE
Response manipulation between two collections

### ISSUE THREAD

**Issue by limadelrey** [devopsfaith/krakend-ce#150]
Hey,

I've read KrakenD's documentation, but since I didn't find any example that merges an endpoint with multiple elements with another endpoint with multiple elements I've decided to ask you directly if that is possible or not.

Basically let's use as an example a service (service A) that returns a JSON object with multiple elements with the following properties:
```
{
  "total": "",
  "limit": "",
  "page": "",
  "items": [
    {
      "id": "",
      "service_b_id": ""
    }, 
    {
      "id": "",
      "service_b_id": ""
    }
  ]
}
```

Then let's use another service (service B) that also returns a JSON object with multiple elements with the following properties:
```
{
  "total": "",
  "limit": "",
  "page": "",
  "items": [
    {
      "id": "",
      "name": ""
    }, 
    {
      "id": "",
      "name": ""
    }
  ]
}
```

Is is possible to use KrakenD response manipulation in order to merge both endpoints and get an aggregated object with the following properties?
```
{
  "total": "",
  "limit": "",
  "page": "",
  "items": [
    {
      "id": "",
      "service_b": {
        "id": "",
        "name": ""
      }
    }, 
    {
      "id": "",
      "service_b": {
        "id": "",
        "name": ""
      }
    }
  ]
}
```

Thank you in advance.

**Comment by kpacha** [comment]
There is no component ready to do that kind of custom aggregation but you can use a lua script for that

check it in action at the integration tests:

- config: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L483-L517

- specs (req/resp): https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/specs/lua_1.json

**Comment by AndreaTurco** [comment]
Hi all,
I'm trying to achieve this target:

- from a json response given by my backend -> convert in a XML to return to the enduser  

For do that I'm trying to integrate a new lua script as extra_config:
```

{
   "endpoint": "/json_ext",
   "timeout": "800ms",
    "method": "GET",
   "backend":[
      {
         "output_encoding":"xml",
         "url_pattern":"/todos/1",
         "extra_config":{
            "github.com/devopsfaith/krakend-lua":{
               "sources":[
                  "converter/luatoxml.lua"
               ],
               "md5":{

               },
               "post":"toxml",
               "live":true,
               "skip_next":true
            }
         },
         "method":"GET",
         "encoding":"json",
         "disable_host_sanitize":true,
         "host":[
            "https://jsonplaceholder.typicode.com"
         ]
      }
   ]
}
```
where **toxml** of the `"post": "toxml",` is the function defined inside the file **"converter/luatoxml.lua"** . The lua file is located in the **/etc/krakend/** directory (same of the config file).
At this point:

1.  I don't know how if the configuration is written in the correct way
2. I'm not getting any error or information about the correct execution of the lua file
3. I don't know how to have access at the response of the backend (in the docs I can see an example only for the request https://www.krakend.io/docs/endpoints/lua/) inside the lua script

Is possible to have some advice on this topic? 
Thanks

**Comment by kpacha** [comment]
@AndreaTurco it seems to me that you are looking for the format conversion:

```
    {
      "endpoint": "/json_ext",
      "timeout": "800ms",
      "output_encoding":"xml",
      "backend":[
        {
          "url_pattern":"/todos/1",
          "host":["https://jsonplaceholder.typicode.com"]
        }
      ]
    }
```

```
$ curl -i localhost:8080/json_ext
HTTP/1.1 200 OK
Content-Type: application/xml
X-Krakend: Version 1.0.0
X-Krakend-Completed: true
Date: Mon, 28 Oct 2019 11:01:08 GMT
Content-Length: 100

<doc><completed>false</completed><id>1</id><title>delectus aut autem</title><userId>1</userId></doc>```
