### ISSUE TITLE
[HELP REQUIRED] in logging request 

### ISSUE THREAD

**Issue by pardhasm** [devopsfaith/krakend-ce#151]
I am new to Golang and exploring Krakend.
I am trying to log the complete request and response payloads but am not able to do so.

This is my krakend.json

```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "INFO",
      "prefix": "[KRAKEND]",
      "syslog": true,
      "stdout": true,
      "format": "logstash"
    },
    "github_com/devopsfaith/krakend-metrics": {
      "collection_time": "60s",
      "proxy_disabled": false,
      "router_disabled": false,
      "backend_disabled": false,
      "endpoint_disabled": false,
      "listen_address": ":8090"
    }
  },
  "timeout": "10000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "gtest",
  "port": 8002,
  "endpoints": [
    {
      "endpoint": "/v2/xyz/details/{id}",
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "querystring_params": [
        "*"
      ],
      "headers_to_pass": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "/v2/xyz/details/{id}",
          "encoding": "json",
          "sd": "static",
          "extra_config": {},
          "host": [
            "https://api.mysite.com"
          ],
          "disable_host_sanitize": true
        }
      ]
    }
  ]
}

```
**Logs**
**Sysout:**
`[GIN] 2019/10/09 - 17:47:24 | 200 |  8.610076523s |       127.0.0.1 | GET      /v2/xyz/details/12345678?_ab=987654`

**Syslog:**
`Oct  9 17:44:57 My-MacBook-Pro krakend[10352]: {"@timestamp":"900-10-09T17:44:57.155+00:00", "@version": 1, "level": "WARNING", "message": "{"@timestamp":"2019-10-09T17:44:57.155014+05:30","@version":1,"host":"localhost","level":"WARNING","message":"unable to create the usage report client: Post https://usage.krakend.io/session: context deadline exceeded","module":"[KRAKEND]"}", "module": "KRAKEND"}`

I am not able to find the details in documentation.

**Comment by kpacha** [comment]
hi @pardhasm 

first of all, the logger does not inspect the request and responses the gateway is dealing with.

there is a component (https://github.com/devopsfaith/krakend-spew) for doing that on custom builds, but it's not included into the CE due its huge impact on performance.

when you need to do this kind of inspection on production, I'd suggest you to use `tcpdump`.

I'm closing this due duplication with https://github.com/devopsfaith/krakend-ce/issues/65

**Comment by pardhasm** [comment]
@kpacha can you please help with any resources for using `tcpdump` . I'm new to both krakend and Golang.
Currently 
`[GIN] 2019/10/09 - 17:47:24 | 200 | 8.610076523s | 127.0.0.1 | GET /v2/xyz/details/12345678?_ab=987654 ` is being logged.
Can any other details be added to this? (Headers, keys, etc.,)

**Comment by kpacha** [comment]
`tcpdump` is a network tool not related with krakend or golang

some examples: https://sites.google.com/site/jimmyxu101/testing/use-tcpdump-to-monitor-http-traffic

for a more detailed article: https://www.middlewareinventory.com/blog/tcpdump-capture-http-get-post-requests-apache-weblogic-websphere/

cheers!

**Comment by pardhasm** [comment]
@kpacha Thanks for the info. Do we have anything similar to [https://docs.konghq.com/hub/kong-inc/syslog/#log-format](this)

**Comment by kpacha** [comment]
you can't do that with just enabling the logger component, but you can use the tracing feature (https://www.krakend.io/docs/logging-metrics-tracing/tracing/). Such feature supports the logger as an exporter for both metrics and traces

**Comment by pardhasm** [comment]
Thank you. Will try and get back

**Comment by pardhasm** [comment]
@kpacha Tried enabling logger. My kraken.json below

  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": true,
      "stdout": true,
      "format": "logstash"
    },
    "github_com/devopsfaith/krakend-metrics": {
      "collection_time": "60s",
      "proxy_disabled": false,
      "router_disabled": false,
      "backend_disabled": false,
      "endpoint_disabled": false,
      "listen_address": ":8090"
    },
    "github_com/devopsfaith/krakend-opencensus": {
      "sample_rate": 100,
      "reporting_period": 1,
      "exporters": {
        "logger": {}
      }
    },
    "github_com/devopsfaith/krakend-logstash": {
      "enabled": true
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "gtest",
  "port": 8002,
  "endpoints": [
    {
      "endpoint": "/v2/xyz/details/{id}",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0,
          "strategy": "ip"
        }
      },
      "output_encoding": "no-op",
      "concurrent_calls": 1,
      "querystring_params": [
        "*"
      ],
      "headers_to_pass": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "/v2/xyz/details/{id}",
          "encoding": "no-op",
          "sd": "static",
          "extra_config": {},
          "host": [
            "https://api.mysite.com"
          ],
          "disable_host_sanitize": true
        }
      ]
    }
  ]
}


I'm running krakend on mac. 
Sysout :
[GIN] 2019/10/10 - 11:58:17 | 200 |  121.874818ms |             ::1 | GET      /v2/xyz/details/8362541147651098A?_dc=1570618769954

Syslog :
Oct 10 11:56:41 Pardhas-MacBook-Pro krakend[2480]: {"@timestamp":"1000-10-10T11:56:41.419+00:00", "@version": 1, "level": "DEBUG", "message": "{"@timestamp":"2019-10-10T11:56:41.419276+05:30","@version":1,"host":"localhost","level":"DEBUG","message":"CEL: no extra config detected for pipe /v2/cam/details/:id","module":"[KRAKEND]"}", "module": "KRAKEND"}
Oct 10 11:56:41 Pardhas-MacBook-Pro krakend[2480]: {"@timestamp":"1000-10-10T11:56:41.419+00:00", "@version": 1, "level": "INFO", "message": "{"@timestamp":"2019-10-10T11:56:41.419349+05:30","@version":1,"host":"localhost","level":"INFO","message":"JOSE: singer disabled for the endpoint /v2/cam/details/:id","module":"[KRAKEND]"}", "module": "KRAKEND"}
Oct 10 11:56:41 Pardhas-MacBook-Pro krakend[2480]: {"@timestamp":"1000-10-10T11:56:41.419+00:00", "@version": 1, "level": "INFO", "message": "{"@timestamp":"2019-10-10T11:56:41.419377+05:30","@version":1,"host":"localhost","level":"INFO","message":"JOSE: validator disabled for the endpoint /v2/cam/details/:id","module":"[KRAKEND]"}", "module": "KRAKEND"}



Not sure what I am missing

**Comment by karnphongkie** [comment]
@pardhasm Have you found a solution yet?
