### ISSUE TITLE
JWT expiration

### ISSUE THREAD

**Issue by mkolbusz** [devopsfaith/krakend-ce#154]
**Describe what are you trying to do**
I want to use JWT to authenticate API access. I set up the token issuer endpoint `/token` and endpoint that needs authorization by JWT `/v1/identites`. Returning JWK from service I set the `exp` and `iat`. The problem is I can use that generated token after the exp time as well. Does the krakend handle expiration and check it? I supposed to use a valid token only if `now` < `exp` and after that, the token is invalid, does it? Thanks a lot!
**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Test",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/v1/identities",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "HS256",
          "jwk-url": "http://auth-service:3001/v1/jwk",
          "issuer": "test",
          "cache": true,
          "disable_jwk_security": true
        }
      },
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/v1/identities",
          "encoding": "json",
          "sd": "static",
          "extra_config": {
            "github.com/devopsfaith/krakend-httpcache": {},
            "github.com/devopsfaith/krakend-ratelimit/juju/proxy": {
              "maxRate": 1,
              "capacity": 1
            }
          },
          "method": "GET",
          "host": [
            "http://embedding-service:3001"
          ],
          "disable_host_sanitize": false,
          "is_collection": true,
          "target": ""
        }
      ]
    },
    {
    "endpoint": "/token",
    "method": "POST",
    "backend": [
    {
        "host": [ "http://auth-service:3001" ],
        "url_pattern": "/v1/tokens"
    }
    ],
    "extra_config": {
        "github.com/devopsfaith/krakend-jose/signer": {
            "alg": "HS256",
            "kid": "test",
            "keys-to-sign": ["access_token"],
            "jwk-url": "http://auth-service:3001/v1/jwk",
            "disable_jwk_security": true
        }
    }
  }]
}
```
**Commands used**
How did you start the software?
```
docker-compose up -d
```
**Service JWT issuer response**
Below is my service issues response and how I set `exp` and `iat` claims.
```
let now = new Date();
      let exp = new Date(now);
      exp.setSeconds(now.getSeconds() + 30);
      return {
        "access_token": {
            "aud": "test",
            "iss": "test",
            "sub": "1234567890qwertyuio",
            "jti": "mnb23vcsrt756yuiomnbvcx98ertyuiop",
            "roles": ["role_a", "role_b"],
            "exp": exp.getTime(),
            "iat": now.getTime()
        }
      }
```
**JWK endpoint result**
```
return {
        "keys": [
          {
            "kty": "oct",
            "k": "key",
            "kid": "test",
            "alg": "HS256"
          }
        ]
      }
```

**Comment by kpacha** [comment]
this is very weird, because this flow is used at the playground.

Compare your tokens with https://github.com/devopsfaith/krakend-playground/blob/master/data/token.json in order to be sure the `exp` and `iat` are well formated (maybe you need to use the `getSeconds()` function)

**Comment by mkolbusz** [comment]
@kpacha Thanks for your help and point the way to solve it. The problem was `getTime()` returns time in milliseconds but we need epoch time in seconds. Changing it to `Math.round(exp.getTime() / 1000)` fixed the problem.
