### ISSUE TITLE
2- way SSL offloading & routing based on header

### ISSUE THREAD

**Issue by ankit284** [devopsfaith/krakend-ce#159]
Hello Team,
We are evaluating KrakenD-CE. Would like to know few things that I didn't find in documentation:-
1. Can we route based on header / param - out of box?
2. Does it support two way SSL ? If yes can you please provide some documentation around it.

Thanks,
Ankit Singhai

**Comment by ariutk** [comment]
I join the question. I also need a routing based on header

**Comment by kpacha** [comment]
- you can route just by url, but you could add a plugin and change the url of the incoming requests depending on the header value
- 2 way SSL is not supported, but, again, you can customize it with some plugin
