### ISSUE TITLE
Use krakend-ce with mux

### ISSUE THREAD

**Issue by m33ch** [devopsfaith/krakend-ce#164]
Hi staff, i would use mux router instead of gin router.
I read that is possibile to fork krakend-ce repository customizing the router.
Files involved are router_engine.go,  handler_factory.go and executor.go. 

The problem is that there aren't all dependencies libraries for mux, 
for example:
- github.com/devopsfaith/krakend-botdetector -> missing mux implemetation
- github.com/devopsfaith/krakend-ratelimit/juju -> missing mux implemetation

Can you suggest how to customize krakend-ce version 1.0.0 with mux?
Do you have some example file already customized?
Thanks

**Comment by kpacha** [comment]
you are right: there are some KrakenD modules that do not support the mux router yet.

these tasks are on the backlog but they aren't near to the top at all, so if you need this implemented and build the missing components, please open some PRs and share them with the rest of the community.
