### ISSUE TITLE
JWT signed in backend 

### ISSUE THREAD

**Issue by mkolbusz** [devopsfaith/krakend-ce#165]
**Describe what are you trying to do**
I want to sign the JWT payload in my backend service and not use the Krakend signer, but return the signed token directly from backend service. Then I want to use Krakend validator to validate my token in Krakend gateway not in my backend. Is it possible?

**Your configuration file**
```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [
        "*"
      ],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "DELETE",
        "OPTIONS",
        "PATCH"
      ],
      "allow_headers": [
        "Authorization",
        "Content-Type",
        "Accept",
        "X-Auth-Token"
      ]
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "no-op",
  "name": "Name",
  "port": 8080,
  "endpoints": [
      {
      "endpoint": "/v1/login",
      "querystring_params": ["*"],
      "timeout": "5s",
      "method": "POST",
      "output_encoding": "no-op",
      "concurrent_calls": 1,
      "headers_to_pass": [
        "Content-Type"
      ],
      "backend": [
        {
          "url_pattern": "/v1/login",
          "encoding": "no-op",
          "sd": "static",
          "extra_config": {},
          "method": "POST",
          "host": [
            "http://users-service:3001"
          ],
          "disable_host_sanitize": false
        }
      ]
    },
    {
      "endpoint": "/v1/users/{id}",
      "querystring_params": ["*"],
      "timeout": "5s",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
            "alg": "HS256",
            "jwk-url": "http://users-service:3001/v1/jwk",
            "issuer": "issuer",
            "cache": true,
            "disable_jwk_security": true
        }
      },
      "output_encoding": "no-op",
      "concurrent_calls": 1,
      "headers_to_pass": [
        "Authorization",
        "Content-Type"
      ],
      "backend": [
        {
          "url_pattern": "/v1/users/{id}",
          "encoding": "no-op",
          "sd": "static",
          "extra_config": {},
          "method": "GET",
          "host": [
            "http://users-service:3001"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}
```
**Logs**
If I try to make a request using the generated token I see in the logs:
```
[GIN] 2019/12/17 - 22:35:09 | 200 |   49.077198ms |      172.19.0.1 | POST     /v1/login
[GIN] 2019/12/17 - 22:35:28 | 401 |     2.88628ms |      172.19.0.1 | GET      /v1/users/2
Error #01: no Keys has been found
```

**Comment by harish278** [comment]
I had a similar issue. Handling the following fixed it for me:
Signing JWT
- JWT should contain kid in its header
- Secret key used to sign should not be base 64 encoded
Validation in krakend-jose/validator
- JWKS should include kid
- Secret (k) should be base64 encoded in JWKS.

**Comment by dirk39** [comment]
I had the same issue. I solved it creating a custom plugin that accepts `client_id` and `client_secret`, create a new Http request and send the request to the backend.

**Comment by b3n3w** [comment]
Hi Guys,

i'm trying to figure out how to do the same procsess as questioned.  I switched currently from the express-gateway project to krakenD. In express-gateway i could just put my secret key by env to the proxy which automatically decoded the jwt token and attached the payload to the request body for all microservices. 
The authentication service which sign all the tokens sits also behind the api-gateway (without any token validation). 


Is there any responsible plugin which can decode the given bearer token in Authorization Header and attach the payload like roles and user_id to the request for backend ?

**Comment by alombarte** [comment]
@b3n3w maybe this helps? https://www.krakend.io/docs/authorization/jwt-validation/#passing-claims-to-the-backend-url
