### ISSUE TITLE
Writing plugins

### ISSUE THREAD

**Issue by rsasidar** [devopsfaith/krakend-ce#166]
I have a requirement for API gateway. Currently I am using Zuul, however evaluating krakend-ce and got few questions which is specific to my requirement.

1. I have a Token server(custom built), which create JWT token (some of the claims in the token include a tenantId and userId. 
2. Consumers use this token to access the backend APIs. With Zuul gateway , once the token is validated, we extract specific claims ( tenanted, userId in this case) and set in to the request header before forwarding the request to specific backend

Is this possible with Krakend ? Can this be achieved by writing a custom plugin ? Can someone help me with a sample plugin and steps. I am new to go/lua,

Any help is highly appreciated

Thanks,

**Comment by SananGuliyev** [comment]
You can use [krakend-martian](https://github.com/devopsfaith/krakend-martian). You can implement your modifier which can add the needed claims to the header before forwarding it to the specified backend. 

There is also a good article about how to do it: https://www.krakend.io/blog/website-development-as-a-sysadmin/
