### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by megakoresh** [devopsfaith/krakend-ce#171]
**Is your feature request related to a problem? Please describe.**
I need ability to authenticate and authorize requests against an LDAP server. For example by defining a group filter that users have to pass to access a certain endpoint.

**Describe the solution you'd like**
The best solution for me would be if Krakend supported this out of the box. Right now it just supports OAuth2 and if I want to use LDAP I would need to either code own middleware for this very common functionality, or use some kind of auth proxy.

**Describe alternatives you've considered**
Using auth proxies is another solution. For example [dex](https://github.com/dexidp/dex), but that increases operational complexity.

**Additional context**
N/A

**Comment by alombarte** [comment]
Closed the issue after 2 upvotes in 1 year
