### ISSUE TITLE
calling mix of parallel and serial backends within one endpoint configuration

### ISSUE THREAD

**Issue by venugopal-annamaneni** [devopsfaith/krakend-ce#176]
**Can we achieve this scenario within one Krakend Endpoint**

API-1 ------> API - 2  --------> API - 5
.....................    API - 3
.....................    API - 4

First Step : Call  API-1 
Second Step : Call API-2, API-3 & API-4 in parallel
Third Step :  Call API-5 finally

**Comment by kpacha** [comment]
I think you'll need 2 endpoints:

1. endpoint A could be doing the parallel requests (API 2, API 3 & API 4)
2. endpoint B could be the sequential one, calling API 1, then the endpoint A and, finally, the API 5



cheers

**Comment by venugopal-annamaneni** [comment]
Thanks for reverting.  I guess that wouldn't be ideal way and difficult to manage also. 
May be using this as a API gateway only makes sense rather than thinking it as an "aggregator" or "orchestrator"
