### ISSUE TITLE
Plugin are not working on devopsfaith/krakend:1.0 - __vfprintf_chk: symbol not found

### ISSUE THREAD

**Issue by mdiazp** [devopsfaith/krakend-ce#178]
**Describe the bug**
I'm trying to write a plugin but it is not working.

**Plugin implementation**
Actually it is the same krakend-example in the doc
```
package main
import (
	"context"
	"errors"
	"fmt"
	"html"
	"net/http"
)

// ClientRegisterer is the symbol the plugin loader will try to load. It must implement the RegisterClient interface
var ClientRegisterer = registerer("krakend-example")

type registerer string

func (r registerer) RegisterClients(f func(
	name string,
	handler func(context.Context, map[string]interface{}) (http.Handler, error),
)) {
	f(string(r), r.registerClients)
}

func (r registerer) registerClients(ctx context.Context, extra map[string]interface{}) (http.Handler, error) {
	// check the passed configuration and initialize the plugin
	name, ok := extra["name"].(string)
	if !ok {
		return nil, errors.New("wrong config")
	}
	if name != string(r) {
		return nil, fmt.Errorf("unknown register %s", name)
	}
	// return the actual handler wrapping or your custom logic so it can be used as a replacement for the default http client
	return &handler{}, nil
}

type handler struct{}

func (*handler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(w, "Hello, %q", html.EscapeString(req.URL.Path))
}

func init() {
	fmt.Println("krakend-example client plugin loaded!!!")
}

func main() {}
```

**krakend.json**
```
{
  "version": 2,
  "plugin": {
    "pattern":".so",
    "folder": "/etc/krakend/plugin/"
  },
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[APP_APIGATEWAY]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    }
  },
  "port": 443,
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "appointments-apigateway",
  "tls": {
    "public_key": "/etc/krakend/ssl/server/server-cert.pem",
    "private_key": "/etc/krakend/ssl/server/server-key.pem"
  },
  "read_timeout": "5s",
  "write_timeout": "5s",
  "idle_timeout": "5s",
  "read_header_timeout": "2s",
  "endpoints": [
    {
      "endpoint": "/test",
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/test",
          "encoding": "json",
          "sd": "static",
          "host": [
            "http://test"
          ],
          "disable_host_sanitize": false,
          "is_collection": false,
          "target": "",
          "blacklist": [],
          "extra_config": {
            "github.com/devopsfaith/krakend/transport/http/client/executor": {
                "name": "krakend-example"
            }
          }
        }
      ]
    }
  ]
}
```
**Commands used**
I'm using this docker image devopsfaith/krakend:1.0.
The definition for krakend in docker-compose  is:
```
apigateway:
    image: devopsfaith/krakend:1.0
    ports:
      - "443:443"
    volumes:
      - "./apigateway/krakend.json:/etc/krakend/krakend.json"
      - "./apigateway/plugin:/etc/krakend/plugin"
      - "./apigateway/ssl:/etc/krakend/ssl"
    restart: "unless-stopped"
```
**Logs**
[APP_APIGATEWAY] 2020/02/18 - 19:07:40.552 ▶ ERROR unable to create the GELF writer: getting the extra config for the krakend-gelf module
[APP_APIGATEWAY] 2020/02/18 - 19:07:40.552 ▶ INFO Listening on port: 443
[APP_APIGATEWAY] 2020/02/18 - 19:07:40.562 ▶ INFO registering usage stats for cluster ID 'eWEno2JrFOqtitbWwpthztveTvrBLF1nnW/+MP9cP/M='
[APP_APIGATEWAY] 2020/02/18 - 19:07:40.566 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugin/krakend-example.so): plugin.Open("/etc/krakend/plugin/krakend-example.so"): Error relocating /etc/krakend/plugin/krakend-example.so: __vfprintf_chk: symbol not found

**Comment by kpacha** [comment]
@mdiazp the docker image 1.0 does not support plugins as it was build on top of alpine. After https://github.com/devopsfaith/krakend-ce/pull/179, it should be fixed for the next release (1.1.0) planned for the next week

**Comment by mdiazp** [comment]
> @mdiazp the docker image 1.0 does not support plugins as it was build on top of alpine. After #179, it should be fixed for the next release (1.1.0) planned for the next week

Thanks for the feedback.
So what image can I use that work with plugins until next release ?

**Comment by taik0** [comment]
> So what image can I use that work with plugins until next release ?

The tgz/deb/rpm can be used with plugins since it's not compiled for alpine. You can build the docker image with that binary. 
Like @kpacha said, 1.1.0 release is planned for next week and will fix this issue.

**Comment by kpacha** [comment]
@mdiazp the 1.1.0 was published yesterday.

cheers!
