### ISSUE TITLE
How to configure crackend to listen to a specific interface.

### ISSUE THREAD

**Issue by gosha20777** [devopsfaith/krakend-ce#180]
I set up a crackend gateway to listen on port 8080. But when I access my server on port 8080 from an external network, my requests are processed by a gateway.

I would like to be able to access the gateway only from localhost. Is it possible? Of course I can configure the IP tables on my server. But can I somehow avoid this?

I found only such settings:
```json
"github_com/devopsfaith/krakend-cors": {
      "allow_origins": [ "http://localhost:8080", "http://localhost:80" ],
      "allow_methods": [ "POST", "GET" ],
      "max_age": "12h"
    },
```
But after their application, nothing happened

**My configuration file**
```json
{
    "version": 2,
    "name": "My lovely gateway",
    "host": [ "http://127.0.0.1:8080" ],
    "cache_ttl": "3600s",
    "timeout": "3s",
    "extra_config": {
      "github_com/devopsfaith/krakend-gologging": {
        "level":  "DEBUG",
        "prefix": "[KRAKEND]",
        "syslog": false,
        "stdout": true
      },
      "github_com/devopsfaith/krakend-metrics": {
        "collection_time": "60s",
        "proxy_disabled": false,
        "router_disabled": false,
        "backend_disabled": false,
        "endpoint_disabled": false,
        "listen_address": ":8090"
      },
      "github_com/devopsfaith/krakend-cors": {
        "allow_origins": [ "http://localhost:80", "http://localhost:8080" ],
        "allow_methods": [ "POST", "GET" ],
        "max_age": "12h"
      }
    },
    "endpoints": [
        {
        .....
        }
    ]
}
```
**Commands used**
`krakend run -c krakend.json`

**Comment by kpacha** [comment]
the CORS component is just responsible for dealing with OPTION requests sent by the browsers before processing any other request from the JS

there is no way no bind the service to an interface but maybe you could use https://github.com/devopsfaith/krakend-httpsecure in order to restrict the allowed host headers
