### ISSUE TITLE
custom module for health check

### ISSUE THREAD

**Issue by p3ym4n** [devopsfaith/krakend-ce#184]
Hi everybody,
I am implementing a health check endpoint for my KrakenD instance and it seems very cumbersome to implement in a way that we have used for our previous services and I was thinking it can be more flexible than what it is.

**Is your feature request related to a problem? Please describe.**
implementing a health check endpoint with current options is hard and not delivering a desirable result:
- using fake backend results in logging error.
- activating debug mode is not possible for production environments.
- using martian only changes the response body, not the header.

**Describe the solution you'd like**
As can be seen [here](https://inadarei.github.io/rfc-healthcheck/) there is a draft for standard, but every company may have their own conventions, like our convention which is code 204 for success and 503 for error with the empty response body.

Also, because of the stateless design of KrakenD, I have no idea for error situations. but for success situations having a module with this config where `path`, `code` & `body` can change is good:

```json
{
    "path" : "/healthz",
    "success" : {
        "code" : "204",
        "body" : "",
    },
    "error" : {
        "code" : "503",
        "body" : "",
    }
}
```

**Comment by kpacha** [comment]
You can try with LUA and the `skip_next` flag enabled, so no backend is contacted, or you can go with a custom plugin (also avoiding hitting an external service), or even, you could just collect the health_check from every backend used by the gateway

as you said, every company uses it's own standard and even your generic proposal could fall short in terms of customization options

**Comment by p3ym4n** [comment]
Thank you for fast response, Yes my solution don't support all situations.
I think collecting backends health results is not a good option.
but if it can be done in LUA I think it's ok.
