### ISSUE TITLE
localhost with with https backend

### ISSUE THREAD

**Issue by adityanmishra** [devopsfaith/krakend-ce#186]
Hi, i am testing this gateway. I am trying to run krakend on port 8080 on my laptop and trying an url which is https. I am getting x509: certificate signed by unknown authority error. Can anyone let me know where should i put client public certificates to make it work? 
krakend documentation provides overall certificate configuration to run krakend on 443

**Comment by kpacha** [comment]
the internal http clients check the backend certificate against the system CA. how and where to place the certs so it's trusted by the system depends on your OS

**Comment by adityanmishra** [comment]
We are using the docker image provided by devopsfaith which is alpine in nature. As suggested after adding the certificates to the OS it starts working.
