### ISSUE TITLE
Plugins load error

### ISSUE THREAD

**Issue by angomablaise** [devopsfaith/krakend-ce#187]
WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugin/grpc-gateway-post.so): plugin.Open("/etc/krakend/plugin/grpc-gateway-post"): plugin was built with a different version of package internal/cpu

I have got this message when I try to use the plugin in the latest krakend docker 

I am using a linux ubuntu for OS to run my backend server

**Comment by kpacha** [comment]
as the log says, the plugin should be compiled using the same versions of the go package and the common deps.

are you compiling with go 1.14.0?

**Comment by angomablaise** [comment]
I am compiling with go1.13.8

**Comment by kpacha** [comment]
that should be the problem. try upgrading or using the latest docker image

**Comment by angomablaise** [comment]
After updating the go to 1.4. the internal/cpu message is resolved but I got the new one : plugin was built with a different version of package google.golang.org/grpc/codes
 I have then updated google.golang.org/grpc from v1.20.1 to  v1.27.1 but I still have the same second error message. What grpc version is used ?

**Comment by kpacha** [comment]
the go.mod and go.sum contain the list of versions.

as you can see at https://github.com/devopsfaith/krakend-ce/blob/v1.1.0/go.sum#L1024
the v1.1.0 is using google.golang.org/grpc v1.27.1.

**Comment by angomablaise** [comment]
I want now if the way to write the plugin has changed or is it like in the tutorial : 

`package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/multiagentmicroserviceautomation/Backend/gateway"
)

func init() {
	fmt.Println("krakend-grpc-post plugin loaded!!!")
}

var ClientRegisterer = registerer("grpc-post")

type registerer string

func (r registerer) RegisterClients(f func(
	name string,
	handler func(context.Context, map[string]interface{}) (http.Handler, error),
)) {
	f(string(r), func(ctx context.Context, extra map[string]interface{}) (http.Handler, error) {
		cfg := parse(extra)
		if cfg == nil {
			return nil, errors.New("wrong config")
		}
		if cfg.name != string(r) {
			return nil, fmt.Errorf("unknown register %s", cfg.name)
		}
		return gateway.New(ctx, cfg.helloEndpoint, cfg.routeEndpoint)
	})
}

func parse(extra map[string]interface{}) *opts {
	name, ok := extra["name"].(string)
	if !ok {
		return nil
	}

	rawEs, ok := extra["endpoints"]
	if !ok {
		return nil
	}
	es, ok := rawEs.([]interface{})
	if !ok || len(es) < 2 {
		return nil
	}
	endpoints := make([]string, len(es))
	for i, e := range es {
		endpoints[i] = e.(string)
	}

	return &opts{
		name:          name,
		helloEndpoint: endpoints[0],
		routeEndpoint: endpoints[1],
	}
}

type opts struct {
	name          string
	helloEndpoint string
	routeEndpoint string
}`

**Comment by kpacha** [comment]
there is another example in the documentation that is up to date: https://pkg.go.dev/github.com/devopsfaith/krakend/transport/http/client/plugin?tab=doc

**Comment by angomablaise** [comment]
Thanks
