### ISSUE TITLE
Got "plugin was built with a different version of package [errors | internal/cpu | sync/atomic]"

### ISSUE THREAD

**Issue by dorian-y** [devopsfaith/krakend-ce#195]
**Describe what are you trying to do**
I am trying to create, build and load a custom Plugin into Krakend_CE

I am using Krakend_CE 1.1.0 / devopsfaith/krakend:1.1.0
I checked the version of Krakend used in https://github.com/devopsfaith/krakend-ce/blob/v1.1.0/go.mod : `1.12`
For my build operation, I tried several versions of Golang with different Go Build Commands but I get quite the same error, with different package indicated :
- 1.12
  - command : `go build -buildmode=plugin -o ../../plugins/my-plugin.so`
  - error : `plugin.Open("/etc/krakend/plugin/my-plugin"): plugin was built with a different version of package internal/cpu`
- 1.12.9
  - command : `go build -buildmode=plugin -o ../../plugins/my-plugin.so`
  - error : `plugin.Open("/etc/krakend/plugin/my-plugin"): plugin was built with a different version of package errors`
- 1.13.3
  - commands tried : 
     - go build -buildmode=plugin -o ../../plugins/my-plugin.so
     - go build -trimpath -buildmode=plugin -o ../../plugins/my-plugin.so
  - error : `plugin.Open("/etc/krakend/plugin/my-plugin"): plugin was built with a different version of package sync/atomic`

**Your configuration file**
The content of my `krakend.json` file :
```
{
  "version": 2,
  "plugin": { 
    "folder": "/etc/krakend/plugin/",
    "pattern": ".so"
  },
  "endpoints": [
    {
      "endpoint": "/myendpoint1",
      "backend": [
        {
          "url_pattern": "/myurl1",
          "host": [
            "https://myhost1"
          ],
          "extra_config": {
            "github.com/devopsfaith/krakend-martian": {
              "header.Modifier": {
                "scope": ["request"],
                "name": "Authorization",
                "value": "Bearer mybearer"
              }
            },
            "github_com/devopsfaith/krakend/transport/http/server/handler": {
              "name": "myPluginModifier",
              "mockkey": "mockvalue"
            }
          },
          "whitelist": ["data"],
          "group": "mygroup1"
        }
      ]
    }
}
```

**Plugin content**
I used the same content than the example : https://godoc.org/github.com/devopsfaith/krakend/transport/http/server/plugin

I just changed the registration.
```
var HandlerRegisterer = registerer("myPluginModifier")
```

**Commands used**
```
go1.12 clean -cache
go1.12 get -d -v ./gateway/src/my-plugin-dir
cd ./gateway/src/my-plugin-dir
go1.12 build -buildmode=plugin -o ../../plugins/my-plugin.so
docker-compose up -d --build
```
with docker-compose.yml
```
version: '3.7'
services:
  # API Gateway
  krakend_ce:
    image: devopsfaith/krakend:1.1.0
    volumes:
      - ./scripts/krakend/krakend.json:/etc/krakend/krakend.json
      - ./gateway/plugins/:/etc/krakend/plugin
    ports:
      - "8066:8080"
```

**Logs**
```
Parsing configuration file: /etc/krakend/krakend.json
2020/03/10 16:45:24  ERROR: unable to create the gologging logger: getting the extra config for the krakend-gologging module
2020/03/10 16:45:24  ERROR: unable to create the GELF writer: getting the extra config for the krakend-gelf module
2020/03/10 16:45:24  INFO: Listening on port: 8080
2020/03/10 16:45:24  INFO: registering usage stats for cluster ID '2iD93d'
2020/03/10 16:45:24  WARNING: loading plugins: plugin loader found 1 error(s):
opening plugin 0 (/etc/krakend/plugin/my-plugin.so): plugin.Open("/etc/krakend/plugin/my-plugin"): plugin was built with a different version of package sync/atomic
2020/03/10 16:45:24  INFO: total http executor plugins loaded: 0
2020/03/10 16:45:24  WARNING: loading plugins: plugin loader found 1 error(s):
opening plugin 0 (/etc/krakend/plugin/my-plugin.so): plugin.Open("/etc/krakend/plugin/my-plugin.so"): plugin was built with a different version of package sync/atomic (previous failure)
2020/03/10 16:45:24  INFO: total http handler plugins loaded: 0
2020/03/10 16:45:24  DEBUG: creating a new influxdb client
2020/03/10 16:45:24  DEBUG: no config for the influxdb client. Aborting
2020/03/10 16:45:24  WARNING: influxdb: unable to load custom config
2020/03/10 16:45:24  WARNING: opencensus: no extra config defined for the opencensus module
2020/03/10 16:45:24  WARNING: building the etcd client: unable to create the etcd client: no config
2020/03/10 16:45:24  DEBUG: no config for the bloomfilter
2020/03/10 16:45:24  WARNING: bloomFilter: no config for the bloomfilter
2020/03/10 16:45:24  WARNING: no config present for the httpsecure module
2020/03/10 16:45:24  DEBUG: lua: no extra config
2020/03/10 16:45:24  DEBUG: botdetector middleware:  no config defined for the module
2020/03/10 16:45:24  DEBUG: AMQP: https://myhost: no amqp consumer defined
2020/03/10 16:45:24  DEBUG: AMQP: https://myhost: no amqp producer defined
2020/03/10 16:45:24  DEBUG: pubsub: subscriber (https://myhost): github.com/devopsfaith/krakend-pubsub/subscriber not found in the extra config
2020/03/10 16:45:24  DEBUG: pubsub: publisher (https://myhost): github.com/devopsfaith/krakend-pubsub/publisher not found in the extra config
2020/03/10 16:45:24  DEBUG: http-request-executor: no extra config for backend /myurl1
2020/03/10 16:45:24  DEBUG: CEL: no extra config detected for backend /myurl1
2020/03/10 16:45:24  DEBUG: lua: no extra config
2020/03/10 16:45:24  DEBUG: CEL: no extra config detected for pipe /myendpoint1
2020/03/10 16:45:24  DEBUG: lua: no extra config
2020/03/10 16:45:24  INFO: JOSE: singer disabled for the endpoint /myendpoint1
2020/03/10 16:45:24  DEBUG: lua: no extra config
2020/03/10 16:45:24  INFO: JOSE: validator disabled for the endpoint /myendpoint1
2020/03/10 16:45:24  DEBUG: botdetector:  no config defined for the module
2020/03/10 16:45:24  DEBUG: http-server-handler: no extra config
```

**Comment by kpacha** [comment]
the version is not in the go.mod. each KrakenD release is built using the go version defined at the Makefile, for v1.1.0 and v1.1.1 it was go1.14.0 (https://github.com/devopsfaith/krakend-ce/blob/v1.1.0/Makefile#L21)

**Comment by dorian-y** [comment]
Thanks, I built with go1.14, and now I got the following 

`plugin was built with a different version of package github.com/devopsfaith/krakend-martian/register`

```
2020/03/10 17:31:44  WARNING: loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugin/my-plugin.so): plugin.Open("/etc/krakend/plugin/my-plugin"): plugin was built with a different version of package github.com/devopsfaith/krakend-martian/register
2020/03/10 17:31:44  INFO: total http executor plugins loaded: 0
2020/03/10 17:31:44  WARNING: loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugin/my-plugin): plugin.Open("/etc/krakend/plugin/my-plugin.so"): plugin was built with a different version of package github.com/devopsfaith/krakend-martian/register (previous failure)
2020/03/10 17:31:44  INFO: total http handler plugins loaded: 0

```

**Comment by kpacha** [comment]
you can check the version of every dependency at the go.mod and go.sum files. https://github.com/devopsfaith/krakend-ce/blob/v1.1.0/go.mod#L52

but be aware of two of the big limitations of go plugins: 

1. interfaces are hard to pass between the plugin and the binary and the other way around
2. the plugin can not try to define a command flag already in use

I'm listing them because they are the reason why we can't support injecting martian modifiers, validators and filters with plugins. I remember hitting the wall with this line: https://github.com/google/martian/blob/b99070ab9f10410a3f8d25fae01dd611a6cc79ff/init.go#L24

if you try to load a plugin using the martian package, it will try to redeclare that same flag and the binary will panic

**Comment by dorian-y** [comment]
Understood, thanks for those details. I have just removed martian register and I seems better.

But using the same code as shown here : https://godoc.org/github.com/devopsfaith/krakend/transport/http/server/plugin
I have the following message : 
`plugin: symbol ClientRegisterer not found in plugin`
Indeed I use the following symbol : `var HandlerRegisterer = registerer("krakend-example")`

Any ideas ?

**Comment by kpacha** [comment]
there are 2 plugin loaders at the current versions of the gateway. every plugin loader inspects all the plugins looking for a symbol (a `ClientRegisterer` or a `HandlerRegisterer`) and report the failures. if you have a single plugin exposing just one of the expected symbols you'll see the KrakenD reporting a success and a failure. in your scenario, it should report a failure loading the plugin as a client and a success as a handler

```
WARNIN loading plugins: plugin loader found 1 error(s):
opening plugin 0 (/etc/krakend/plugin/my-plugin.so): plugin: symbol ClientRegisterer not found in plugin ...
INFO: total http executor plugins loaded: 0
INFO: total http handler plugins loaded: 1
```

**Comment by dorian-y** [comment]
Thanks that's clearer for me. 
I might quit the initial topic but : I first went into creating a custom plugin in order to perform specific modifications of the response of backend calls (that I could not perform with default Martian modifiers). Could you confirm that creating a Handler Plugin is the way to go?

**Comment by kpacha** [comment]
you can modify the backend responses at the client level. at the server level you can modify the final response of the gateway

**Comment by dorian-y** [comment]
Ok, I am not sure to get the point from a krakend implementation point of view. 
I will create a separate ticket to dig into this subject.

The main purpose to include plugin has been covered, thank you again.
