### ISSUE TITLE
Dockerfile: specify user's UID instead of username in USER directive

### ISSUE THREAD

**Issue by fvillain** [devopsfaith/krakend-ce#196]
There is a problem with the dockerfile, i missed it when I saw the PR : https://github.com/devopsfaith/krakend-ce/pull/193/files#diff-3254677a7917c6c01f55212f86c57fbfR14

You need to set the UID in the USER command of the Dockerfile, otherwise you cannot deploy when using Pod Security Policies by default

You need to have:

```USER 1000 # if the userid you created has uid 1000```

not:

```USER krakend```

Could you patch it please ?

You have the needed syntax in my previous issue: https://github.com/devopsfaith/krakend-ce/issues/188

**Comment by taik0** [comment]
Sorry for taking so long to fix this.
