### ISSUE TITLE
Send a custom format Endpoint response from Backends to Final client

### ISSUE THREAD

**Issue by dorian-y** [devopsfaith/krakend-ce#197]
**Describe what are you trying to do**
I have several "datatypes" backend with same response structure :
Here example for backend "/datatypeA"
```
{
  "data": [
      {
         "code": "LABEL_A1"
         "label": "The label A1"
         "type": "datatype_A"
       },
       {
         "code": "LABEL_A2"
          "label": "The label A2"
          "type": "datatype_A"
      }
   ]
}
```

I want to unify those backend responses into the response of my krakend-endpoint "mydatatypes" this way :
```
{
  "datatype_A": {
    "LABEL_A1": "The label A1",
    "LABEL_A2": "The label A2"
  },
  "datatype_B": {
    "LABEL_B1": "The label B1",
    "LABEL_B2": "The label B2"
  }
}
```

**Your configuration file**
```
{
  "version": 2,
  "plugin": { 
    "folder": "/etc/krakend/plugin/",
    "pattern": ".so"
  },
  "endpoints": [
    {
      "endpoint": "/mydatatypes",
      "backend": [
        {
          "url_pattern": "/datatypeA",
          "host": [
            "https://myhost1"
          ],
          "whitelist": ["data"],
          "group": "datatype_A"
        },
        {
          "url_pattern": "/datatypeB",
          "host": [
            "https://myhost1"
          ],
          "whitelist": ["data"],
          "group": "datatype_B"
        }
      ]
    }
}
```

I tried "data manipulation" capabilities, but I was limited in this case.
I tried to create a plugin (see issues/195) but discovered that martian modifiers cannot be injected.

Do you please have any implementation suggestion for this case? :pray:

**Comment by alombarte** [comment]
Hi @dorian-y, your example needs a lot of custom logic, and this goes beyond pure transformation. You think you should create a [LUA script](https://www.krakend.io/docs/endpoints/lua/) to get these transformations done.
