### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by yuwono95** [devopsfaith/krakend-ce#198]
I'm trying to upgrade KrakenD from 1.0.0 to 1.1.1.

But it failed to run after pulling the latest:
`docker pull devopsfaith/krakend:latest`
  
Using the usual docker run command:
`docker run -dit --restart always -p 8080:8080 -v $PWD:/etc/krakend/ --name krakend devopsfaith/krakend`

The error message:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/etc/krakend\") set in config.json failed: permission denied": unknown.

I'm using **root** user.

Downgrade again to 1.0.0 and it works again (using the same docker run command).

I think it has anything to do with user permission [#196](https://github.com/devopsfaith/krakend-ce/issues/196) 

Any clue?

**Comment by alombarte** [comment]
Hi @yuwono95 ,

```
 ~ ❯ docker pull devopsfaith/krakend:latest
latest: Pulling from devopsfaith/krakend
68ced04f60ab: Already exists 
87362bb72106: Pull complete 
1f015a909f31: Pull complete 
109ba7fd74c4: Pull complete 
de73f82d85f5: Pull complete 
Digest: sha256:acbc84b369eec351dc3ba4f60d9f42a23c10f45dd369c4d91f30ceb4b983a893
Status: Downloaded newer image for devopsfaith/krakend:latest
docker.io/devopsfaith/krakend:latest
 ~ ❯ docker run -it -p 8080:8080 -v "$PWD:/etc/krakend" devopsfaith/krakend
Parsing configuration file: /etc/krakend/krakend.json
[KRAKEND] 2020/03/12 - 12:48:36.501 ▶ INFO Listening on port: 8080
[KRAKEND] 2020/03/12 - 12:48:36.501 ▶ DEBUG creating a new influxdb client
...
```
As you can see, **it works on my machine**!

Now seriously, where are you launching this and what is the context and environment. Is it possible that you are restarting the container that it was launched with the previous version?

There must be some caching issue here with the Docker registry :thinking:

**Comment by taik0** [comment]
I think the issue may be that the volume that's been mounted on `/etc/krakend` only has read/execution permissions for root. Can you check that?

**Comment by yuwono95** [comment]
@taik0 , you're right. The new installation must use "krakend" user (UID: 1000). While my $PWD is on the "root" user. So, to resolve this:
1. Make a new directory to hold the krakend.json
`mkdir krakend`
2. Copy krakend.json there
`cp krakend.json krakend/`
3. Change the directory owner
` chown 1000:1000 -R krakend`
4. Run like this:
docker run -p 8080:8080 -v $PWD/krakend:/etc/krakend/ --name krakend devopsfaith/krakend

Now the new version working flawlessly.

@alombarte I think you have no trouble because you already use "krakend" user on the config directory.

I think the new version should be refined to accommodate users like me.
