### ISSUE TITLE
What about api lifecycle management and developer portal ?

### ISSUE THREAD

**Issue by deka** [devopsfaith/krakend-ce#20]
There exists some of this features with krakend ?
- The documentation of the Rest APIs (swagger, etc.) with examples cURL , Try-It , search features ...
- A self-enrollment or enrollment mechanism subject to authorization, to issue an API key (API_KEY) or a pair (client_id / secret) for OAuth2 or OIDC,
- The ability to track consumption by application,
- And other features to facilitate API lifecycle management

Thanks

**Comment by alombarte** [comment]
Hi @deka,
Our [Designer](http://designer.krakend.io) is the first approach to a developer portal. But KrakenD-CE is not a SaaS so we need to make sure that you are in control and able to host it in your own side.

- The Swagger is currently under consideration. 
- Not sure what you want to accomplish with this mechanism to issue an API key, but KrakenD-CE won't issue API keys ever. Not the responsibility of this software  (in any case we would write another piece)
- You have metrics available and you can export them wherever you want. There are users that use them to take decisions that impact the behavior of the system.

Finally, KrakenD has focused on being a pure API gateway and to offer performance. Is not our goal to compete or compare to API management products. I believe that we still drag some of this wording in the website, but anything causing this confusion will go away.

**Comment by deka** [comment]
Thanks @alombarte 
Do you know projects with the aim of extending krakend's functionality with developer portal features ?

**Comment by alombarte** [comment]
I am not completely sure what you are looking for, but I worked a couple of years with this:
https://www.3scale.net/
Hope it helps

**Comment by NellaguttaPraveen** [comment]
@alombarte,
Is there any Tutorial/Developer guide to learn about KrakenD API Gateway. I Am trying to access one microservice but not able to, which has OAuth Token and few header.
