### ISSUE TITLE
Return response from within Lua script and stop proxying to backend?

### ISSUE THREAD

**Issue by cdennig** [devopsfaith/krakend-ce#204]
Hi there,

I have a question regarding Lua scripting. Is it possible to send an immediate response to the client from within a Lua script without further querying the backend?

Consider this situation:

I have a header value sent from the client that **must match** a value in the JWT token. I can check for that value in the lua script (currently in the backend section "github.com/devopsfaith/krakend-lua/proxy/backend" with the "pre" hook). Now, I would like to stop the request to be sent to the backend, if that condition fails and immediately send a "403" back...so that no request is proxied to the backend.

Is that possible? Any help is appreciated! 

Many thanks!

**Comment by kpacha** [comment]
@cdennig that's not possible right now but I think it's a great idea. I'm adding it to the backlog

thanks for such a valuable feedback!

there are so many questions we should answer before starting the prototype, such as:
- how many error types should be exposed (LuaError for generic internal cases, and HttpError for returning a parametrized http error with status code)?
- should an error always abort the execution of the pipe?
- if the execution is not aborted, should we implement some try/catch/recover mechanism?

**Comment by cdennig** [comment]
From a client perspective, I think it's only interesting **why** a request is failing (HTTP error should be sufficient). That said, as a developer, I would like to have a bit more control, of course :) Maybe introduce a "context" object that can be used to control whether a request should be aborted and why (error information within the context)?! You could check that context object in every step of the pipe.

I would not introduce any kind of try/catch mechanism to keep things clear.  When an error occurs, abort the pipe. But there may be cases I don't see at the moment.

**Comment by kpacha** [comment]
Interesting... I was hoping to avoid try/catch but I didn't think about the error stacktrace.

I'd keep the generic error just because http is not the only transport protocol you could use to consume the krakend gateway.

again, thanks for the great feedback

**Comment by nickshatilo** [comment]
Hey! This is a needed feature for us. An updates on this one?

**Comment by kpacha** [comment]
we'll include new helpers `custom_error('expect me')` and `custom_error('expect me', 999)`  in the next release

**Comment by cdennig** [comment]
Is the second parameter supposed to be the Http status code?

**Comment by kpacha** [comment]
> Is the second parameter supposed to be the Http status code?

yes, it is
