### ISSUE TITLE
How to implement a cross-cutting concern? 

### ISSUE THREAD

**Issue by limadelrey** [devopsfaith/krakend-ce#207]
Hi everyone. I have a requirement that seems to me as a cross-cutting concern, so I instantly thought of using KrakenD middleware in order to implement it. However, I don't really know how to do it.

My platform consists on multiple microservices that allow users to manipulate different objects in multiple languages by using REST APIs. Available languages are set on one of this microservices. Instead of adding a validation on every request on every single microservice I was hopping to do it on gateway level, just like I'm doing with token validation.

An example of that would be:
- Service A lists all available languages (**en_gb**, **pt_pt**);
- Service B lists all objects in given a language;
- Gateway exposes a route to Service B which validates if language exists on Service A.

Success case: User makes a request on **en_gb** via gateway and it returns successfully;
Error case: User makes a request on **es_es** via gateway and it returns an error.

Is it possible to do it? If it is, do you have any documentation on this?

Thanks in advance.

**Comment by alombarte** [comment]
Hi @limadelrey,
Have a look at https://www.krakend.io/docs/endpoints/sequential-proxy/

**Comment by limadelrey** [comment]
Hi @alombarte,
Thank you for answering. I'll take a look on the documentation and assure if it helps solving my requirement codewise. I'll give an update on this later.

**Comment by limadelrey** [comment]
Hi again,
I made it work by using sequential proxy. However, there's multiple side effects which prevents me of using this solution: 

1) **It doesn't return service A error code + error message**
If some user tries to read an object in a language that doesn't exist (e.g. es_es), instead of getting "404 - Language es_es not found" (service A error code + error message), the user just receives "500 - Internal Server Error" from KrakenD.

2) **Responses are being merged**
If some user tries to read an object in a language that does actually exists, instead of only getting the list of objects in that given language (service B success message), the user is receiving that list + service A success message.

I was really expecting something similar to token validation. More like the behaviour of "github.com/devopsfaith/krakend-jose/validator" and the usage of jwk-url field to set which URL is used to verify the authenticity and integrity of the token.
