### ISSUE TITLE
Server-Sent Events (SSE)

### ISSUE THREAD

**Issue by limadelrey** [devopsfaith/krakend-ce#208]
Hi again.
Is SSE supported by KrakenD currently? If not, is it on its roadmap?

**Comment by jallaix** [comment]
Hello,
I've made some tests as I also require this feature, but unfortunately it doesn't seem to work.
Krakend quickly closes the connection to the server.
I'll make more tests by tweaking timouts but I'll probably have to not use my SSE component behind KrakenD.

**Comment by kpacha** [comment]
No, the feature is not supported. There are some concerns regarding its possible impact on the performance due the number of connections it could require.

**Comment by samail** [comment]
Hi everyone, 

Is there any progress or news on this topic ? 

Thank you

**Comment by cedricjimenezst** [comment]
+1

**Comment by ricardomoreirab** [comment]
+1

**Comment by FredyR4zox** [comment]
Hello,

Any update on this?
Has anyone tested SSE with krakend?

Thank you

**Comment by thegoncalomartins** [comment]
➕ 1️⃣

**Comment by alombarte** [comment]
Closing the issue.
SSE is not planned any time soon and the issue only received 5 upvotes in 1 year

**Comment by alombarte** [comment]
SSE has become more relevant now, so this will be revisited an developed on https://github.com/krakend/krakend-sse
