### ISSUE TITLE
Using endpoint variables to service discovery

### ISSUE THREAD

**Issue by batoyu** [devopsfaith/krakend-ce#215]
Can i use the variables in the dynamic service discovery?
my config endpoint section.

"endpoints": [
    {
      "endpoint": "/service/{servicename}/{endpoint}",
      "querystring_params":[  
        "*"
      ],
      "description": "This is a consul service",
      "method": "POST",
      "extra_config": {},
      "output_encoding": "no-op",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/{endpoint}",
          "encoding": "no-op",
          "sd": "dns",
          "host": [
            "{servicename}.service.consul.srv"
          ],
          "disable_host_sanitize": true,
          "is_collection": true,
          "target": "",
          "method": "POST"
        }
      ]
    },

**Comment by kpacha** [comment]
hi, @batoyu and welcome to the KrakenD community.

That's not supported because pure routing it's outside the scope of the project. Also, the SD module is not designed to handle variables since it would add tones of complexity and impact on the performance and resilience of the integration
