### ISSUE TITLE
roles_key from Auth0 in playground can not be accessed

### ISSUE THREAD

**Issue by yuswaldi** [devopsfaith/krakend-ce#217]
**Try krakend playground**
Hi everyone, I want to try krakend playground in my Ubuntu laptop. I have already setup Auth0 for endpoint /private/auth0 validation, after login I receive JWT payload data like this :

{
  "http://gip.net/roles": [
    "admin",
    "staff",
    "user"
  ],
  "iss": "https://dev-gipoauth.auth0.com/",
  "sub": "google-oauth2|116898880090498844890",
  "aud": [
    "https://gip-api.act.id",
    "https://dev-gipoauth.auth0.com/userinfo"
  ],
  "iat": 1591688597,
  "exp": 1591695797,
  "azp": "wMUR6zRLM0qCvrx3wwGjChBD12hFkySQ",
  "scope": "openid profile read:messages",
  "permissions": [
    "read:messages"
  ]
}

**and on endpoint validation like this :** 

{
      "endpoint": "/private/auth0",
      "backend": [
        {
          "url_pattern": "/user/1.json"
        }
      ],
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "audience": ["https://gip-api.act.id"],
          "roles_key": "http://gip.net/roles",
          "roles": [
            "admin",
            "operator"
          ],
          "jwk-url": "https://dev-gipoauth.auth0.com/.well-known/jwks.json"
        }
      }
    },

when I try to ping private endpoint I always get forbidden message,
but if I make empty the roles value I can get value from backend

Can anyone explain what is wrong with my configuration? 

Thanks

**Comment by kpacha** [comment]
it looks like it's a bug introduced at https://github.com/devopsfaith/krakend-jose/pull/23

thanks for the heads up!

**Comment by yuswaldi** [comment]
Thank you for your fixing
I appreciate so much  
Great job
