### ISSUE TITLE
Does Krakend Provide Access Token

### ISSUE THREAD

**Issue by SanyamKode** [devopsfaith/krakend-ce#226]
Is there any feature in krakenD using which we can generate a security/access token. We want to provide that token to our third parties so that only they can access our services by passing that token in header. Also that token should be valid for only defined time duration.

**Comment by kpacha** [comment]
KrakenD supports oauth2 authorization using JWT. Check the documentation: https://www.krakend.io/docs/authorization/jwt-overview/
