### ISSUE TITLE
ERROR Unable to load custom config from the extra config (Version: 0.5.1)

### ISSUE THREAD

**Issue by krema** [devopsfaith/krakend-ce#23]
Hi there,

On start up I always get this error message

    ERROR Unable to load custom config from the extra config

I am not sure what is wrong with the configuration. I _always_ get http response code 500 when I try to access the resource. I believe it is related to that error message on start up.

**Following situation:**

_Resources_
  http://192.168.178.44:8000/posts

_Log_
[GIN] 2018/06/25 - 23:56:18 | **500** |    8.315425ms |  192.168.178.44 |  GET     /posts

Why do I always get the 500 error? It should work! Appreciate your help.

Thanks

**Config file created with the designer:**

    {
      "version": 2,
      "extra_config": {
        "github_com/devopsfaith/krakend-gologging": {
          "level": "DEBUG",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true
        },
        "krakendesigner": {
          "endpoint_defaults": {
            "github.com/devopsfaith/krakend-ratelimit/juju/router": {
              "maxRate": 0,
              "clientMaxRate": 0
            }
          }
        },
        "github_com/devopsfaith/krakend-etcd": {
          "dial_timeout": "5s",
          "dial_keepalive": "30s",
          "header_timeout": "1s"
        },
        "github_com/devopsfaith/krakend-oauth2-clientcredentials": {
          "is_disabled": true,
          "endpoint_params": {}
        },
        "github_com/devopsfaith/krakend-httpsecure": {
          "disable": true,
          "allowed_hosts": [],
          "ssl_proxy_headers": {}
        },
        "github_com/devopsfaith/krakend-opencensus": {
          "sample_rate": 100,
          "reporting_period": 1,
          "exporters": {}
        }
      },
      "output_encoding": "json",
      "read_timeout": "0s",
      "write_timeout": "0s",
      "idle_timeout": "0s",
      "read_header_timeout": "0s",
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "name": "Consul",
      "sd_providers": {
        "providers": {
          "dns": false,
          "static": true,
          "custom": false
        },
        "hosts": [
          {
            "sd": "static",
            "host": "http://192.168.178.44:8000"
          }
        ]
      },
      "endpoints": [
        {
          "endpoint": "/posts",
          "method": "GET",
          "output_encoding": "json",
          "concurrent_calls": 1,
          "extra_config": {
            "github.com/devopsfaith/krakend-httpsecure": {
              "disable": true,
              "allowed_hosts": [],
              "ssl_proxy_headers": {}
            },
            "github.com/devopsfaith/krakend-ratelimit/juju/router": {
              "maxRate": 0,
              "clientMaxRate": 0
            }
          },
          "backend": [
            {
              "url_pattern": "/posts",
              "encoding": "json",
              "extra_config": {
                "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
                  "is_disabled": true,
                  "endpoint_params": {}
                }
              },
              "sd": "static",
              "host": [
                "http://192.168.178.44:8000"
              ],
              "disable_host_sanitize": false
            }
          ]
        }
      ],
      "disable_rest": false
    }

**Comment by alombarte** [comment]
Hi @krema ,

At startup time KrakenD will show errors and warnings related to misconfigurations with the middleware ( `extra_config` modules). But if the server doesn't die then you have KrakenD listening and ready to interact with your backend.

I don't have a way to test what this `192.168.178.44` is returning, but if the server is reachable from the KrakenD box I would bet that the response is giving you is not an object (e.g `{  "a": true }`) but an array (e.g: `[ { "a": true } ]`). 

If this is the case, just add `"is_collection": true`  inside the `backend` definition. The following example is the same configuration you passed me but adding the `is_collection` and using a fake api that returns a list.

```
{
  "version": 2,
  "timeout": "2s",
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "krakendesigner": {
      "endpoint_defaults": {
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      }
    },
    "github_com/devopsfaith/krakend-etcd": {
      "dial_timeout": "5s",
      "dial_keepalive": "30s",
      "header_timeout": "1s"
    },
    "github_com/devopsfaith/krakend-oauth2-clientcredentials": {
      "is_disabled": true,
      "endpoint_params": {}
    },
    "github_com/devopsfaith/krakend-httpsecure": {
      "disable": true,
      "allowed_hosts": [],
      "ssl_proxy_headers": {}
    },
    "github_com/devopsfaith/krakend-opencensus": {
      "sample_rate": 100,
      "reporting_period": 1,
      "exporters": {
        "logger": {}
      }
    }
  },
  "output_encoding": "json",
  "read_timeout": "0s",
  "write_timeout": "0s",
  "idle_timeout": "0s",
  "read_header_timeout": "0s",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "name": "Consul",
  "sd_providers": {
    "providers": {
      "dns": false,
      "static": true,
      "custom": false
    },
    "hosts": [
      {
        "sd": "static",
        "host": "http://192.168.178.44:8000"
      }
    ]
  },
  "endpoints": [
    {
      "endpoint": "/posts",
      "method": "GET",
      "output_encoding": "json",
      "concurrent_calls": 1,
      "extra_config": {
        "github.com/devopsfaith/krakend-httpsecure": {
          "disable": true,
          "allowed_hosts": [],
          "ssl_proxy_headers": {}
        },
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      },
      "backend": [
        {
          "url_pattern": "/posts",
          "encoding": "json",
          "extra_config": {
            "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
              "is_disabled": true,
              "endpoint_params": {}
            }
          },
          "sd": "static",
          "is_collection": true,
          "host": [
            "https://jsonplaceholder.typicode.com"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ],
  "disable_rest": false
}
```
I also added an exporter to `opencensus` so the module does something. But without it would have worked anyway.

Let me know if this was the case.

**Comment by krema** [comment]
hi, the 500 error is gone with is_collection but the start up error message still there. I am closing this ticket for now. Thanks

**Comment by alombarte** [comment]
Nice! Yes, we should add more info in the start up errors. Note taken!

A couple of additional comments now that I see you are using a collection.
1) Remember operations like whitelist or blacklist are not available in collections, only in objects
2) By default all collections are named `collection`. You might want to change this with `mapping`:
```
"is_collection": true,
          "mapping": {
            "collection": "some-other-name"
          },
```
Cheers

**Comment by kpacha** [comment]
regarding the error message, I think this is the message you are seeing: https://github.com/letgoapp/krakend-influx/blob/master/config.go#L75

I'll send a PR with an improved message.
