### ISSUE TITLE
configure DNS Server

### ISSUE THREAD

**Issue by amarktl** [devopsfaith/krakend-ce#234]
I would like to use consul as service discovery and lookup the services.

* Is there a possibility to configure the DNS Server to be used without modifying the OS DNS resolving.
* can i perform a dynamic resolving eg. like i have parameters in the URL or a path and map this to a dns name. 
 -> call: https://localhost:8080/orders/create
 -> configure dns name like : **_{service}_.service.consul**
-> this would than dynamically be mapped to **_orders_.service.consul**

BR
Alex

**Comment by kpacha** [comment]
- no, it is not because the DNS resolver relies on the OS one
- no, you can not because DNS resolution is independent from the request processing and because different services should be using different pipes fitting just the individual requirements (there is no 'one size fits all')

**Comment by amarktl** [comment]
Thx @kpacha for the fast answer. What would be the best way to route calls to different downstream services based on eg URL parameters or headers. I have the requirement to support such a dynamic routing because we setup new services dynamically which are "the same service" but for a different parameter set aka location. 
Do i really need to map all these as endpoints in the Gateway ?

**Comment by kpacha** [comment]
what you are describing sounds more like a reverse proxy than an API Gateway. If you want to really use an API Gateway, you should define an explicit mapping and expose it as your interface contract.

you can read more about the reasoning here: https://www.krakend.io/blog/what-is-an-api-gateway/

**Comment by amarktl** [comment]
Thx @kpacha  for your answer. :) So if i understand this correctly it would be a better option to use the API Gateway as an edge service and point the endpoints to an reverse proxy to handle the dynamics here.

**Comment by amarktl** [comment]
Thx for the hints and tips - things are starting to get clearer. 
@kpacha , @alombarte  i really like krakend and the way you treat the community. 
BR,
Alex
