### ISSUE TITLE
Websockets are must. Can't even think of building application without websockets.

### ISSUE THREAD

**Issue by Dhua-v** [devopsfaith/krakend-ce#237]
See you said,
" due the customizations it requires " it is not open-sourced. Please atleast give a very basic feature so that atleast I can start

I hope you understand. My application's core business runs on websockets and I came here with hope.

I am not a golang developer, otherwise I would have had given a PR for it. 
Thanks. Thousands of organizations are beniffiting from your work. 
Thanks again.

**Comment by alombarte** [comment]
Duplicated with #84
