### ISSUE TITLE
KrakenD endpoints validating 

### ISSUE THREAD

**Issue by soulless-viewer** [devopsfaith/krakend-ce#239]
### What I want:
When accepting a request for a specific endpoint, the service must take information from this request and make a new one in order to check (validate) the received request. After successful verification, the initial request continues.

Example:
~~~
[1]Client - - - > [2]<krakend> / api/service/project1/secret-info - - - > [3]<server>/project1/secret-info
~~~~

**1.**    Send JWT in auth header (with userID)
**2.1.** Get userID from JWT & projectID from URL
**2.2.** Send UID & GID to <krakend>/api/check-users-project
**2.3.** Check response (if access denied - abort, if access allowed - continue)
**3.**    Accepts a normal request

-------------------
### What I did:
**1.** Tried using a **_Sequential Proxy_**, but it's not exactly what I need. This scheme cannot terminate requests if verification fails.
**2.** Tried to use a **_Checking requests and responses with CEL_** in the request chains. The check works, but it still fails to terminate requests.
**3.** Trying to use **_Lua scripts_**. Everything was fine, but I ran into the current problem.

-------------------
### Main question:

I want to use **_Lua scripts_** to send **https** requests using **"socket"** and **"luasec"**. This would solve my problem, but I don't see a way to use **.so** files for Lua inside Krakend.

**Simple config example:**
```
{
    "endpoint": "/api/secret",
    "method": "GET",
    "extra_config": {
        "github.com/devopsfaith/krakend-lua/request": {
            "sources": [
                "/etc/krakend/lua/validateRequest.lua",        <--- (1)
                "/etc/krakend/lua/socket.lua",                       <--- (2)
                "/etc/krakend/lua/https.lua",                          <--- (3)
                "/etc/krakend/lua/socket/core.so"                 <--- (4)
            ],
            "pre": "validateRequest(ctx.load())",
            "live": true,
            "allow_open_libs": true
        }
    },
    "backend": [
        {
            "extra_config": {
                "github.com/devopsfaith/krakend-cel": [
                    {
                        "check_expr": "'True' in req_headers['Krakend-Access']"
                    }
                ]
            },
            "host": [
                "http://<ip:port>"
            ],
            "url_pattern": "/secret",
            "encoding": "json"
        }
    ]
}
```

**_(1) validateRequest.lua:_**

```
local socket = require "socket"   <--- OK
...
```

**_(2) socket.lua:_**

```
local socket = require "https"   <--- OK
...
```

**_(3) https.lua:_**

```
local socket = require "socket/core"   <--- this is core.so and KrakenD can't load or find this module inside
...
```

**I will be grateful for advice on an alternative solution or how to fix the current algorithm. For everything in general. Thanks**

**Comment by kpacha** [comment]
duplicated with https://github.com/devopsfaith/krakend-lua/issues/10

also, you can go with a handler plugin: https://www.krakend.io/docs/extending/writing-plugins/#writing-and-injecting-plugins
