### ISSUE TITLE
Usage of Wildcard support in krakend (krakend-107: Unveil endpoint wildcard support #337)

### ISSUE THREAD

**Issue by ms4800** [devopsfaith/krakend-ce#241]
Hi, 

I got to know the willcard support was added in krakend. (krakend-107: Unveil endpoint wildcard support #337)
I am new to krakend and I needed some help in getting this work.
I could not locate any documentation to refer to for using wildcard. 

Could you please point me to a document describing how to use the wildcard functionality. 
Specifically, I want to able to accept encoded slashes ('/') in an endpoint in krakend.json. 

For example:
If I have to accept the following as an endpoint.
/path/*   say  /path/xyz%3A%2F%2Fabcd.mandy%2F02%2F1234a-3456b

Thanks & Regards

**Comment by alombarte** [comment]
Hello @ms4800 ,

Have a look at https://github.com/devopsfaith/krakend/pull/337 and noticed that it was never merged (and the why). Wildcard is not supported on Krakend-CE.

There are workarounds to have similar functionality, like having endpoints like `/path/{level1}/{level2}/`
