### ISSUE TITLE
Configuration in a micro service environment

### ISSUE THREAD

**Issue by tobiasb** [devopsfaith/krakend-ce#243]
**Describe what are you trying to do**
I'd like to use Krakend as the API gateway between our clients (website, mobile app, 3rd party integrations) and our various (micro)services. The services are mostly independent from each other it is accepted that clients call multiple services directly, we're not interested in sequential requests and response aggregation, mostly about encapsulating cross cutting concerns such as security, rate limiting, etc. 
I'd like the configuration of the services' endpoints within the API gateway to be as independent from each other as possible but I noticed that I have to define all hosts at the highest level in the config file so I'm wondering if I'm using Krakend wrong.

Is there a way to define multiple "services" with hosts and other configuration as well as endpoints __per service__ similar to Kong's concept of [services](https://docs.konghq.com/getting-started-guide/2.1.x/expose-services/) so owners of service A can maintain their configuration independent from owners of service B?

**Comment by radykal-com** [comment]
With https://www.krakend.io/docs/configuration/flexible-config/ you can define each services endpoints in a file and then include those files in the main config file

**Comment by alombarte** [comment]
Sorry for the late reply, I didn't see this issue until @radykal-com stepped in.

On the Enterprise version, you can forward all traffic to a specific endpoint to a service (we call it wildcards). Also, as Marc mentioned, on the open-source version you can have different owners for the configuration parts.
