### ISSUE TITLE
Using Array-Response for Sequential Proxy 

### ISSUE THREAD

**Issue by MasterChiefPaul** [devopsfaith/krakend-ce#246]
Hi community,

I think you really have a nice product.
I would like to use responses in an array from the first backend for querying the second backend using the sequential proxy feature.
I would love to be able to use it like "{resp0_a.*b1.0.c}" or "{resp0_a.0.b1.0.c}".
If I try I am getting an Error (see below). I managed to work around it by extracting single fields to the top level using flatmap. But this results in redundant coding. And I have to configure a Backend for each call.

**This is my configuration:**
```
{
	"version": 2,
	"extra_config": {},
	"timeout": "3000ms",
	"cache_ttl": "0s",
	"output_encoding": "json",
	"name": "Test Aggregation with Arrays",
	"endpoints": [
		{
			"endpoint": "/arrayStructStub",
			"method": "GET",
			"output_encoding": "json",
			"extra_config": {
				"github.com/devopsfaith/krakend/proxy": {
					"static": {
						"data": {
							"a": [
								{
									"b1": [
										{
											"c": 1,
											"d": "foo"
										},
										{
											"c": 2,
											"d": "bar"
										}
									],
									"b2": true
								},
								{
									"b1": [
										{
											"c": 3,
											"d": "vaz"
										}
									]
								}
							],
							"x": 1337
						},
						"strategy": "always"
					}
				}
			},
			"backend": [
				{
					"url_pattern": "/dummy",
					"encoding": "json",
					"sd": "static",
					"method": "GET",
					"extra_config": {},
					"disable_host_sanitize": false,
					"host": [
						"localhost:8080"
					]
				}
			]
		},
		{
			"endpoint": "/simpleStub/{foo}",
			"method": "GET",
			"output_encoding": "json",
			"extra_config": {
				"github.com/devopsfaith/krakend/proxy": {
					"static": {
						"data": {
							"simpleStubResponse": 1
						},
						"strategy": "incomplete"
					}
				}
			},
			"backend": [
				{
					"url_pattern": "/dummy",
					"encoding": "json",
					"sd": "static",
					"method": "GET",
					"extra_config": {},
					"host": [
						"localhost:8080"
					],
					"disable_host_sanitize": false
				}
			]
		},
		{
			"endpoint": "/aggregate",
			"method": "GET",
			"output_encoding": "json",
			"extra_config": {
				"github.com/devopsfaith/krakend/proxy": {
					"sequential": true
				}
			},
			"backend": [
				{
					"url_pattern": "/arrayStructStub",
					"encoding": "json",
					"sd": "static",
					"method": "GET",
					"extra_config": {},
					"host": [
						"localhost:8080"
					],
					"disable_host_sanitize": false
				},
				{
					"url_pattern": "/simpleStub/{resp0_a.0.b1.0.c}",
					"encoding": "json",
					"sd": "static",
					"method": "GET",
					"extra_config": {},
					"host": [
						"localhost:8080"
					],
					"disable_host_sanitize": false
				}
			]
		}
	]
}
```

**If I call localhost:8080/aggregate I get following output in the log:**
[GIN] 2020/08/28 - 08:49:12 | 404 |         2.1µs |      172.17.0.1 | GET      /dummy
[GIN] 2020/08/28 - 08:49:12 | 200 |     2.51299ms |      172.17.0.1 | GET      /arrayStructStub
Error #01: Invalid status code
[GIN] 2020/08/28 - 08:49:12 | 404 |         2.7µs |      172.17.0.1 | GET      /dummy
[GIN] 2020/08/28 - 08:49:12 | 200 |    2.357391ms |      172.17.0.1 | GET      /simpleStub/{{.Resp0_a.0.b1.0.c}}
Error #01: Invalid status code
[GIN] 2020/08/28 - 08:49:12 | 200 |     5.44058ms |      172.17.0.1 | GET      /aggregate

The descriptor is not properly resolved! (GET      /simpleStub/{{.Resp0_a.0.b1.0.c}})

**When I use "{resp0_x}" instead I get following output:**
[GIN] 2020/08/28 - 09:10:55 | 404 |         1.7µs |      172.17.0.1 | GET      /dummy
[GIN] 2020/08/28 - 09:10:55 | 200 |     2.90869ms |      172.17.0.1 | GET      /arrayStructStub
Error #01: Invalid status code
[GIN] 2020/08/28 - 09:10:55 | 404 |         2.3µs |      172.17.0.1 | GET      /dummy
[GIN] 2020/08/28 - 09:10:55 | 200 |    2.513391ms |      172.17.0.1 | GET      /simpleStub/1337
Error #01: Invalid status code
[GIN] 2020/08/28 - 09:10:55 | 200 |     8.74817ms |      172.17.0.1 | GET      /aggregate

Thanks for your help.

**Comment by kpacha** [comment]
v1.2.0 includes the ability to turn array parameters as a comma separated list, with no withe spaces

thanks for the suggestion!
