### ISSUE TITLE
Krakend lambda configurations

### ISSUE THREAD

**Issue by dkgerra** [devopsfaith/krakend-ce#248]
Configured Lambda and getting 200 response in status in krakend terminal, but no response in output 

Please find the ss attached response from lambda krakend

![image (2)](https://user-images.githubusercontent.com/72087272/94570229-41f22f80-028c-11eb-89d6-f8cddd39b381.png)
![image (3)](https://user-images.githubusercontent.com/72087272/94570328-60582b00-028c-11eb-8f61-f6f01671c2bb.png)

```
{
      "endpoint": "/lambda/{lambda}",
      "output_encoding": "json",
      "backend": [
        {
          "extra_config": {
            "github.com/devopsfaith/krakend-lambda": {
              "function_param_name": "Lambda",
              "region": "ap-south-1",
              "max_retries": 1
            }
          }
        }
      ]
    }
```
Please help asap..

**Comment by kpacha** [comment]
can you provide the complete configuration of the endpoint and the result returned by your lambda function when called trough the console?
