### ISSUE TITLE
Krakend cannot load Lua library

### ISSUE THREAD

**Issue by ramadhia** [devopsfaith/krakend-ce#251]
**Describe the bug**
I need a solution that uses a bit of scripting, I simply need to use a Lua library like **lua-http** when I need to parse a cookie to convert to a query string or header. I installed and checked all dependencies on the docker container. I tried checking with the command `$ lua -l lpeg` and got a positive response. 
Also, I have experimented with  `$ luarocks show lpeg` and it is clearly installed. But when I try to hit the endpoint and try to see the logs, I get the response `Error # 01: Line 6: module leg not found` with http status 500

**Your configuration file**
```
{
    "endpoint": "/services",
    "method": "GET",
    "headers_to_pass": [
        "*"
    ],
    "extra_config": {
        "github.com/devopsfaith/krakend-lua/proxy": {
            "sources": [
                "/usr/share/lua/5.1/cookie.lua"
            ],
            "pre": "require('cookie').to_header()",
            "live": true,
            "allow_open_libs": true
        }
    },
    "output_encoding": "json",
    "concurrent_calls": 1,
    "backend": [
        {
            "url_pattern": "/",
            "method": "GET",
            "host": [
                "http://services.dns/"
            ]
        }
    ]
}
```
**Commands used**
```
$ docker run --rm -it  -p 8000:8000/tcp -p 8001:8001/tcp api-krakend:envoy
```

**Expected behavior**
When i hit the endpoint, http status must be **200** not **500**, and i can use lua-http library for parse cookie

**Logs**
```
[GIN] 2020/10/09 - 00:33:48 | 500 |   14.515927ms |       127.0.0.1 | GET      /service
Error #01: Line 6: module lpeg not found
```

```
$ luarocks show lpeg

LPeg 1.0.2-1 - Parsing Expression Grammars For Lua

LPeg is a new pattern-matching library for Lua, based on Parsing Expression
Grammars (PEGs). The nice thing about PEGs is that it has a formal basis
(instead of being an ad-hoc set of features), allows an efficient and simple
implementation, and does most things we expect from a pattern-matching library
(and more, as we can define entire grammars).

License:        MIT/X11
Homepage:       http://www.inf.puc-rio.br/~roberto/lpeg.html
Installed in:   /usr/local

Modules:
        lpeg (/usr/local/lib/lua/5.1/lpeg.so)
        re (/usr/local/share/lua/5.1/re.lua)

Depends on:
        lua >= 5.1 (using 5.1-1)
```
_Note: this is the perspective from docker container_

**Additional context**

**Comment by kpacha** [comment]
the lua component is not using the system libs. instead, it has its own, native lua VM/interpreter. So no external, c-based libs can be included/loaded.

if the available helpers are not enough for your requirements, I'd go with client plugins (https://www.krakend.io/docs/extending/writing-plugins/)
