### ISSUE TITLE
loading plugins: invalid ELF header

### ISSUE THREAD

**Issue by samstride** [devopsfaith/krakend-ce#254]
**Describe what are you trying to do**

Hey Guys, great job maintaining the gateway. We have krakend running on k8s and it works well. We are working on a prototype to get the [grpc-gateway post](https://www.krakend.io/blog/krakend-grpc-gateway-plugin/) working on k8s as well.

This is what I briefly did:

- Deployed Krakend v1.2.0 to k8s
- Upgraded [code here](https://github.com/kpacha/krakend-grpc-gateway-post) to go 1.15. I have created [PR](https://github.com/kpacha/krakend-grpc-gateway-post/pull/2) if anyone wants to have a look
- I generated the plugin and made sure I added it to the Dockerfile

```
# KrakenD 1.2.0 linux/amd64
FROM devopsfaith/krakend@sha256:d896abc400b6b72d2675620e5bebca801ad18707b07882012020e4330b440c7f
COPY plugins/* /etc/krakend/plugins/
COPY krakend.json /etc/krakend/krakend.json
``` 

**Your configuration file**

```json
{
    "version": 2,
    "extra_config": {
        "github_com/devopsfaith/krakend-gologging": {
            "level": "WARNING",
            "prefix": "[KRAKEND]",
            "syslog": false,
            "stdout": true
        }
    },
    "timeout": "3000ms",
    "cache_ttl": "300s",
    "name": "krakend-k8s",
    "port": 8000,
    "plugin": {
        "pattern": ".so",
        "folder": "/etc/krakend/plugins/"
    },
    "endpoints": [
        {
            "endpoint": "/user/{name}/{latitude}/{longitude}",
            "backend": [
                {
                    "host": [ "http://ignore.this" ],
                    "url_pattern": "/v1/helloworld/hello/{name}",
                    "extra_config": {
                        "github.com/devopsfaith/krakend/transport/http/client/executor": {
                            "name": "grpc-post",
                            "endpoints": [ "localhost:50051", "localhost:50052" ]
                        }
                    }
                },
                {
                    "host": [ "http://ignore.this" ],
                    "url_pattern": "/v1/routeguide/features/{latitude}/{longitude}",
                    "group": "feature",
                    "extra_config": {
                        "github.com/devopsfaith/krakend/transport/http/client/executor": {
                            "name": "grpc-post",
                            "endpoints": [ "localhost:50051", "localhost:50052" ]
                        }
                    }
                }
            ]
        }
    ]
}
```
**Commands used**
How did you start the software?

Krakend is running on k8s

**Logs**

```sh
KRAKEND] 2020/10/16 - 01:59:28.388 ▶ ERROR unable to create the GELF writer: getting the extra config for the krakend-gelf module
[KRAKEND] 2020/10/16 - 01:59:28.388 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugins/grpc-gateway-post.so): plugin.Open("/etc/krakend/plugins/grpc-gateway-post.so"): /etc/krakend/plugins/grpc-gateway-post.so: invalid ELF header
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugins/grpc-gateway-post.so): plugin.Open("/etc/krakend/plugins/grpc-gateway-post.so"): /etc/krakend/plugins/grpc-gateway-post.so: invalid ELF header
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN influxdb: unable to load custom config
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN opencensus: no extra config defined for the opencensus module
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN building the etcd client: unable to create the etcd client: no config
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN bloomFilter: no config for the bloomfilter
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN no config present for the httpsecure module
Parsing configuration file: /etc/krakend/krakend.json
```

Any ideas what I got wrong, especially around this error and why is it printed twice?

```sh
[KRAKEND] 2020/10/16 - 01:59:28.388 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugins/grpc-gateway-post.so): plugin.Open("/etc/krakend/plugins/grpc-gateway-post.so"): /etc/krakend/plugins/grpc-gateway-post.so: invalid ELF header
[KRAKEND] 2020/10/16 - 01:59:28.389 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (/etc/krakend/plugins/grpc-gateway-post.so): plugin.Open("/etc/krakend/plugins/grpc-gateway-post.so"): /etc/krakend/plugins/grpc-gateway-post.so: invalid ELF header
```

**Comment by samstride** [comment]
Managed to get past the ELF header issue.

The core problem was that I was building the plugin on mac os and deploying to k8s running on linux.

Cross compiling the plugin for linux on mac was tricky and I ended up building the plugin on linux and the ELF header issue was resolved.

Now I am running into this error:

```sh
plugin was built with a different version of package github.com/golang/protobuf/proto
```

I looked at the [go.sum for 1.2.0](https://github.com/devopsfaith/krakend-ce/blob/v1.2.0/go.sum) and made sure I was using the same versions of the necessary dependencies but I still can't get past the plugin version error.

Anyways, closing this for now.

Hoping there will be an easier way to build plugins in the future and resolve dependencies easily without having to get an enterprise license.

It was a good learning experience and we will have to live the extra network hop for now.

**Comment by kpacha** [comment]
we have just released an online tool I think will help: https://plugin-tools.krakend.io/

**Comment by samstride** [comment]
@kpacha , thanks for the tool. I ran my go.sum file and I got a long list of variations.

This one caught my interest:

```sh
github.com/lib/pq: v1.1.1 was expected but we have v1.8.0
```
We are using the latest version of that library? Assuming all the other dependencies matched, will this specific difference actually cause an error?

With regards to the error I am getting:

```sh
plugin was built with a different version of package github.com/golang/protobuf/proto
```

I made sure my go.sum had the correct dependency version but during plugin build, the latest version seems to have been added to my go.sum file. How do I deal with that auto upgrade during plugin build? (I cleared go mod cache before build but that didn't seem to help)

Also, I am generating my files using protoc v3.13.0. Will this matter?

**Comment by kpacha** [comment]
> We are using the latest version of that library? Assuming all the other dependencies matched, will this specific difference actually cause an error?

yes, it will be an issue when loading the plugin. Versions must match. You can force the version with
```
go get github.com/lib/pq@v1.1.1
```

regarding the error you're getting: notice the package `github.com/golang/protobuf` must be `v1.3.4` (`github.com/golang/protobuf/proto` is a subpackage)

> Also, I am generating my files using protoc v3.13.0. Will this matter?

That's the same version we are using

**Comment by samstride** [comment]
@kpacha , thanks for feedback. Will close for now.
