### ISSUE TITLE
using rabbitmq backend on docker

### ISSUE THREAD

**Issue by iceberg99** [devopsfaith/krakend-ce#255]
hi,
i have the following setup:  virtualbox VM that runs docker which includes the following containers:
rqsrv that runs rabbitmq, 
appsrv that run my application & 
krakendsrv that runs krakend they are on the same network i configured it on the run docker command.

using the designer i have created a configuration file, but when i try to run the krakend container it exits with message: "panic: invalid host"
i have tried several variations to access the host all failed.
my application connects to the rabbitmq with simple amqp://rqsrv
Help !!!!

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "rmq",
  "endpoints": [
    {
      "endpoint": "/pubmsg",
      "method": "POST",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/",
          "encoding": "json",
          "sd": "static",
          "extra_config": {
            "github.com/devopsfaith/krakend-amqp/produce": {
              "exchange": "",
              "durable": true,
              "delete": false,
              "exclusive": false,
              "no_wait": true,
              "mandatory": true,
              "immediate": false,
              "name": "tasks"
            }
          },
          "method": "POST",
          "host": [
            "amqp://guest:guest@rqsrv"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}
}
```
**Commands used**
sudo docker run -d --name krakendsrv     --network myNet -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend

**Logs**
sudo docker run -it -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend check --config krakend.json
Parsing configuration file: krakend.json
panic: invalid host

goroutine 1 [running]:
github.com/devopsfaith/krakend/config.URI.CleanHost(0x1, 0xc000041480, 0x18, 0xc0007742d0, 0xc000541ba0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/config/uri.go:42 +0x145
github.com/devopsfaith/krakend/config.URI.CleanHosts(0x1, 0xc00055f250, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/config/uri.go:33 +0x97
github.com/devopsfaith/krakend/config.(*ServiceConfig).initBackendDefaults(0xc0003367e0, 0x0, 0x0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/config/config.go:419 +0x1ba
github.com/devopsfaith/krakend/config.(*ServiceConfig).initEndpoints(0xc0003367e0, 0x32ff4a8, 0xc000774150)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/config/config.go:362 +0x345
github.com/devopsfaith/krakend/config.(*ServiceConfig).Init(0xc0003367e0, 0x2319520, 0xc0003367e0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/config/config.go:309 +0xbf
github.com/devopsfaith/krakend-viper.Parser.Parse(0xc00053a400, 0x7ffdb29b3f64, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/devopsfaith/krakend-viper@v0.0.0-20200605164302-854fa4ff4a66/parser.go:34 +0x157
github.com/devopsfaith/krakend-cobra.checkFunc(0x329dda0, 0xc000540de0, 0x0, 0x2)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v0.0.0-20200317174411-3518505e8cd2/check.go:24 +0xfe
github.com/spf13/cobra.(*Command).execute(0x329dda0, 0xc000540d80, 0x2, 0x2, 0x329dda0, 0xc000540d80)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
israel@dockerd:~/krakend$ sudo docker ps -a --format "table {{.ID}}    {{.Names}}\t{{.Networks}}\t{{.Status}}}"
israel@dockerd:~/krakend$ sudo docker ps -a --format "table {{.ID}}    {{.Names}}\t{{.Networks}}\t{{.Status}}}"

**Comment by kpacha** [comment]
try disabling the host sanitization (as in the example from the documentation: https://www.krakend.io/docs/backends/amqp/#example-1), since you aren't using http(s)
```
"disable_host_sanitize": true
```

**Comment by iceberg99** [comment]
Daniel hi,
10x 4 your answer.
it didnt work.

I.S.

‫בתאריך יום ג׳, 20 באוק׳ 2020 ב-19:34 מאת ‪Daniel López‬‏ <‪
notifications@github.com‬‏>:‬
