### ISSUE TITLE
Configurable option to use CertificateThumbprintSHA1 instead of KeyID for JWK cache construction

### ISSUE THREAD

**Issue by spencerhuang** [devopsfaith/krakend-ce#257]
**Is your feature request related to a problem? Please describe.**
An OAuth 2 authentication server has decided to implement the issuing of access token (JWT) and the issuing of JWK by using the same value in the kid field for both structure. 

`
jwt
"wbaxrV5e7SwP979FZhipGL4grrzz6Huprgh8GhmYLXw",
  "x5t": "h_qy14b0XfJGElJAqW2jjoEpzUc",
  "kid": "KEY",
  "alg": "RS256"...
}

jwk
 {
            "kty": "RSA",
            "x5t#S256": "bD2Ba4uIs0lLNyZAg_4Fbs2PgjqsF3p9AA21_Xkye34",
            "e": "AQAB",
            "x5t": "-1VGrqVBZ-Cc2k21fMx5n9qv-xI",
            "kid": "KEY",
            "x5c": ...
`

My understanding of Krakend is as the following:
the jwk spec library (structure) https://godoc.org/gopkg.in/square/go-jose.v2#JSONWebKey
auth0 creating jwk cache https://github.com/auth0-community/auth0-go/blob/master/key_cacher.go#L67
krakend-jose utilizing jwk cache https://github.com/devopsfaith/krakend-jose/blob/master/jwk.go#L43

To resolve this issue, I would have to fork the auth0-go library, modify the jwk cache construction, change how Krakend-jose uses that go package, and then maintain my own implementation.

**Describe the solution you'd like**
It appears that krakend-jose is using the ADD and the GET of aut0-go library, be great if it provides an option to use x5t as the key of jwk cache and we can set it as part of extra_config.

**Describe alternatives you've considered**
Change how that specific auth server provides token, but that's proprietary, not open source.

**Additional context**

**Comment by kpacha** [comment]
duplicates https://github.com/devopsfaith/krakend-jose/issues/43
