### ISSUE TITLE
Add extra configuration option to prefer IPV4

### ISSUE THREAD

**Issue by shireefadel** [devopsfaith/krakend-ce#259]
**Is your feature request related to a problem? Please describe.**
 ubuntu 18 forces the krakend process to listen on TCP6

**Describe the solution you'd like**
Add extra configuration option to prefer IPV4

**Comment by kpacha** [comment]
can you elaborate on the reasoning? what's the problem with using one over the other?

also, is not possible to disable ip6 on your server?

**Comment by shireefadel** [comment]
Yes, I can disable ipv6, but it's better to add this feature per process not for the server itself.

**Comment by alombarte** [comment]
Thank you for opening the issue @shireefadel . Unfortunatelly, we won't be investing time in this change.
