### ISSUE TITLE
Dockerfile issue 

### ISSUE THREAD

**Issue by arunsilu** [devopsfaith/krakend-ce#26]
when i build  a docker image ,i got  a issue

**Comment by kpacha** [comment]
hi, @arunsilu 

can you give us more details regarding the issue you are facing?

Cheers!

**Comment by arunsilu** [comment]
PFB DETAILS

FROM alpine:3.7

LABEL maintainer="dortiz@devops.faith"

RUN apk add --no-cache ca-certificates
ADD krakend-alpine /usr/bin/krakend

VOLUME [ "/etc/krakend" ]

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8000 8090


error
Step 1/8 : FROM alpine:3.7
 ---> 791c3e2ebfcb
Step 2/8 : LABEL maintainer="dortiz@devops.faith"
 ---> Using cache
 ---> c2e1fa20dc39
Step 3/8 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> 0d4d7e2f9c0d
Step 4/8 : ADD krakend-alpine /usr/bin/krakend
ADD failed: stat /var/lib/docker/tmp/docker-builder387431314/krakend-alpine: no such file or directory

HOW TO RESOLVE THAT ISSUE

**Comment by kpacha** [comment]
are you using the makefile?

In order to build the docker image you must execute `make docker_build_alpine krakend_docker`

Cheers!

**Comment by arunsilu** [comment]
PFB DETAILS
WHEN I RUN,  docker run -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend run --config /etc/krakend/krakend.json

OUTPUT :

[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   count:               0
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   min:                 0
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   max:                 0
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   mean:                0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   stddev:              0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   median:              0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   75%:                 0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   95%:                 0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   99%:                 0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   99.9%:               0.00
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG gauge krakend.service.runtime.NumThread
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   value:               9
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG gauge krakend.service.runtime.MemStats.HeapReleased
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   value:         1040384
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG gauge krakend.service.runtime.MemStats.HeapSys
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   value:         5865472
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG gauge krakend.service.runtime.MemStats.PauseTotalNs
[KRAKEND] 2018/07/25 - 12:43:33.121 ▶ DEBUG   value:          108146

HOW TO SAW MY  BROWSER THAT OUTPUT?

**Comment by kpacha** [comment]
hi,

that depends on your configuration.

the defined endpoints should be exposed at the port defined also in the config (maybe it's not the 8080 you're exposing from the container)

**Comment by arunsilu** [comment]
Thanks
