### ISSUE TITLE
Docker with Flexible configuration

### ISSUE THREAD

**Issue by caiaffa** [devopsfaith/krakend-ce#261]
`FROM devopsfaith/krakend:1.2.0

USER root

COPY . .

ARG ENVIRONMENT

RUN FC_ENABLE=1 FC_SETTINGS="config/${ENVIRONMENT}/settings" FC_OUT=out.json krakend check -d -c "config/krakend.json"

COPY out.json /etc/krakend/krakend.json`

but this not working

**Comment by taik0** [comment]
The `COPY out.json...` should be `RUN mv out.json /etc/krakend/krakend.json`  but it's much better to create a multistage build https://docs.docker.com/develop/develop-images/multistage-build/
