### ISSUE TITLE
Krakend did not load the plugin 

### ISSUE THREAD

**Issue by juaihua** [devopsfaith/krakend-ce#265]
hi guys,

   I  write a krakend plugin,  and it works well with the krakend downloaded from 

https://repo.krakend.io/bin/krakend_1.2.0_amd64.tar.gz.  Then i compile and build

krakend (krakend-ce v1.2.0)myself and run it to load the plugin,  

then i got a message 

   Error while trying to load plugin ./krakend-plugins.so.1.0.0-SNAPSHOT, plugin.Open("./krakend-plugins.so.1.0.0-SNAPSHOT"): 

plugin was built with a different version of package internal/unsafeheader (previous failure), so is there some bro 

who can give me some advise on how to resolve this problem , followed is the go.mod file of the plugin :

 module rcplatform.com/architecture/krakend-plugins

go 1.14

require (
	github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78 // indirect
	github.com/Microsoft/go-winio v0.4.14 // indirect
	github.com/Nvveen/Gotty v0.0.0-20120604004816-cd527374f1e5 // indirect
	github.com/cenkalti/backoff v2.2.1+incompatible // indirect
	github.com/containerd/continuity v0.0.0-20200928162600-f2cc35102c2a // indirect
	github.com/docker/go-connections v0.4.0 // indirect
	github.com/docker/go-units v0.4.0 // indirect
	github.com/go-sql-driver/mysql v1.5.0
	github.com/jmoiron/sqlx v1.2.0
	github.com/opencontainers/image-spec v1.0.1 // indirect
	github.com/opencontainers/runc v0.1.1 // indirect
	github.com/ory/dockertest v3.3.5+incompatible
	github.com/sirupsen/logrus v1.7.0 // indirect
	golang.org/x/net v0.0.0-20201010224723-4f7140c49acb
	golang.org/x/sys v0.0.0-20201013081832-0aaa2718063a // indirect
)

replace golang.org/x/sys => golang.org/x/sys v0.0.0-20200826173525-f9321e4c35a6

**Comment by alombarte** [comment]
Hi @juaihua, this might be useful: https://plugin-tools.krakend.io/validate

**Comment by juaihua** [comment]
> Hi @juaihua, this might be useful: https://plugin-tools.krakend.io/validate

thanks , my dear bro.  i think the problem is i choice a wrong version of golang ,  v1.15.2 is the correct version.  

best wishes    ^_^
