### ISSUE TITLE
Issues with custom plugin development

### ISSUE THREAD

**Issue by emilianozublena** [devopsfaith/krakend-ce#275]
I'm moving this discussion out of [here](https://github.com/devopsfaith/krakend-amqp/issues/7) to avoid out of topic things in the plugin repository @kpacha 

**Describe what are you trying to do**
We're trying to create a new custom plugin for KrakenD, aimed to create a transport layer between incoming http calls and AMQP through RPC calls (something the current supported plugin doesn't have)

**Your configuration file**
```
{
  "version": 2,
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "CoolUserService",
  "plugin": {
    "pattern": ".so",
    "folder": "./"
  },
  "extra_config": {
    "github_com/devopsfaith/krakend/transport/http/server/handler": {
      "name": "krakend-example",
      "attachuserid": "rsc"
   }
  },
  "endpoints": [
    {
      "endpoint": "api/get-user/{userId}",
      "headers_to_pass": [
        "X-Friend-User"
      ],
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "querystring_params": [],
      "backend": [
        {
          "method": "GET",
          "host": [ "https://api.github.com" ],
          "url_pattern": "/users/{userId}"
        }
      ]
    }
  ]
}
```
**Commands used**
```
krakend run -c kraken.json
```

**Logs**
```
2021/02/01 14:19:17  WARNING: loading plugins: plugin loader found 1 error(s): 
opening plugin 0 (./krakend-amqp-rpc.so): plugin.Open("./krakend-amqp-rpc"): plugin was built with a different version of package github.com/streadway/amqp
```

I have already checked the dependencies for KrakenD 1.2 in http://plugin-tools.krakend.io/ and i'm using the exact same version of Streadway/AMQP
The validation tool passed ok with my current .sum file: http://plugin-tools.krakend.io/validate/v1.2.0/1.15.2

go.mod file content
```
module github.com/emilianozublena/krakend-amqp-rpc

go 1.15

require (
	github.com/google/uuid v1.1.1
	github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271
)
```

go.sum file content
```
github.com/google/uuid v1.1.1 h1:Gkbcsh/GbpXz7lPftLA3P6TYMwjCLYm83jiFQZF/3gY=
github.com/google/uuid v1.1.1/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271 h1:WhxRHzgeVGETMlmVfqhRn8RIeeNoPr2Czh33I4Zdccw=
github.com/streadway/amqp v0.0.0-20190827072141-edfb9018d271/go.mod h1:AZpEONHx3DKn8O/DFsRAY58/XVQiIPMTMB1SddzLXVw=
```

**Comment by emilianozublena** [comment]
I've even tried building krakend from this very repository (just to be sure that both app and plugin were built with the exact same Golang version) but i keep hitting the same error, double and triple checked the streadway/amqp dependency and it's the same versions...

**Comment by emilianozublena** [comment]
Has anyone have time to check this one out? I have already tried all posible combinations i can think of :(

**Comment by kpacha** [comment]
duplicates https://github.com/devopsfaith/krakend-ce/issues/273

**Comment by alombarte** [comment]
Hi @emilianozublena , I guess the issue persists with 1.3. Isn't it?

**Comment by emilianozublena** [comment]
@alombarte we couldn't find our way through. Just went on a diff direction.

**Comment by emilianozublena** [comment]
Not sure the issue has been solved. Not being able to code a plugin that shares dependencies with Krakend's core plugins is a bit of a blocker...
Would've loved to see some degree of support with this :(

**Comment by alombarte** [comment]
I've closed the issue because you spoke in the past and I understood you chose another solution.

We are happy to support you with this and reopen the issue if you can continue to provide feedback on the issue. A lot of custom plugins are created for KrakenD and we haven't faced this situation (yet?). At this point, we cannot reproduce the problem without your help. If you'd like to continue I'll reopen it.

**Comment by kpacha** [comment]
> Not sure the issue has been solved. Not being able to code a plugin that shares dependencies with Krakend's core plugins is a bit of a blocker...
Would've loved to see some degree of support with this :(

that's not a restriction coming from KrakenD plugin package. It comes from the golang plugins package itself
