### ISSUE TITLE
Wildcard Problem (GIN).  Restful is not possible

### ISSUE THREAD

**Issue by fgparamio** [devopsfaith/krakend-ce#276]
I have the same problem indicated in this link. When RestFul apis with child resources are exposed there are always wildcard problems:

[https://stackoverflow.com/questions/61225833/krakend-api-gateway-panic-in-new-path-conflicts-with-existing-wildcard-in-exist](https://stackoverflow.com/questions/61225833/krakend-api-gateway-panic-in-new-path-conflicts-with-existing-wildcard-in-exist
)

This is the JSON file: 

[krakend.log](https://github.com/devopsfaith/krakend-ce/files/5920254/krakend.log)

It forces us to change the version of the end-points that give conflicts: v1, v2, v3, etc ... but that is a problem because it does not match the urls when working locally

**Comment by Juandavi1** [comment]
Hi, i've the same issue

**Comment by MrSmoke** [comment]
yeah we have the same issue too. We've had to just use un-restful routes for now. I know you can swap out gin for mux (except some things stop working) but there doesn't really seem to be any solid docs (and not knowing go makes it a bit harder).

See https://github.com/devopsfaith/krakend-ce/issues/136

Ideally there would be a `krakend-ce` mux docker image we could use which is supported
