### ISSUE TITLE
Container issue

### ISSUE THREAD

**Issue by arunsilu** [devopsfaith/krakend-ce#28]
PFB details
When i start the Container,i got bellow issue
please help me.

:~/krakend-ce# ls
backend_factory.go  Dockerfile   executor.go  Gopkg.toml          krakend         krakend.json  main.go   proxy_factory.go  router_engine.go  vendor
builder             encoding.go  Gopkg.lock   handler_factory.go  krakend-alpine  LICENSE       Makefile  README.md         sd.go

root@i~/krakend-ce# docker run -p 8080:8080 -v ./krakend.json:/etc/krakend/ devopsfaith/krakend run --config /etc/krakend/krakend.json
docker: Error response from daemon: create ./krakend.json: "./krakend.json" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by kpacha** [comment]
Hi, @arunsilu !

Can you check if this is not a docker-related issue? Please, try again with the full path for your volumes:

```
docker run -p 8080:8080 -v ${PWD}/krakend.json:/etc/krakend/krakend.json devopsfaith/krakend run --config /etc/krakend/krakend.json
```

Extra tip: once you have the docker setup fixed, If you are not sure if your config file is a correct, you can use a json linter and/or the [KrakenD checker](http://www.krakend.io/docs/commands/check/)

Cheers!

**Comment by arunsilu** [comment]
Thanks
When i  run the  above command, i got bellow output


[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   value:         2373336
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG gauge krakend.service.runtime.MemStats.Sys
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   value:         7217152
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG timer krakend.service.runtime.ReadMemStats
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   count:               6
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   min:             11415.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   max:             26426.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   mean:            17814.17ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   stddev:           4487.13ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   median:          17246.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   75%:             20513.75ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   95%:             26426.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   99%:             26426.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   99.9%:           26426.00ns
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   1-min rate:          0.01
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   5-min rate:          0.01
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   15-min rate:         0.00
[KRAKEND] 2018/07/31 - 12:07:44.336 ▶ DEBUG   mean rate:           0.02

**Comment by arunsilu** [comment]
please explain, what is the above output?
can i run on browser localhost:8080?

please help me.

Thanks
Arun

**Comment by alombarte** [comment]
Hi @arunsilu, the above output means the service is correctly running  and these numbers are just informational lines around several stats. Do not pass the flag `-d` when running if you prefer not seeing it.

You should also be able to browse localhost:8080 in your machine if you have chosen this port.
