### ISSUE TITLE
Please provide ARM and ARM64 binaries

### ISSUE THREAD

**Issue by egandro** [devopsfaith/krakend-ce#287]
Get a Pi4 :) and provide arm / arm64 binaries.

Also for Docker that would make sense.

**Comment by alombarte** [comment]
Thanks, @egandro

ARM is supported but it didn't have a lot of demand. I am leaving this issue open for a while to see if it gets some upvoting, otherwise, I will be closing it as every option we add is more maintenance.

**Comment by egandro** [comment]
@alombarte same here. It's getting momentum to at last evaluate arm and arm64. I am willing to help with the coding - but you guys need to buy maybe 2 PI4s for arm and arm64 or use qemu.

**Comment by fkrauthan** [comment]
I think now with the new apple systems using ARM CPUs as well as Amazon announcing some of there services to use it this should be looked at again.

**Comment by alombarte** [comment]
@fkrauthan You can install Krakend using brew on Mac.

`brew install krakend` and you'll get a Mac binary.

**Comment by fkrauthan** [comment]
Yeah but we are running everything (including kraken). So we build our own image and install kraken through the debian repository which only publishes amd64 binaries and no arch.

**Comment by rjdsilv** [comment]
We have requirements to have always the most up to date of a OS running under our Docker images and that's why we build the images ourselves. Regardless, looking in docker HUB I don't see an amr64 image for KrakenD. Would it be possible to start publishing those arm64 images?
