### ISSUE TITLE
Unshaped "return_error_details"

### ISSUE THREAD

**Issue by egandro** [devopsfaith/krakend-ce#288]
I just checked the source code of 

https://github.com/devopsfaith/krakend/blob/master/transport/http/client/status.go

DetailedHTTPStatusHandler will always shape the error code of the server. 

Is there any posibitliy to have this unshaped as is? I want the extra checking stuff of krakend but the error response should be untransformed.

```
"extra_config": {
    "github.com/devopsfaith/krakend/http": {
        "return_error_details": "backend_alias"
    }
}
```

**Comment by kpacha** [comment]
The alternative is to go with `no-op` pipes (https://www.krakend.io/docs/endpoints/no-op/), but then you'll lose the response manipulation and aggregation features
