### ISSUE TITLE
Aggregate multiple client requests through API Gateway.

### ISSUE THREAD

**Issue by sachinkanadia** [devopsfaith/krakend-ce#299]
Hi There,

I would like to implement an API Gateway that will aggregate multiple client calls into a single call exposed by an API Gateway as mentioned in the documentation [here](https://www.krakend.io/docs/overview/introduction/).

However I can't find in the documentation of how I would go abouts achieving this?

What is the best way if I want to achieve client request aggregation in front of microservices?

Please can someone advise.

Many Thanks!

**Comment by kpacha** [comment]
please, check the example at the backend section: https://www.krakend.io/docs/backends/overview/
