### ISSUE TITLE
Custom Middleware

### ISSUE THREAD

**Issue by jordelca** [devopsfaith/krakend-ce#300]
I have been trying to add a custom middleware to an endpoint, which evaluates some rules based on JWT and allow/deny the request. The middleware github.com/jordelca/krakend-opa/validator is not public at github yet, but it is located at $GOPATH/src/github.com/jordelca/krakend-opa/validator instead

```
{
    "version": 2,
    "name": "My lovely gateway",
    "port": 8080,
    "cache_ttl": "3600s",
    "timeout": "3s",
    "extra_config": {
      "github_com/devopsfaith/krakend-gologging": {
        "level":  "DEBUG",
        "prefix": "[KRAKEND]",
        "syslog": false,
        "stdout": true
      },
      "github_com/devopsfaith/krakend-metrics": {
        "collection_time": "60s",
        "proxy_disabled": false,
        "router_disabled": false,
        "backend_disabled": false,
        "endpoint_disabled": false,
        "listen_address": ":8090"
      },
      "github_com/devopsfaith/krakend-cors": {
        "allow_origins": [ "http://192.168.99.100:3000", "http://localhost:3000" ],
        "allow_methods": [ "POST", "GET" ],
        "allow_headers": [ "Origin", "Authorization", "Content-Type" ],
        "expose_headers": [ "Content-Length" ],
        "max_age": "12h"
      }
    },
    "endpoints": [
        {
            "endpoint": "/opa/{user}",
            "backend": [
                {
                    "host": [ "http://api.github.com" ],
                    "url_pattern": "/",
                    "whitelist": [
                        "authorizations_url",
                        "code_search_url"
                    ]
                }
            ],
            "extra_config": {
                "github.com/jordelca/krakend-opa/validator": {
                    "roles": ["admin","member"]
                }
            }
        }
    ]
}

```
**Commands used**
```
krakend run --config krakend.json
```

Even if I set a not existing middleware it is just ignored.
Is there any way I can use a local middleware? Any logs where I can see whats going on?

**Comment by alombarte** [comment]
Does it look like you are expecting that krakend goes to your GOPATH and compiles the middleware for you? If you want to add new middelwares you need to fork krakend-ce and inject it (e.g: see https://github.com/devopsfaith/krakend-ce/blob/master/executor.go)

If you don't want to recompile KrakenD have a look at plugins (which are sideloaded binaries)

The `extra_config` is a namespace used to identify your middleware. It can look like a path or a random string like `"extra_config": {"jorge": ...}`. The content has to match your middleware registration. See any of the multiple krakend-* repos and how are they loaded.

**Comment by jordelca** [comment]
You're right, my approach was wrong. Thanks for your answer.
