### ISSUE TITLE
KrakenD EE - Customization/Extension

### ISSUE THREAD

**Issue by alexduraipalam** [devopsfaith/krakend-ce#302]
If I decide to go with KrakenD EE, customization or extending the functionalities are allowed? Meaning, Is there a way to extend some functionalities specific to my client need ?

If so, what technology it supports for extention?

**Comment by alombarte** [comment]
Please reach to us at https://www.krakend.io/enterprise/ for commercial questions (Github is for open source)

Quick answer: Yes, you can customize enterprise.
