### ISSUE TITLE
Forwarding X.509 certificate information in HTTP-Headers (mTLS)

### ISSUE THREAD

**Issue by clouddistortion** [devopsfaith/krakend-ce#313]
Hi,

I am looking for a way on how to forward information e.g. CN, DN from a X.509 client certificate to the backend via e.g. HTTP-Headers.

Is this possible?
Regards

**Comment by kpacha** [comment]
yes, you can create a custom handler plugin (https://www.krakend.io/docs/extending/writing-plugins/#writing-and-injecting-plugins) and add the new headers using the info from https://golang.org/pkg/net/http/#Request.TLS

don't forget to add the headers to the list of `headers_to_pass` (https://www.krakend.io/docs/endpoints/parameter-forwarding/#headers-forwarding)
