### ISSUE TITLE
Have any plugins that can work around this routing limitation?

### ISSUE THREAD

**Issue by GoneGo1ng** [devopsfaith/krakend-ce#314]
[https://www.krakend.io/docs/endpoints/creating-endpoints/#endpoint-variables](https://www.krakend.io/docs/endpoints/creating-endpoints/#endpoint-variables)
`A request like /user/1/2 won’t be recognized by this endpoint. For such scenario you need to declare /user/{first}/{second}.`

I looked up the official documents and saw this rule. Have any plugins that can work around this routing limitation?

**Comment by alombarte** [comment]
The new router implemented on KrakenD 1.4.1 is much more flexible now.
