### ISSUE TITLE
Make KrakenD pass all user requests through a endpoint first

### ISSUE THREAD

**Issue by smahdis** [devopsfaith/krakend-ce#316]
We have a scenario in which we are using JWT (which has user_id enccoded inside it).

We want to pass all user requests through an endpoint in which it takes the JWT Token, extracts the user_id and then put it in the header (As I understood the krakend itself can't extract info from JWT)

Then we want to call the user requested endpoint.

For example I want to access this api:

/api/products/list

And I want to call this api first to extract the user_id from JWT Token and put user_id in the header:

/api/user/get_user_info

then KrakenD must go back to the requested user endpoint but with user_id in the header.

/api/products/list

So that the above endpoint knows which user is requesting.

How can I implement this?

**Comment by taik0** [comment]
Hi @smahdis 
Check the  section `Propagate JWT claims as request headers` of the [JWT documentation](https://www.krakend.io/docs/authorization/jwt-validation/)

**Comment by smahdis** [comment]
Thanks for the answer, I edited my first question.

I still need to route all user requests to an endpoint, change some header and then continue to the requested endpoint.

Is that possible?
