### ISSUE TITLE
Use sequential variable in extra_config

### ISSUE THREAD

**Issue by smahdis** [devopsfaith/krakend-ce#319]
Is there any way that I could use sequential variables in extra_config?

like this:

              "extra_config": {
                    "github.com/devopsfaith/krakend-martian": {
                        "header.Modifier": {
                          "scope": ["request", "response"],
                          "name": "Account_uuid",
                          "value": "{resp0_acnt_uuid}"
                        }
                    }
                }
     

It currentyl just prints "{resp0_acnt_uuid}" instead of the value of "acnt_id".

If I put it in url_pattern, it works. But I want to put it in header.

**Comment by smahdis** [comment]
Can anyone tell me how can I do this myself?

Which approach should i take?

(Lua, CEL, Router Plugin, Proxy Plugin or a custom midlleware?)

**Comment by kpacha** [comment]
no, you can't use url params extracted from the endpoint pattern in the extra config.

with lua, cel and a custom mw you could access these params using the defined structs and/or helpers
