### ISSUE TITLE
How do we handle in case of aggregation backend error?

### ISSUE THREAD

**Issue by iamgoangle** [devopsfaith/krakend-ce#32]
Hi Krakend Team,

Assume that I have 2 backend service (upstreams), I would like to know that what setting should be done in krakend.json to prevent the error whole request error?

**for example:**

I have following compoentns
- endpoint: /a 
   - backend /b and /c

I expected that if /c is failed, it should be return {} empty object, or krakend will be automatically handle error to {} empty object.

and finally response will be 

```
response : {
  b: { success: {} }
  c: {}
}
```

Do you have any suggestion?

**Comment by kpacha** [comment]
Hi, @iamgoangle 

KrakenD is a very pluggable framework, so there are ways to customize almost every part of it. The default implementation will let the clients know if the response is incomplete via HTTP headers.

You can inject your custom `proxy.ResponseCombiner` into the register and update your endpoint configurations properly. Your implementation could check if every response has the `IsComplete` property enabled and return an empty response if so.

An easy alternative could be the static response feature. You can define a struct to be returned every time a backend fails.

There is a reason why the feature you commented is not supported out of the box: we think returning an incomplete response when some backend fails is a desired feature for the api gateway pattern, giving tons of resilence to the stack by supporting graceful degradation. With the current implementation, the endpoint A will fail just if and only if both backends B and C fail.

`PeA = PeB x PeC`

if PeB = PeC = 10%, **PeA = 1%**

With the behaviour you are looking to achieve, your endpoint will work if and only if both backends work, increasing the error rate dramatically. 

`PeA = 1 - ((1-PeB) x (1-PeC))`

if PeB = PeC = 10%, **PeA = 19%**

![amplified error](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/media/image3.png)

Check out the existent literature on the net.

Cheers!

**Comment by kpacha** [comment]
🤔  After reading your question one more time, I think with the static partials and [groups](http://www.krakend.io/docs/features/response-manipulation/#grouping) you could get what you want.

**Comment by iamgoangle** [comment]
I'm trying to create custom proxy, my solution is that when http request to backend failed (container down, connect lost, not only 4xx, 5xx returned), my proxy will be return it as empty object and moving forward to next() backend.

Honestly, I have no idea where should I started to create custom proxy and inject to proxy_factory.go

**Comment by iamgoangle** [comment]
it does not work for me maybe I configured something wrong. I expected that if

```
endpoint: /
backend: /a /b
```

if /a failed maybe container not started, 4xx or 5xx returned it should not breaker all whole request.

```
response: {
  a: {},
  b: { ... success object ...}
}
```

**Comment by alombarte** [comment]
Hi @iamgoangle let us check because there might be a problem here. Will get to you ASAP

**Comment by iamgoangle** [comment]
Thanks @alombarte I would like to add some more feature about circuit breaker fallback. for example I can set default value i.e. empty response object. In case of circuit break in some backend die, before /proxy/merge.go do some action. 

Do you have any suggestion which part of project should I looking for?

**Comment by kpacha** [comment]
@iamgoangle it looks like you found a bug!

I'm updating the framework right now and the fix will be in the release planned for next week

thanks

**Comment by kpacha** [comment]
Fixed!

**Comment by iamgoangle** [comment]
Thanks!!!
