### ISSUE TITLE
Edit body with lua script got error 

### ISSUE THREAD

**Issue by Jozefiel** [devopsfaith/krakend-ce#320]
Hi
I am trying to parse some data from the header and add it to the body via Lua script, but I still got the error:

`Error #01: Post "http://127.0.0.1:8180/token": 
http: ContentLength=29 with Body length 38`

Here is my part of krakend config with lua settings:
```json
"github.com/devopsfaith/krakend-lua/router": {
    "sources": ["parser.lua"],
    "allow_open_libs": true,
    "live": true
 }
```

And here is (just body part) parser.lua script 
```lua

local r=ctx.load()
local body=r:body().."user=name"  -- add data do body
r:body(body)
```
Can I ask, how to correctly edit the body (add next data) via Lua or how to solve this problem?

Thanks a lot
Jozef

**Comment by taik0** [comment]
Since you are adding new data to the body, you need to update the Content-Length header to it's new size.
As you can see in the error, you are adding 9 chars and the length changes from 29 to 38 (+9).

**Comment by Jozefiel** [comment]
Thanks @taik0
