### ISSUE TITLE
What is an incomplete response?

### ISSUE THREAD

**Issue by yanjh007** [devopsfaith/krakend-ce#329]
**Describe what are you trying to do**
I think krakend is great! Easy to use and config, clear config file. So I setup krakend as a gateway for my api clusters. very simple, https request in, offload ssl, and distrbute the requests to backend api server. 

The only thing need to notice is use a path param and transfer to backend. As the config file discripted. 

The test is well. The request send, and the expect result responsed. seemingly.  Check the background running log, there are some unexpect information here, as below.

When I go for a performace test, there are somethings wrong. Some request not finished properly. I think its related with the wrong status of krakend.  

I check the website but I have not found useful information about my situation. Could somebody have the same isuue and any advice? 

Some information of my environment:

**Your configuration file**

{ "version": 2,
  "port": 8443,
  "tls": {
      "public_key": "/opt/kproxy/_w.ulsc.local.pem",
      "private_key": "/opt/kproxy/_w.ulsc.local.key"
  },
  "timeout": "3s",
  "output_encoding": "json",
  "extra_config": {
      "github_com/devopsfaith/krakend-gologging": {
          "level" : "WARNING",
          "prefix": "[KRAKEND]",
          "syslog": false,
          "stdout": true
      }
  },
  "endpoints": [{
     "endpoint": "/score/{b64param}",
     "extra_config": {
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
            "maxRate": 10000
        }
     },
     "backend": [{
        "url_pattern": "/score/{b64param}",
        "host": [
           "http://d205.ulsc.local:8011",
           "http://d205.ulsc.local:8012",
           "http://d205.ulsc.local:8013",
           "http://d205.ulsc.local:8014",
           "http://d207.ulsc.local:8011",
           "http://d207.ulsc.local:8012"
        ]
     },{
        "url_pattern": "/api",
        "host": [ "http://d205.ulsc.local:8011" ]
     }]
  }]
}

**Commands used**

krakend run -c api.json

**Logs**
If applicable, any logs you saw in the console and debugging information

[GIN] 2021/07/07 - 17:50:05 | 200 |    45.67798ms |   192.168.9.207 | GET      "/score/eyJoYXNoaWQiOiI0Y2YyMzM5ODQ1NGRlY2VkMWQ3OTkwNGZkYTJiY2JmY2E3Zjc2YTZkYzg3MjBmYjAifQ"
Error #01: Invalid status code
[GIN] 2021/07/07 - 17:50:05 | 200 |   50.039002ms |   192.168.9.207 | GET      "/score/eyJoYXNoaWQiOiIyMmViZmZmZWM3MGI3M2Q5OWY0N2QxZTE1ZTczNmUwN2JmMjAxYmMyNGUzNWQzODAifQ"
Error #01: Invalid status code

**Comment by kpacha** [comment]
@yanjh007 , endpoints with more than one backend require merging and, as stated at the documentation (https://www.krakend.io/docs/v1.3/endpoints/response-manipulation/#merging), the merger can return a partial (incomplete) response if anything nefarious happens (wrong status code, timeout, etc):

> The merge operation is implemented in a way where user experience and responsiveness goes first. It does its best effort to get all the required parts from the involved backends and returning the composed object as soon as possible.

in your example, it looks like one of the backends returned an error (invalid status code), so the merger returned a partial response. in order to know if that's the case, you can check the response header `X-Krakend-Completed`
