### ISSUE TITLE
plugin was built with a different version of package runtime/internal/sys

### ISSUE THREAD

**Issue by DmitryKaramin** [devopsfaith/krakend-ce#333]
**im' trying to use Krakend-ce plugin**
we need some additional login in Krakend-ce and choose to write our own plugin as it was allowed in documentation
https://www.krakend.io/docs/extending/writing-plugins/

**Your configuration file**
the section in `krakend.json` responsible for plugin

```
  "plugin": {
      "pattern":".so",
      "folder": "./plugins/"
  },
  "extra_config": {
      "github_com/devopsfaith/krakend/transport/http/server/handler": {
          "name": "krakend-example"
      }
  }
```

"hello, world" plugin was taken from 
https://pkg.go.dev/github.com/devopsfaith/krakend/transport/http/server/plugin

**Commands used**

```
go version go1.16.5 darwin/amd64
make build
go build -buildmode=plugin -o myplugin.so
./krakend run -c krakend.json


**Logs**

...
2021/07/11 16:51:46  WARNING: [loading plugins: plugin loader found 1 error(s):
opening plugin 0 (plugins/myplugin.so): plugin.Open("plugins/myplugin"): plugin was built with a different version of package runtime/internal/sys]
2021/07/11 16:51:46  INFO: [total http executor plugins loaded: 0]
2021/07/11 16:51:46  WARNING: [loading plugins: plugin loader found 1 error(s):
opening plugin 0 (plugins/myplugin.so): plugin.Open("plugins/myplugin.so"): plugin was built with a different version of package runtime/internal/sys (previous failure)]
...
2021/07/11 16:51:46  DEBUG: [http-server-handler: no plugins registered for the module]

**Question**

I build .so file with the same "golang" version... what should i do to make in work?

**Comment by kpacha** [comment]
you can check the go version required for every KrakenD release at https://plugin-tools.krakend.io/

**Comment by DmitryKaramin** [comment]
i've cloned version 1.4.1 of KrakenD from master. If it can be a reason of my fail?

**Comment by DmitryKaramin** [comment]
> you can check the go version required for every KrakenD release at https://plugin-tools.krakend.io/

rolled back to v 1.4.0 in pare with go version 1.16.4 i solved half of problem.

the problem stays when i try to debug app in GoLand
