### ISSUE TITLE
Modify Response Body

### ISSUE THREAD

**Issue by NeilduToit13** [devopsfaith/krakend-ce#337]
I would like to modify the response body returned by the backend.
I wan to insert/add a key value pair to the response body based on the status code of the response. The frontend people want to know whether their request was successful or not as a boolean and have this information in the response body rather than the response status code. 
I also want to transform snake_case keys into camelCase keys.

For example, given a response with 
status code: 401
body: {'detail_message': 'user is not logged in'}

I want to transform it to a response with
status code: 401
body: {'success': False, 'detailMessage': 'user is not logged in'}

The rule for success would be True for anything below 400 and False for anything above or equal.

Can I achieve this using Lua or another method?
Appreciate the help

**Comment by alombarte** [comment]
Hi @NeilduToit13, yes you should be able to make modifications of the body with lua scripts.
