### ISSUE TITLE
Redis for http caching

### ISSUE THREAD

**Issue by valodya-street** [devopsfaith/krakend-ce#341]
Hello. How can I implement Redis for http caching?

**Comment by alombarte** [comment]
You need to create a new component for that. There is no support for client caching.

**Comment by valodya-street** [comment]
Thank you. How I understand I can't resolve this problem if I create plugin. Need use this repository and expand it

**Comment by alombarte** [comment]
You don't need to fork the repository. You can write a plugin and make it work together with KrakenD. See: https://www.krakend.io/docs/extending/writing-plugins/
