### ISSUE TITLE
integrate with external OAuth2 server with authorization code flow

### ISSUE THREAD

**Issue by mango009** [devopsfaith/krakend-ce#348]
We have existing infrastructure using an external OAuth2 server. We would like to put KrakenD in front of our services as the API Gateway. We are using authorization code grant to generate access tokens. How do we integrate KrakenD? In the document there's only Client Credential grant type mentioned.

**Comment by alombarte** [comment]
Hi @mango009,

Your access tokens generated by the OAuth2 server have to be validated using https://www.krakend.io/docs/authorization/jwt-validation/. Client credential is only for the private communication between KrakenD and your backend severs, but not between end users and KrakenD. Use JWT validation as described in the link
