### ISSUE TITLE
Load Balancing for backend

### ISSUE THREAD

**Issue by prerit96** [devopsfaith/krakend-ce#349]
Suppose I have multiple instances running for a particular service and I need to load balance the backend requests from KrakenD, we need to define the hosts in the hosts array in the configuration file.

The question I have is how does KrakenD decide which host to connect to? In simple terms, what is the approach for Load Balancing?

**Comment by alombarte** [comment]
Hi @prerit96 , the connection to a pool of servers defined at `hosts` is done in a round-robin fashion.

A couple more of options you have is to use a single URL of an external LB (haproxy, ELB, etc) and let it keep the list of hosts updated for you. Another one is that you could use other of the supported service discovery systems (DNS, etcd, eureka...) as these SD components do update the host list too.

**Comment by prerit96** [comment]
Thanks for the info!
