### ISSUE TITLE
Unable to unzip the krakend gz file

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#352]
I was trying to unzip the krakend_1.4.1_amd64.tar.gz
I had downloaded this image on my location machine and then transferred to a VM
On the VM I tried unzipping it but it gave error message saying
gzip: krakend_1.4.1_amd64.tar.gz: invalid compressed data--format violated

Let me know what could be the problem
**Your configuration file**
      --NA--
**Commands used**
 gunzip krakend_1.4.1_amd64.tar.gz
```

**Logs**
gzip: krakend_1.4.1_amd64.tar.gz: invalid compressed data--format violated

**Comment by alombarte** [comment]
Hi, please use `tar xvfz krakend_1.4.1_amd64.tar.gz` instead

**Comment by nagaraj-trivedi** [comment]
Thanks
