### ISSUE TITLE
How to gzip Krakend responses?

### ISSUE THREAD

**Issue by EthanML** [devopsfaith/krakend-ce#353]
**Describe what are you trying to do**

It seems the only way to possibly get a gzipped response out of Krakend is when using `no-op` encoding on the desired endpoint and backend, with the backend itself having to do the gzipping.

- What about if we want Krakend to do the gzipping itself before returning its processed response to clients? Is it possible outside of using `no-op` encoding, which excludes other Kraken functionality? 
- If it's not possible by default is this something a custom plugin or middleware would be able to accomplish, or does one perhaps already exist? (I can't seem to find any central repository for shared plugins/middlewares either)
- If Krakend itself cannot do this, what is the expected usage pattern for compressing responses? Are Kraken users all deploying another server/CDN/etc. in front of Kraken for this express purpose?

Gzipping seems like a very important feature to be without, so I may be missing something entirely here - apologies if so.

**Your configuration file**

n/a

**Commands used**

n/a

----------------

**Comment by alombarte** [comment]
Hi @EthanML,

Your assumptions are correct. As of today, KrakenD does not gzip responses back to the client by itself. Current implementations of KrakenD-CE in need of gzip add it in the CDN level or any other piece in front of KrakenD. Can it be done? Yes. When? I frankly don't have an answer for it. It shouldn't be a plugin though, but be in its core.

**Comment by EthanML** [comment]
Thanks for confirming @alombarte , the swift response is much appreciated.
