### ISSUE TITLE
wanted to know the difference between an endpoint and the backend

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#354]
I am setting up the API gateway for the first time. I have come across the terminologies endpoint and backend from the document. Wanted to know the clear definition of these two.

Thanks and Regards

N.M.Trivedi

**Comment by alombarte** [comment]
Hi @nagaraj-trivedi 

An API allows two parts to communicate with each other. One side is the client, and the other is the server. When you don't use an apigateway the picture is clear:
```
Client <----> Server (Your API)
```
When you put an API gateway in the middle (KrakenD), then it becomes the server, but the data is still in your API(s). We call your original API servers the **backend(s)**. 
 
An **endpoint** is the HTTP resource you expose to your client, e.g.: `GET /user/{id}`. In our API gateway, unlike a reverse proxy, you have to take care of defining which endpoints exist for the client and how they map to your API servers. With a gateway the picture could be like this

```
Client <----> KrakenD <----> Your API
```
The endpoints are what you want to show to the public. And the backends where the actual data is. 

```
Client <--(endpoint)--> KrakenD <--(backend)--> Your APIs
```

A single user call to an endpoint can get data from many backends at once. For instance:

```
Client -- /user/john --> KrakenD -- |--  /user/john -->
                                    |--  /payments/john -->           Your API
                                    |--  /history/john -->
```

In the example above you would have a single endpoint `/user/john` that is connected to three different backends at the same time. The end user (client) would call one time to KrakenD, and krakend would call 3 times in parallel (by default) to your API to fetch the user, payments and history information.

it's a simple example but I am hoping that depicts the idea.

**Comment by nagaraj-trivedi** [comment]
Thank you for the clarification
