### ISSUE TITLE
where to find the client for krakend and how to integrate with APIs

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#355]
Hi all, I am setting up the krakend API Gateway for the first time.
Wanted to know from where to find the client and how to integrate APIs with krakend. From where we need to get this information.

**Comment by alombarte** [comment]
Hi,

There is no client-specific software for KrakenD, as it exposes a regular HTTP API. You can interact KrakenD with any HTTP client of your choice, from terminal using curl, from your own software with an HTTP call, or visually using an UI like [Postman](https://www.postman.com/product/api-client/).
