### ISSUE TITLE
where to find the client for krakend API Gateway

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#356]
Hi all, I am a new beginner with krakend API Gateway. Wanted to know where to find the client to send requests to the krakend API Gateway.

**Comment by EthanML** [comment]
Hi - this isn't something you would have a specific client for. Anything which can send an HTTP request will do. 
For example you might have `curl`  on your command line if running Linux or Mac. Or you could install GUI clients such as Postman or Paw for making these requests. (Or provided you only need to make a GET request, simply use your web browser.)

Just start your Krakend gateway locally and use one of the above to fire a request to whatever URL you have the gateway running on e.g. `localhost:8080/some-path` or similar.

**Comment by nagaraj-trivedi** [comment]
Thanks for your response.

Thanks
Nagaraj
