### ISSUE TITLE
Need some clarification on how and where to run endpoint, API Gateway, backend and the API

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#357]
Hi all, I want to know whether the endpoint, API Gateway, backend and API implementation can be done on the same machine

Also let me know how the the communication between API Gateway and backend and between backend and the actual API implementation takes place.

Thanks
Nagaraj

**Comment by alombarte** [comment]
Yes, it can be done on the same machine as long they do not share the same port.

The communication with the backend takes place via HTTP most of the times (unless you use queues or gRPC)
