### ISSUE TITLE
we can create endpoint for all api endpoint in micro service?

### ISSUE THREAD

**Issue by akaytatsu** [devopsfaith/krakend-ce#359]
we are starting with krakend as API Gateway. My question is: We have backend app that have 100 more endpoints. We need write a json with all 100+ endpoints? It's possible use something like wildcard?

**Comment by alombarte** [comment]
Hi @akaytatsu, yes you need to declare all the endpoints one way or the other. There are though different ways to ease this task.

1) You can use [Flexible Configuration](https://www.krakend.io/docs/configuration/flexible-config/#flexible-configuration-example) and declare a list of these 100 endpoints and write one loop (range) in a template.
2) Use the enterprise version which has a wildcard feature
