### ISSUE TITLE
procedure to create API and implement backend API with krakened

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#361]
Hi all, I am new to the krakend. I want to create an API, implement backend API implementation, endpoint and invoke this API through krakend.
Let me know the step by step procedure how to do it. Also let me know are there any links or documents that explain this.
Please provide me this information.

Thanks
Nagaraj Trivedi

**Comment by kpacha** [comment]
the [KrakenD playground](https://github.com/devopsfaith/krakend-playground/) is a good starting point as you can see how to expose your actual services and some other nice features.
