### ISSUE TITLE
unable to deploy the fake-api

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#362]
Hi all, I am referring the link to build and deploy the krakend and other necessary components(modules)
https://www.krakend.io/blog/krakend-on-kubernetes/
It has built the krakend and fake-api

But while deploying the backend api in k8s I got the error message saying
**Error from server (NotFound): deployments.apps "fake-api" not found**

But the fake-api image is created and is verified through command
 docker images
REPOSITORY                                TAG       IMAGE ID       CREATED         SIZE
k8s-krakend                               0.0.1     863de9256cae   4 minutes ago   27.2MB
**fake-api                                  latest    ae0b157047df   8 minutes ago   439MB**
k8s.gcr.io/kube-apiserver                 v1.22.2   e64579b7d886   7 days ago      128MB
k8s.gcr.io/kube-controller-manager        v1.22.2   5425bcbd23c5   7 days ago      122MB
k8s.gcr.io/kube-scheduler                 v1.22.2   b51ddc1014b0   7 days ago      52.7MB
k8s.gcr.io/kube-proxy                     v1.22.2   873127efbc8a   7 days ago      104MB
kubernetesui/dashboard                    v2.3.1    e1482a24335a   3 months ago    220MB
k8s.gcr.io/etcd                           3.5.0-0   004811815584   3 months ago    295MB
kubernetesui/metrics-scraper              v1.0.7    7801cfc6d5c0   3 months ago    34.4MB
k8s.gcr.io/coredns/coredns                v1.8.4    8d147537fb7d   3 months ago    47.6MB
gcr.io/k8s-minikube/storage-provisioner   v5        6e38f40d628d   5 months ago    31.5MB
k8s.gcr.io/pause                          3.5       ed210e3e4a5b   6 months ago    683kB
devopsfaith/krakend                       0.4.2     9f4fb9b4c696   3 years ago     27.2MB
jaxgeller/lwan                            latest    526243cbb205   6 years ago     439MB

**Commands used**
kubectl expose deployment fake-api --type=NodePort
```

**Logs**

**Error from server (NotFound): deployments.apps "fake-api" not found**

Let me know what could be the issue

**Comment by alombarte** [comment]
The `fake-api` has not been uploaded to your registry.

Please use kubernetes or docker help to get this done. is not related to krakend CE.

Thanks
