### ISSUE TITLE
Unable to see the response sent by the backend API

### ISSUE THREAD

**Issue by nagaraj-trivedi** [devopsfaith/krakend-ce#365]
Hi all, I have sent GET request to the end point and has reached the backend API whose definition is as below

func helloworld(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Welcome to the HelloWorld!\n")
    fmt.Println("Endpoint Hit: homePage")
}

It is verified at backend API that when a request is done from the client it logs a message
**Endpoint Hit: homePage**

The API writes the response as
**fmt.Fprintf(w, "Welcome to the HelloWorld!\n")**

But I am unable to see this response when I executed the below command
curl -X GET http://localhost:8080/new-endpoint

Let me know how to see the response sent by the backend API OR is the backend API code(statement) to send the response itself is wrong.

Please let me know about it.

**configuration file**
{
  "version": 2,
  "extra_config": {},
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "New Service",
  "endpoints": [
    {
      "endpoint": "/new-endpoint",
      "method": "GET",
      "output_encoding": "json",
      "extra_config": {},
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/helloworld",
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "extra_config": {},
          "host": [
            "172.30.156.18:10010"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}

**Commands used**
**docker-compose up**
**curl -X GET http://localhost:8080/new-endpoint**

**Logs**
Logs observed on the backend API console
**Endpoint Hit: homePage** (This is the message I have logged at the backend API (helloworld)

Thanks
Nagaraj

**Comment by kpacha** [comment]
"Welcome to the HelloWorld!\n" is not a valid JSON. check your backend encoder (maybe you could use `string`: https://www.krakend.io/docs/backends/supported-encodings/ )

**Comment by nagaraj-trivedi** [comment]
Hi, I have selected the encoding as json only in the backend configuration

In the log messages of krakend I have observed the following
krakend_ce_1       | [GIN] 2021/09/27 - 14:35:47 | 500 |     848.254µs |      172.18.0.1 | GET      "/new-endpoint"
krakend_ce_1       | Error #01: invalid character 'W' looking for beginning of value

Please let me know what is this error is all about.
Also is there a sample backend API code that returns the response in JSON format, which I can refer to code my backend API.

Thanks
Nagaraj

**Comment by nagaraj-trivedi** [comment]
Hi, it is got fixed. I used the encoding format as the string instead of json and got the response sent by the backend API.

Thanks for your valuable suggestion.

Thanks
Nagaraj
