### ISSUE TITLE
Pass headers in sequential proxy

### ISSUE THREAD

**Issue by slifer2015** [devopsfaith/krakend-ce#372]
How can I pass headers from previous response header as request header to the next end-point ?

**Comment by alombarte** [comment]
Hello,

All backend calls, sequential or not, will receive the headers from the endpoint request as declared in `headers_to_pass`. The sequential proxy is no different and it will never inspect or is able to use the headers of a previous backend call.

There's possibly some workaround for this functionality using Lua scripts, by injecting the first backend response headers inside the body, and then using the regular `{resp0_xxx}` field in the second backend.
