### ISSUE TITLE
X-Forwarded-For wrong value after upgrade to latest 1.4.1 version

### ISSUE THREAD

**Issue by samail** [devopsfaith/krakend-ce#373]
**Describe the bug**
Hi,
We used to use official 1.1.1-alpine image version of the service. A few weeks ago, we've decied to move to latest version to be able to enjoy new features as well as fixing vulnerabilities. 
Before upgrade, value of X-Forwarded-For was correct as it was the real client IP address thanks to our config of our ingress. We realized a few days ago that since the upgrade the value is not real client ip address but the one from our ingress. 
We double checked ingress config and it is ok, it is working, i can get the correct value in other services as well as if i get back to 1.1.1-alpine version, it is working as expected. But as soon as i upgrade the value is not ok anymore. 
We double checked with the debug endpoint and we confirm the issue between both versions.

**Commands used**
How did you start the software?
in DEBUG mode (-d) to get the debug endpoint working to check our issue, but it does the same with normal mode

**Expected behavior**
Should get the same value for X-Forwarded-For with all versions

**Logs**

with 1.4.1 version
```
test-app-kraken-dn7nh kraken [KRAKEND] 2021/10/20 - 16:34:22.366 ▶ DEBUG Headers: map[Accept-Encoding:[gzip] User-Agent:[KrakenD Version 1.4.1] X-B3-Sampled:[1] X-B3-Spanid:[a04fc8dad00f3176] X-B3-Traceid:[74c5b7f8e4c36f8e88f16b0d04bba6d3] X-Forwarded-For:[XX.XX.XX.XX] X-Forwarded-Host:[our-domain.fr]]
```
where XX.XX.XX.XX is the internal private IP 

with 1.1.1-alpine version
```
test-app-kraken-7ldkp kraken [KRAKEND] 2021/10/20 - 16:39:12.613 ▶ DEBUG Headers: map[Accept-Encoding:[gzip] User-Agent:[KrakenD Version 1.1.1] X-B3-Sampled:[1] X-B3-Spanid:[bb3ad65f1b2acf89] X-B3-Traceid:[db572f15ddd12a97c9719fe5f73c92ab] X-Forwarded-For:[XX.XX.XX.XX ]]
```
where XX.XX.XX.XX is the real client public IP

Have you experiemented the same issue ? Would love some feedback 
Thanks in advance

**Comment by radykal-com** [comment]
I was facing the same problem. It's a bug in gin affecting KrakenD 1.4.1. 

In our custom krakend-ce build with the just released gin v1.7.7, it seems fixed.

**Comment by terrasoff** [comment]
Experienced a similar issue as well. 
We have to downgrade kraken to 1.2.0.

**Comment by code-quantum** [comment]
would be nice to see build v1.4.2 :)
