### ISSUE TITLE
How to configure KrakenD to NOT follow redirect

### ISSUE THREAD

**Issue by mango009** [devopsfaith/krakend-ce#378]
Hi, How do I configure KrakenD such that it would not follow redirect 3xx from the endpoints? I tried to configure both the "output-encoding" for the endpoint with "no-op" and backend "encoding" with "no-op" as described in the doc (https://www.krakend.io/docs/endpoints/no-op/). But KrakenD still follows redirect.

Here's the configuration of my endpoint:
```
    {
      "endpoint": "/look/away",
      "output_encoding": "no-op",
      "backend": [
        {
          "encoding": "no-op",
          "url_pattern": "/look/away",
          "host": [
            "http://{{env "REST_API"}}"
          ]
        }
      ]
    },
```

**Comment by kpacha** [comment]
the internal http clients will always follow the redirect. if you want to pass it, you can use the redirect plugin available at the enterprise version (https://www.krakend.io/docs/enterprise/backends/client-redirect/)

cheers!
