### ISSUE TITLE
Error #01: context deadline exceeded

### ISSUE THREAD

**Issue by muhademan** [devopsfaith/krakend-ce#381]
I'd like to ask. why when i run krakend on ubuntu version 20 it happens Error #01: context deadline exceeded. 

The following configuration krakend.json:
```
{
      "endpoint": "/test",
      "backend": [
          {
            "host":["http://jsonplaceholder.typicode.com"],
            "url_pattern": "/posts/1"
          }
      ]
    }
```

Here's the krakend status on ubuntu:
```
curl -i http://localhost:8080/test
HTTP/1.1 500 Internal Server Error

Nov 10 11:00:18 krakend[2593670]: [GIN] 2021/11/10 - 11:00:18 | 500 | 30.000274571s |             ::1 | GET      "/test"
Nov 10 11:00:18 krakend[2593670]: Error #01: context deadline exceeded
```

I have also used timeout for the problem but still error 500 and Error #01: context deadline exceeded. 
```
{
  "version": 2,
  "name": "Krakend API Gateway",
  "port": 8080,
  "timeout": "2000ms",
  "endpoints": [
    {
      "endpoint": "/test",
      "timeout": "60s",
      "backend": [
          {
            "host":["http://jsonplaceholder.typicode.com"],
            "url_pattern": "/posts/1"
          }
      ]
    }
  ]
}
```

when i do `curl - i http://jsonplaceholder.typicode.com/posts/1` in ubuntu successfully exited the data

```
curl http://jsonplaceholder.typicode.com/posts/1
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

How can Error #01: context deadline exceeded be overcome? Please help me, because it has been days without finding a solution to the problem.

**Comment by taik0** [comment]
Hi @muhademan 
This is a timeout from the backend, looks like your KrakenD instance does not have internet access.

**Comment by yuwono95** [comment]
Any clue? I'm facing the same issue, Ubuntu 20.04 LTS. This issue does not exist on CentOS 8.
