### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by VogliaZero** [devopsfaith/krakend-ce#382]
Hi,

for some strange reasons my installation seems to ignore API Keys settings. I even copy/pasted sample configuration from API Keys documentation page, and I can still access all endpoints without even providing an Authorization header:

https://www.krakend.io/docs/enterprise/authentication/api-keys/#protecting-endpoints-by-api-key

Thank you in advance

**Comment by kpacha** [comment]
this feature is only available at the enterprise version
