### ISSUE TITLE
Question: What is order of execution for injection of Flexible Configuration?

### ISSUE THREAD

**Issue by candeemis** [devopsfaith/krakend-ce#387]
**Describe what are you trying to do**
I am trying to use flexible configuration and wondering about the order of execution for the injection of FC templates/json files. Suppose that I have a `urls.json` file that would contain different values (but same schema) depending upon the environment e.g following content:

```json
{
  "keycloak": "http://localhost:8081",
   "others": "other values"
}
```

and a `backend_extra_config.json` file that contains following content.

```json
{
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "{{ .urls.json }}/auth/realms/master/protocol/openid-connect/certs",
          "disable_jwk_security": true
        }
      }
```
And finally `krakand.json` file that uses the above mentioned `backend_extra_config.json` in all backend definitions.

My question is: In which order `krakand.json` will be populated with the given templates? All I want is that the URL of keycloak _defined in_ `urls.json` should be placed into `backend_extra_config.json` **before placing** the backend extra configs into the final `krakend.json` file. Is it a valid assumption, or I am missing something?

**Comment by alombarte** [comment]
Hi,

I recommend you to use the `.tmpl` extension when dealing with templates. What you want to do could be something like:

`krakend.tmpl`:

```
{
    "version": 2,
    "name": "Flexible configuration demonstration",
    "timeout": "3s",
    "endpoints": [
      {
         "endpoint": "/a",
         "extra_config": {
           {{ template "backend_extra_config.tmpl" . }}
         }

     
   ]
}

```
Notice there is a dot after calling the template, and that I have renamed it to tmpl

`backend_extra_config.tmpl`:

```
"github.com/devopsfaith/krakend-jose/validator": {
    "alg": "RS256",
    "jwk-url": "{{ .urls.keycloak }}/auth/realms/master/protocol/openid-connect/certs",
    "disable_jwk_security": true
}
```
Notice the `.keycloak` and not `.json`

The `urls.json` would be the same.

I have not tested this, I wrote it in this box. But you should get something running in no time
