### ISSUE TITLE
Q: How can I tell Krakend to respond with the same response it got from backend?

### ISSUE THREAD

**Issue by droslean** [devopsfaith/krakend-ce#388]
It seems that the issue https://github.com/devopsfaith/krakend-ce/issues/31 doesn't solve my problem.

**Comment by kpacha** [comment]
check this section of the documentation: https://www.krakend.io/docs/endpoints/no-op/

**Comment by droslean** [comment]
@kpacha Thanks! But still `krakend-cors` plugin manipulates the call and adds the headers. So now I am getting error that I have the cors headers multiple times.

**Comment by droslean** [comment]
opened: https://github.com/devopsfaith/krakend-ce/issues/392
