### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values, but only one is allowed.

### ISSUE THREAD

**Issue by droslean** [devopsfaith/krakend-ce#392]
Following https://www.krakend.io/docs/endpoints/no-op/ 

It seems that the `no-op` feature is not working as expected. The cors plugin still manipulates the call and adds the cross-origin headers. 

This looks like a bug, since now there is no way to tell `krakend` to do the `no-op` without manipulating the headers.

cc @kpacha

**Comment by taik0** [comment]
If KrakenD is managing CORS your backend should disable it's own CORS layer.

check this for a workaround if you can't disable CORS in yout backend https://github.com/devopsfaith/krakend-cors/issues/18
