### ISSUE TITLE
Route Step taking very long

### ISSUE THREAD

**Issue by ericlacher** [devopsfaith/krakend-ce#396]
Hi all,

### Our Setup

1. Krakend (v1.4.1) running in GCP GKE
2. Krakend reporting traces to OpenTelemetry Collector (also running in GKE)
3. GCP LoadBalancer in front of Krakend
4. Some backend services getting calls forwarded from krakend (also running in GKE)

### Observations

On the logs for load balancer, we see a lot of long lasting queries (600 seconds, until a timeout is hit). The interesting part is, as we're having tracing enabled, I can see that the first step ("Recv" span) takes very long, but as soon as the next step is hit ( "pipe" span) everything goes smoothly from there. Attached you see such a span: First 3 spans (Recv, Pipe, Backend) are krakend, 4th span (POST) is a span from a backend service.

![Screenshot 2021-12-24 at 11 16 07](https://user-images.githubusercontent.com/11710592/147344370-e38e5593-be04-4356-87d6-9dd1bec623ce.png)

One can clearly see the first span is taking ages (timeline in milliseconds), but as soon as pipe is hit, it runs through.

In the krakend logs for the given time, I do not see anything alerting, except these statements:

> "Error #01: CEL: request aborted by &{Env:0xc000427760 evalOpts:0 defaultVars:<nil> dispatcher:0xc000fe6c48 interpreter:0xc000fed3b0 interpretable:0xc000ff6120 attrFactory:0xc000ff6030}\n"

However, I believe this is expected, as we have an endpoint in place which has to fail and which gets regularly called by health checks (going into details below in section "Special" things we have).

### krakend.json

Our krakend.json is quite huge and contains company specifics, so I cannot post it fully. The attached config file only contains the failing endpoint (there are more failing, however this is a good example) and the root level configuration.

[2021-12-24-krakend.json.txt](https://github.com/devopsfaith/krakend-ce/files/7773993/2021-12-24-krakend.json.txt)

#### GCP Cloud Storage Plugin

I have to mention that we have running a plugin we wrote ourselves, but not enabled on this endpoint. I do not know whether this could cause any harm, but it certainly is something which makes our setup different from the average in the wild.

#### Health endpoints

See this snippet showing our health check setup:

[down-check.txt](https://github.com/devopsfaith/krakend-ce/files/7774169/down-check.txt)

- **/api/internal/health**: this endpoint aggregates health checks of individual services. If any fails, it will fail, if all succeed, it will succeed
- **/api/internal/health/down-check**: This endpoint negates the result from **/api/internal/health**:
  - in backend section, we check (using **CEL**) whether any of the services has status "DOWN" -> this endpoint will only succeed, if any service fails
  - if no service fails (**/api/internal/health** succeeds), this endpoint will return "DOWN" (using proxy and "strategy":"success")
- **/api/health**: This endpoint is the one being called to determine overall health status. It is doing another negation of the down-check endpoint.

I know this looks very complicated, but there were reasons for this setup. On the long term, we plan to have the aggregation being done outside of krakend either way. I am mentioning this setup, because I suspect the above mentioned failures (CEL: request aborted...) coming from down-check endpoint. Looking at the frequency, this looks about correct and thus these errors are expected.

### End

We're considering the krakend enterprise plan (also for improved plugin development experience), but at this point, we first need to get this issue fixed. I did not find any similar issues (neither on github, nor by just googling) other people are experiencing with krakend, so I am not sure whether it really is krakend which fails. Nevertheless, due diligence does no longer allow me to not go into all possible directions, as our prod system is impaired.

Any help highly appreciated, I am also happy to give more insights if needed.

Best regards,
Eric

**Comment by kpacha** [comment]
after checking the configuration you provided, my first suggestion would be to check the networking looking for interruptions and the load and latency of your JWK service (in order to see if it's lagging).

I'm making these suggestions because your JWT validation layer is not defining a cache for the JWK storage, so every incoming request to your gateway triggers another request to the JWK (ie: your health cycle requires 3 calls to the service). check the `cache` and `cache_duration` configuration params at https://www.krakend.io/docs/authorization/jwt-validation/#jwt-validation-settings

let me know if that solved your issues

**Comment by ericlacher** [comment]
Thanks a lot @kpacha, having the endpoints hitting JWK for each query does not make sense at all, no matter whether this is causing our problems. I therefore now have added the suggested caching options and will keep an eye on it the next days. I already can say that the traces/spans are looking way better now (correct nesting), and some low-profile calls got way faster.
Nevertheless, I am wondering whether no cache at all is a sane default, here.

**Comment by ericlacher** [comment]
Quick update on this, with @kpacha's suggestion, we no longer experience the issue with krakend. I will keep a close eye on the traces for a bit longer to be 100% sure, but for now I think this was resolved.
I do not know the reasoning for disabling the cache by default, but probably having it enabled with a sane TTL when not set would make sense.

Thanks again,
Eric
