### ISSUE TITLE
Custom service discovery

### ISSUE THREAD

**Issue by Verttigo28** [devopsfaith/krakend-ce#397]
**Describe what are you trying to do**
In the Krakend Designer we can provide a "custom service discovery" but i don't find any explaination about that.
Is it an URL that return a JSON Array with the hosts?

Thanks for your help,
Baptiste

**Comment by alombarte** [comment]
It should be removed from there because it implies that you have compiled KrakenD with your own service discovery implementation.

**Comment by Verttigo28** [comment]
Okay i see, thanks for the feedback
