### ISSUE TITLE
Allow setting multiple methods per endpoint at once

### ISSUE THREAD

**Issue by amrellafy** [devopsfaith/krakend-ce#398]
**Is your feature request related to a problem? Please describe.**
Creating an endpoint configuration per method is very verbose.

**Describe the solution you'd like**
Allow **method** configuration variable to accept array, for example:
`["GET", "POST", "PUT"]`

**Describe alternatives you've considered**
Using multiple configuration files with templates should work but again, very verbose

**Comment by alombarte** [comment]
Hi @amrellafy,
Thanks for your input. Verbosity can be solved with templating, snippets, and meta generators. There are many ways to overcome this "user" problem, but every combination of endpoint and method must be a different entry for the KrakenD internals.
