### ISSUE TITLE
Usage of "not production ready" krakend-martian in released version

### ISSUE THREAD

**Issue by bartoszgolek** [devopsfaith/krakend-ce#4]
HI,

I've just discovered that in released version of krakend-ce (0.4.0) is dependency of krakend-martian, which is marked as non production ready:
https://github.com/devopsfaith/krakend-ce/blob/67fbdd4ea9e820a0bae9b27aac06a1a70f6608c5/backend_factory.go#L30

https://github.com/devopsfaith/krakend-martian

I think that means one of two: Krakend-ce is not production ready, or krakend-martian is production ready

**Comment by alombarte** [comment]
Well spotted.
Let's fix the krakend-martian README as the comment was left there and it shouldn't.

thanks!

**Comment by alombarte** [comment]
Readme changed

**Comment by bartoszgolek** [comment]
Thanks
