### ISSUE TITLE
Abort further routing on given response from first backend

### ISSUE THREAD

**Issue by tosikszymon** [devopsfaith/krakend-ce#401]
Hi, I am trying to implement some custom logic based on given example:
1. Calling first backend which returns array of sales
2. When the array is empty I would like to not continue further routing (next requests depend on response from first backend)

How I could achieve such functionality in order to save up resources and short circuit response.

**Comment by alombarte** [comment]
Hi @tosikszymon ,

You might have a look at CEL: https://www.krakend.io/docs/endpoints/common-expression-language-cel/#example-check-if-the-backend-response-has-a-specific-field-or-abort

You can check the response of the backend and mark the backend as failed (if the condition evaluates to `false`), so the sequential won't trigger.
