### ISSUE TITLE
Custom Errors with body

### ISSUE THREAD

**Issue by estehurtado** [devopsfaith/krakend-ce#405]
I have an implementation is using lua scripts in the pre backend to perform some validations before call the backend, on certain cases I want to create a response with a http status 422 including body and stopping the pipe execution. How I can achieve that?

**Comment by kpacha** [comment]
with the latest stable release it is not possible to send an error description at the body. you can stop the execution and return a status code for the client and an error for the router to log.

here you'll find the documentation for the helper `custom_error`: https://www.krakend.io/docs/endpoints/lua/#custom_error

one of the new features we'll be adding at the v2.0 release is the ability to tell krakend to return these errors as the response body, so you'll be able to do what you described.
