### ISSUE TITLE
null size result instead expected image from GET query

### ISSUE THREAD

**Issue by vsinceac** [devopsfaith/krakend-ce#407]
I'm trying to retrieve an image (a map tile) generated by a GeoServer backend, via a KrakenD endpoint (GET). 
KrakenD is deployed on same docker swarm stack as the backend.

When I query directly the backend, generated image is correctly received by browser client.
When same query is sent to KrakenD endpoint, the result is 0KB, with status 200 and no error in traces.
I checked Geoserver, which generates well map image and sends it back to caller in both cases above.

I can reproduce same issue with external public backend (to avoid stuff related to my internal backend). 
Did I missed something in krakend.conf (see below)? 

This direct query to public backend returns 1 png image (14KB): _https://ahocevar.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-12523442.714243278%2C6261721.35712164_

When I query same backend via krakend endpoint, with same payload, I get nothing (with status 200): _http://30.30.30.23:12321/NeoAPI/wmsRemote?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-12523442.714243278%2C6261721.35712164_

Single trace in KrakenD is: _[GIN] 2022/02/01 - 12:49:26 | 200 |  122.906154ms |        10.0.0.2 | GET      "/NeoAPI/wmsRemote?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=topp%3Astates&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-13775786.985667605%2C5009377.085697312%2C-12523442.714243278%2C6261721.35712164"_

KrakenD conf (in docker-compose.yml, krakend is launched as command: run -d -c /etc/krakend/krakend.json):
```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [
        "*"
      ],
      "expose_headers": [],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "CONNECT",
        "OPTIONS"
      ],
      "allow_credentials": true
    },
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": true,
      "stdout": true,
      "format": "default"
    },
    "github_com/devopsfaith/krakend-logstash": {
      "enabled": true
    }
  },
  "plugin": {
    "pattern": ".so",
    "folder": "/opt/krakend/plugins/"
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "NeoAPI",
  "port": 12321,
  "endpoints": [
    {
      "endpoint": "/NeoAPI/wmsRemote",
      "method": "GET",
      "output_encoding": "no-op",
	  "headers_to_pass":[
		"*"
	  ],
      "extra_config": {},
      "backend": [
        {
          "url_pattern": "/geoserver/wms",
          "encoding": "no-op",
          "sd": "static",
          "method": "GET",
          "extra_config": {},
          "host": [
            "https://ahocevar.com/"
          ]
        }
      ],
      "concurrent_calls": 3,
      "querystring_params": [
        "SERVICE",
        "VERSION",
        "REQUEST",
        "FORMAT",
        "TRANSPARENT",
        "LAYERS",
        "TILED",
        "WIDTH",
        "HEIGHT",
        "CRS",
        "STYLES",
        "BBOX"
      ]
    }
  ],
  "disable_rest": true
}
```

**Comment by kpacha** [comment]
no-op endpoints returning chunked responses do not play nice with concurrency.

just remove the `"concurrent_calls": 3` line and you'll see the binary response as returned by the backend server.

**Comment by vsinceac** [comment]
Actually YES, it works fine now without that line! Many Thanks!
