### ISSUE TITLE
Sequential call based on a condition

### ISSUE THREAD

**Issue by inchara789** [devopsfaith/krakend-ce#413]
Hi I am new to krakend. How to check the response code of first api and if it is "0000" it should hit second api else it shouldn't execute sequential call.  Below mentioned is my config. 

  {
      "endpoint": "/user/login/fetchUser",
      "method": "POST",
      "headers_to_pass": [
        "*"
      ],
      "querystring_params": [
        "*"
      ],
      "extra_config": {
        "github.com/devopsfaith/krakend/proxy": {
          "sequential": true
        }
      },
      "backend": [
        {
          "host": [
            "http://172.19.12.39:7074"
          ],
          "url_pattern": "/auth/abc",
          "method": "GET",
          },
        {
          "host": [
            "http://172.19.12.39:7079"
          ],
          "url_pattern": "/login/fetchUser",
          "method": "POST"
        }
      ]
    }

**Comment by alombarte** [comment]
Hello Inchara,

the sequential proxy will look for the HTTP status code of the backend response and if it is a 20x code then it will continue. Otherwise the sequence is aborted. You cannot inspect the response body of your backend and apply logic according to it.
