### ISSUE TITLE
In sequential proxy new headers are not displayed

### ISSUE THREAD

**Issue by inchara789** [devopsfaith/krakend-ce#414]
Hello
I am adding a header in the controller of the first API of sequential proxy but it is not displayed by the krakend. if I hit that API separately it is being shown. I am not getting why. Thanks.

**Comment by alombarte** [comment]
KrakenD does not behave like a regular proxy and the default behavior is not to propagate the backend headers back to the client. Headers declared in the `headers_to_pass` are allowed in, and reach the backend, but none of the headers back are transferred out to the client.

If you want to see the backend headers in the client you need to use the encoding `no-op`. But take into account that no-op means literally no operation so no manipulation option is available (including the sequential proxy) and only one backend can be used.
