### ISSUE TITLE
Modify the request body in sequential call with dynamic value

### ISSUE THREAD

**Issue by divyasathya** [devopsfaith/krakend-ce#422]
I am implementing a sequential call which include two API.They are API1 and API2.API 1 is Get and API2 is post call . 
The initial request will route to API 1, After it is  successfully executed, The request will route to  API2.I want to set the request  body of API2  with the response  of API1..For that , i am doing following  configuration .

Here xyz is the  key which i am setting  in API1 response .

"[github.com/devopsfaith/krakend-martian](http://github.com/devopsfaith/krakend-martian)":
      {
          "body.Modifier": {
              "scope": ["request","response"],
              **"body": "{resp0_xyz}"** 
          }
      }
}

Can you please advise how  to achieve  this .

**Comment by alombarte** [comment]
Hi,

This flow is not supported as of krakend 1.4.1. You can use data from API1 to build the URL of API2 but you cannot pass the body content from one to the other.

**Comment by divyasathya** [comment]
Perfect ..Thank you
