### ISSUE TITLE
Endpoint calls multiple backend endpoints are not receiving the request body

### ISSUE THREAD

**Issue by krishna-kunderu** [devopsfaith/krakend-ce#430]
I am having an endpoint A that invokes B & C backend endpoints. The JSON request body that comes from A is only available for B, but not passing the same to C.  I imaging the request body or query params should be passed for all the backends. Please let me know  if I am doing something wrong

Below is sample krakend JSON. suppose I am passing json as {"one": 1, "two": 2}, the same is sent only to B backend, but not seeing the payload coming for the end point C.

{
        "endpoint": "/A",
        "method": "GET",
        "backend": [
          {
            "url_pattern": "/B",
            "encoding": "xml",
            "timeout": "3000ms",
            "method": "POST",
            "host": [
              "http://hostb.com"
            ]
          },
          {
            "url_pattern": "/C",
            "method": "POST",
            "timeout": "3000ms",
            "host": [
              "http://hostc.com"
            ]
          }
        ]
      }

**Comment by alombarte** [comment]
Hi @krishna-kunderu ,

KrakenD is limited by configuration to not use multiple unsafe methods in parallel. While you can have several backends using the GET method, you can only have one non-safe (PUT, POST, DELETE...) backends in total.

**Comment by krishna-kunderu** [comment]
Thanks for the response on this.


Based on your input do you think the request body  would be passed for both the backend methods if I have json as below. 

endpoint A takes a payload, then can B & C can see the request payload, if B is a  GET and C is a POST?


{
"endpoint": "/A",
"method": "POST",
"backend": [
{
"url_pattern": "/B",
"encoding": "xml",
"timeout": "3000ms",
"method": "GET",
"host": [
"http://hostb.com"
]
},
{
"url_pattern": "/C",
"method": "POST",
"timeout": "3000ms",
"host": [
"http://hostc.com"
]
}
]
}

**Comment by alombarte** [comment]
Something similar it's going to work. You will need to enable the sequential proxy to let KrakenD register and endpoint like this.
Try this config:
```
{
    "version": 2,
    "endpoints": [
        {
            "endpoint": "/A",
            "method": "POST",
            "backend": [
                {
                    "url_pattern": "/__debug/B",
                    "method": "GET",
                    "host": [
                        "http://localhost:8080"
                    ]
                },
                {
                    "url_pattern": "/__debug/C",
                    "method": "POST",
                    "host": [
                        "http://localhost:8080"
                    ]
                }
            ],
            "extra_config": {
                "github.com/devopsfaith/krakend/proxy": {
                    "sequential": true
                }
            }
        }
    ]
}
```
And start krakend with `krakend run -d -c krakend.json` (notice the `-d`).  After doing this in the logs you'll see how the BODY of the request reaches all backends:
```
curl --data '{"one": 1, "two": 2}' http://localhost:8080/A
```
Logs:
```
2022/03/01 18:40:53  DEBUG: [Method: GET]
2022/03/01 18:40:53  DEBUG: [URL: /__debug/B]
2022/03/01 18:40:53  DEBUG: [Query: map[]]
2022/03/01 18:40:53  DEBUG: [Params: [{param /B}]]
2022/03/01 18:40:53  DEBUG: [Headers: map[Accept-Encoding:[gzip] Content-Type:[application/x-www-form-urlencoded] User-Agent:[KrakenD Version 1.4.1] X-Forwarded-For:[127.0.0.1] X-Forwarded-Host:[localhost:8080]]]
2022/03/01 18:40:53  DEBUG: [Body: {"one": 1, "two": 2}]
[GIN] 2022/03/01 - 18:40:53 | 200 |     120.476µs |       127.0.0.1 | GET      "/__debug/B"
2022/03/01 18:40:53  DEBUG: [Method: POST]
2022/03/01 18:40:53  DEBUG: [URL: /__debug/C]
2022/03/01 18:40:53  DEBUG: [Query: map[]]
2022/03/01 18:40:53  DEBUG: [Params: [{param /C}]]
2022/03/01 18:40:53  DEBUG: [Headers: map[Accept-Encoding:[gzip] Content-Type:[application/x-www-form-urlencoded] User-Agent:[KrakenD Version 1.4.1] X-Forwarded-For:[127.0.0.1] X-Forwarded-Host:[localhost:8080]]]
2022/03/01 18:40:53  DEBUG: [Body: {"one": 1, "two": 2}]
[GIN] 2022/03/01 - 18:40:53 | 200 |      73.227µs |       127.0.0.1 | POST     "/__debug/C"
[GIN] 2022/03/01 - 18:40:53 | 200 |     730.178µs |       127.0.0.1 | POST     "/A"
```

**Comment by krishna-kunderu** [comment]
Thanks alot, for the same.
