### ISSUE TITLE
How to forbid access to certain endpoint for requests out of localhost?

### ISSUE THREAD

**Issue by Joseda8** [devopsfaith/krakend-ce#432]
I have two endpoints and I want one of them to be accessible by requests from the localhost only. The other one should receive requests from anywhere. In the [Security](https://www.krakend.io/docs/service-settings/security/#restrict-connections-by-host) section of the documentation I found the next configuration:

```
"extra_config": {
  "github_com/devopsfaith/krakend-httpsecure": {
    "allowed_hosts": [
      "host.known.com:443"
    ]
  }
}
```

But this is at the root level only. Also, this includes the port, I need to filter for the criteria: "Comes from the localhost?"

Is there a way in which I can meet this requirement?

**Comment by kpacha** [comment]
that configuration is not intended to do what you want. try with a CEL expression such as
```
'::1' in req_headers['X-Forwarded-For'] || '127.0.0.1' in req_headers['X-Forwarded-For']
```

more details here: https://www.krakend.io/docs/endpoints/common-expression-language-cel/
