### ISSUE TITLE
Endpoint switching

### ISSUE THREAD

**Issue by peturssonstefan-ikea** [devopsfaith/krakend-ce#442]
Hi! 

We are working on a scenario where we have two endpoints exposing the same data, endpoint A and endpoint B. 
Endpoint A is a graphql endpoint and endpoint B is a standard REST endpoint. We'd prefer to direct traffic against endpoint A, but should endpoint A be down for some reason, we'd want to direct traffic to endpoint B instead (but only in case of endpoint A being down). 

Is there a good way to go about this? I've looked at the circuit breaker, but that's not really what we need.  

As this is more of a "best practices / whats possible" kind of question, I'll leave out the krakend.json config, but please let me know if it helps having a look at it anyway.

**Comment by peturssonstefan-ikea** [comment]
Hi,
Found this: https://www.krakend.io/docs/endpoints/common-expression-language-cel/ 
Setting up the sequential steps is more or less what we need. However, the call pipe breaks if we run into a something like a "TCP connection refused", which could very well be the case if the service is completely down. Is there a way to handle something like this in CEL? It seems to me that krakend just immediately terminates upon seeing this.

**Comment by peturssonstefan-ikea** [comment]
From this thread, I can understand that this is not something that Krakend wants to support? 
https://github.com/devopsfaith/krakend-ce/issues/61

**Comment by alombarte** [comment]
Hi @peturssonstefan-ikea ,

I am glad to see IKEA is looking into this :)

We think that the good way of doing this is outside KrakenD (e.g: service discovery, service splitter, etc.) and this is why this described behavior is not present in any near plans.
CEL and sequential proxy can do a lot of magic together, but they assume your backends are working.
