### ISSUE TITLE
Cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by peturssonstefan-ikea** [devopsfaith/krakend-ce#445]
Hi! 

We are requesting an endpoint that returns json in the format:  

`[
    {
        "a": "val1",
        "b": "val2"
    },
    {
        "a": "val3",
        "b": "val4"
    }
]`

But we are getting the following error: 
[ENDPOINT: /test] json: cannot unmarshal array into Go value of type map[string]interface {}

Is krakend unable to handle JSON in this format? 

Here's the krakend.json: 

`{
    "version": 3,
    "extra_config": {
        "telemetry/logging": {
            "level": "DEBUG",
            "prefix": "[KRAKEND]",
            "syslog": true,
            "stdout": true,
            "format": "custom",
            "custom_format": "%{message}"
        }
    },
    "endpoints": [
        {
            "endpoint": "/test",
            "method": "GET",
            "backend": [
                {
                    "url_pattern": "/some-url",
                    "host": [
                        "https://test-host"
                    ]
                }
            ]
        }
    ]
}`

**Comment by kpacha** [comment]
you need to add the `is_collection` flag. check https://www.krakend.io/docs/backends/data-manipulation/#when-the-backend-response-is-inside-an-array
