### ISSUE TITLE
Can krakend be used directly with OIDC (Sign in With Google/Twitter)?

### ISSUE THREAD

**Issue by urashidmalik** [devopsfaith/krakend-ce#447]
Can Krakend used for Securing endpoints using Sign in with Google/ Sign in with Twitter?

Something like: https://docs.konghq.com/enterprise/0.31-x/oidc-google/

**Comment by kpacha** [comment]
sure, as long as your identity provider returns a valid JWT. check the documentation: https://www.krakend.io/docs/authorization/jwt-overview/
