### ISSUE TITLE
Logging Redaction

### ISSUE THREAD

**Issue by is911** [devopsfaith/krakend-ce#448]
Hi,

As per title, go-logging has a builtin Redact function. Without building a soft plugin, can someone give me pointers how to redact sensitive information from the logged message output? I'm using GELF format.

Thanks.

**Comment by alombarte** [comment]
Hi @is911 , the gologging plugin writes application warnings and other messages, but it never logs payloads, backend responses or other information that could be considered sensitive.

I am wondering what is the real use case you are trying to cover with this question.

**Comment by is911** [comment]
Hi @alombarte 

Im trying to partially (of fully) redact some information from the query parameters in the URL which contain sensitive information.

Credit card use case is a simple to demonstrate here. I wish to change https://url.com?card=1234123412341234 to https://url.com?card=12341xxxxxxxx234

Appreciate the way forward.

**Comment by kpacha** [comment]
it's not recommended to pass sensible information in the url, but if you must and you want to obfuscate it at the logs, you'll need to inject a customized gin log formatter (https://pkg.go.dev/github.com/luraproject/lura/v2@v2.0.1/router/gin#EngineOptions)
