### ISSUE TITLE
Rate limit not configured as expected in Kraken 2

### ISSUE THREAD

**Issue by alexanderwink** [devopsfaith/krakend-ce#451]
Kraken 2

**Rate limit has no effect**

The extra_config for endpoint rate limiting does not work when adding qos/ratelimit/router. Adding github.com/devopsfaith/krakend-ratelimit/juju/router works however but the documentation is pretty clear that for 2.0 I'm supposed to use qos/ratelimit/router while juju is for 1.4.

**Configuration file**
```
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "endpoints": [{
    "backend": [{
      "host": [
        "http://service-xxxxxx.svc"
      ],
      "url_pattern": "/api/v1/xxxxxx"
    }],
    "endpoint": "/xxxxxx/api/v1/yyyyyy",
    "input_query_strings": [
      "*"
    ],
    "method": "GET",
    "extra_config": {
      "qos/ratelimit/router": {
        "max_rate": 1,
        "client_max_rate": 1,
        "strategy": "ip"
      }
    }
  }]
}
```

**Expected behavior**
I expect to see 429 and 503 responses. I use bombardier with 125 concurrent requests during 10 seconds. I get 100% 200 repsonse codes.

**Additional context**

If i change my extra_config to
```
"github.com/devopsfaith/krakend-ratelimit/juju/router": {
  "maxRate": 1,
  "capacity": 1,
  "clientMaxRate": 1,
  "strategy": "ip"
}
``` 

Then rate limiting work as expected. However this is the kraken 1.4 config directive.

**Comment by kpacha** [comment]
There was an issue with the config parser. The fix is being released.

Thanks for the heads up!

**Comment by alombarte** [comment]
Version 2.0.1 released.
