### ISSUE TITLE
Logic before sending a request to a backend

### ISSUE THREAD

**Issue by dpalmasan** [devopsfaith/krakend-ce#454]
**Describe what are you trying to do**
I am doing JWT validation through KrakenD and everything works well. In my use case, I am maintaining "session" data in a cache (`redis`), so I can revoke some access token if a user logs out. What I would like to accomplish is the following flow:

1. User tries to send a request with a revoked (yet still valid access token)
2. KrakenD first validates the JWT token (I have already this in place)
3. KrakenD reads the request, checks the cache and if it not exists (meaning it was revoked) then return status 401. This is what I am struggling in implementing, as I need that this happens AFTER JWT verification

I started writing a plugin and I have all the headers needed. The problem is that I am not aware if I can modify the request/responses before sending anything to the backend or maybe a workaround for this?

Endpoint example:

```json
{
            "endpoint": "/refresh",
            "input_headers": [
                "Cookie",
                "Authorization"
            ],
            "method": "POST",
            "output_encoding": "no-op",
            "extra_config": {
                "github.com/devopsfaith/krakend-ratelimit/juju/router": {
                    "maxRate": 0,
                    "clientMaxRate": 30,
                    "strategy": "ip"
                },
                "plugin/req-resp-modifier": {
                    "name": [
                        "auth-access-check-request",
                        "auth-access-check-response"
                    ]
                }
            },
            "backend": [
                {
                    "url_pattern": "/session/refresh",
                    "encoding": "no-op",
                    "sd": "static",
                    "method": "POST",
                    "host": [
                        "http://auth-svc-auth-service.auth-svc.svc.cluster.local:4000"
                    ],
                    "disable_host_sanitize": false
                }
            ]
        },
```

For example if I add the auth validator:

```json
"auth/validator": {
                    "alg": "RS256",
                    "jwk_local_path": "/etc/krakend/jwks.json",
                    "cache": false,
                    "roles_key": "role",
                    "roles_key_is_nested": false,
                    "roles": [
                        "regular",
                        "admin"
                    ],
                    "disable_jwk_security": true,
                    "operation_debug": true
                }
```

I would like it to run **before** the plugin

**Comment by taik0** [comment]
To do that you already have the bloomfilter which is much more performant and doesn't depends on redis.

https://www.krakend.io/docs/authorization/revoking-tokens/

Anyway, a client plugin is executed just before calling the backend (you are the responsible in the plugin of calling the required backends and return the response) and after all the proxy pipe.

**Comment by dpalmasan** [comment]
Thanks for the suggestion, it seems it fits what I would like to do.
