### ISSUE TITLE
Which OpenId Connect (OIDC) flow(s) does KrakenD support?

### ISSUE THREAD

**Issue by tusharsdesai** [devopsfaith/krakend-ce#459]
Hello,

I'm trying to use KrakenD2.0 with KeyCloak. I was previously using Spring Cloud Gateway, which supports the authorization code flow of OIDC. But, it is not clear which flow is being supported by KrakenD? Is it authorization code flow, implicit flow or hybrid flow as described in,

[OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#Authentication)

All the 3 flows, require the client (i.e. KrakenD) to redirect an unauthorized user to the authorization server by preparing an authentication request. However, I'm seeing a 401 (Unauthorized) error. I saw another issue in krakend  in which someone (else) has replied that they see 401, but for some reason they believe it is the expected behavior.

```
08:10:26 $ curl -v localhost:8001/v1/movies/
*   Trying 127.0.0.1:8001...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8001 (#0)
> GET /v1/movies/ HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Sun, 03 Apr 2022 14:40:33 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
08:10:33 $ 
```

The diagram shown on your website [Keycloak integration](https://www.krakend.io/docs/authorization/keycloak/) also does not show any redirects. Since the token is being shared with the User-Agent, I'm led to believe that this is either an implicit or hybrid flow. But, a lack of redirects is confusing.

Can you please clarify?

Thanks.
Tushar.

**Comment by kpacha** [comment]
KrakenD does not play any role in the authentication process and it knows nothing regarding the idp associated with the received tokens. it's up to the client to know where to go for the token negotiation and refresh.

you can use any idp as long as it returns a proper JWT
