### ISSUE TITLE
Can proxy flatmap_filter be used to change the incoming request

### ISSUE THREAD

**Issue by krishna-kunderu** [devopsfaith/krakend-ce#461]
**Describe what are you trying to do**
Can I use proxy flatmap_filter be used to change the incoming request something like this  inside extra_config of an endpoint

```
"proxy": {
              "flatmap_filter": [
                  {
                      "type": "move",
                      "args": ["contact.0.contactMedium.0.characteristic.street1", "contactmoved.0.address1"]
                  },
                    {
                      "type": "move",
                      "args": ["contact.0.contactMedium.0.characteristic.city", "contactmoved.0.city"]
                  },
                    {
                      "type": "move",
                      "args": ["contact.0.contactMedium.0.characteristic.contactNumber", "contactmoved.0.phoneNumber"]
                  }
]
        }
```

My requirement actually is to modify incoming request properties to different property names. 

Also is it possible to take JSON Array Nth element to copy into a JSON Map? something like this contact[0] to "contactMoved": {.....}

**Comment by alombarte** [comment]
The flat map filter only works for the responses. If you want to modify the requests you can use:

- [Lua](https://www.krakend.io/docs/endpoints/lua/)
- [Request modifiers](https://www.krakend.io/docs/extending/plugin-modifiers/)
