### ISSUE TITLE
Can't get access to response data from a downstream service

### ISSUE THREAD

**Issue by razkevich** [devopsfaith/krakend-ce#466]
**Describe the bug**
Hello, I would like to get access to the response data returned by a downstream service. In particular, in the below `krakend.json`, I attempt to log the status code of the response. However, I'm getting 0 (zero). What am I doing wrong? I started off the krakend docker playground. Thanks.

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": "3",
  "timeout": "3000ms",
  "name": "internal-resources",
  "endpoints": [
    {
      "endpoint": "/splash",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/shop/campaigns.json",
          "host": [
            "http://fake_api:8080"
          ],
          "extra_config": {
            "modifier/lua-backend": {
              "post": "print(response.load():statusCode())",
              "allow_open_libs": true
            }
          }
        }
      ]
    }
  ]
}


```
**Commands used**
How did you start the software?
```
docker-compose up krakend_ce fake_api
```
**Expected behavior**
I expect to see 200 in the logs

**Comment by kpacha** [comment]
only the no-op pipes keep the status code from the response.

check https://www.krakend.io/docs/endpoints/status-codes/#returning-the-status-codes-of-the-backend for more details
