### ISSUE TITLE
When I use lura proxy modifier plugin gives an error

### ISSUE THREAD

**Issue by krishna-kunderu** [devopsfaith/krakend-ce#473]
**Describe what are you trying to do**
Using the github.com/luraproject/lura/v2/proxy for request/response modifier plugin following below KrakenD suggested document. 

Modifier plugin is not getting registered with the below errors. Looks like some of the below libraries mentioned in go.mod as below are not built with the GO version our project is using. Not sure how to overcome this. If I remove proxy.ResponseMetadataWrapper from the ResponseWrapper interface all working fine. I am not sure how to build the proxy package provided by lura to make it compatible with Go 1.17.8.

Tried with both v2 and 1.4.1 but giving same errors

V2 with below go.mod giving below errors

go 1.17

`require (
	 plugin was built with a different version of package github.com/luraproject/lura/v2/register
)
`

`2022/04/11 08:53:56 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin"): plugin was built with a different version of package github.com/luraproject/lura/v2/register`

V1.4.1 with below go.mod giving below errors

go 1.17

`require (
	github.com/devopsfaith/flatmap v0.0.0-20200601181759-8521186182fc // indirect
	github.com/luraproject/lura v1.4.1 // indirect
	github.com/valyala/fastrand v1.0.0 // indirect
)
`

https://www.krakend.io/docs/extending/plugin-modifiers/

**Your configuration file**

```
Go Lang version tried with 1.17.8
```

Used this below command to build .so plugin

`go build -buildmode=plugin -o modifierPlugin.so modifierPlugin.go`

**Logs**
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin"): plugin was built with a different version of package github.com/valyala/fastrand
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Handler Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin.so"): plugin was built with a different version of package github.com/valyala/fastrand (previous failure)
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #0 (/etc/krakend/plugins/httpHandlerPlugin.so): plugin: symbol ModifierRegisterer not found in plugin plugin/unnamed-be415b995a80d55a5fde08e3201bb850429c9287
2022/04/07 16:49:51 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin.so"): plugin was built with a different version of package github.com/valyala/fastrand (previous failure)

**Comment by krishna-kunderu** [comment]
Any update on this? I tried building the luraproject source as well as part of the plugin build, but still having the same error. Great if someone can chip in to suggest on this issue

**Comment by kpacha** [comment]
in order to check your deps, you can use this command: https://www.krakend.io/docs/extending/check-plugin/

**Comment by krishna-kunderu** [comment]
@kpacha 

I am seeing below for krakend check-plugin -g 1.17.8. I am using Ubuntu Latest image. Not sure how to proceed further. The link you have shared do not have information on installing the packages that have dependencies

`libc
        have:
        want: GLIBC-2.31
github.com/google/go-cmp
        have: v0.5.5
        want: v0.5.6
github.com/json-iterator/go
        have: v1.1.9
        want: v1.1.12
golang.org/x/net
        have: v0.0.0-20210226172049-e18ecbb05110
        want: v0.0.0-20220127200216-cd36cc0744dd
golang.org/x/sys
        have: v0.0.0-20211004093028-2c5d950f24ef
        want: v0.0.0-20211216021012-1d35b9e2eb4e`

**Comment by krishna-kunderu** [comment]
@kpacha, I updated all the dependencies I see ldd --version where plugin is built is having GLIBC-2.31 but I still see an error 
```
libc 
have: 
want: GLIBC-2.31 
```

I also trying link during the build like below
go build -ldflags="-X github.com/luraproject/lura/v2/core.KrakendVersion=2.0.0 \
	-X github.com/luraproject/lura/v2/core.GoVersion=1.17.8 \
	-X github.com/luraproject/lura/v2/core.GlibcVersion=GLIBC-2.31" -buildmode=plugin -o /etc/krakend/plugins/modifierPlugin.so modifierPlugin.go

**Comment by krishna-kunderu** [comment]
@kpacha Now I see no incompatabilities, but i still get below errors

![image](https://user-images.githubusercontent.com/99324244/162950278-3eda60ce-86ed-4837-8cf1-dc2571090dd8.png)


`2022/04/12 12:18:59 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #1 (/etc/krakend/plugins/modifierPlugin.so): plugin.Open("/etc/krakend/plugins/modifierPlugin"): plugin was built with a different version of package github.com/luraproject/lura/v2/register`
