### ISSUE TITLE
Mac M1 Custom plugin unsupported relocation type 1026

### ISSUE THREAD

**Issue by Sikarnas** [devopsfaith/krakend-ce#476]
**Describe what are you trying to do**

Hi, I’m having some trouble adding plugins to krakend, hope to get some answers here. I’m using mac m1 and krakend.json version 3 with image version 2.
I managed to build docker image with krakend http server plugin example, but when I run the image krakend starts but fails to load plugin with error:
`[KRAKEND] 2022/04/12 - 11:31:45.876 ▶ DEBUG [SERVICE: Executor Plugin] plugin #0 (plugins/test-plugin.so): plugin.Open("plugins/test-plugin.so"): Error relocating /etc/krakend/plugins/test-plugin.so: unsupported relocation type 1026`

I see that the krakernd.json route loads. and krakend works, but I don’t understand the issue with the plugin itself, google didn’t help much either, your help would be much appreciated :)

**Your configuration file**
Dockerfile:
```
FROM golang:1.17 as builder

COPY ./test-plugin/ /test-plugin
RUN cd /test-plugin && go build -buildmode=plugin -o test-plugin.so .


FROM devopsfaith/krakend:2

COPY --from=builder /test-plugin/test-plugin.so /etc/krakend/plugins/
COPY krakend.json /etc/krakend/krakend.json

EXPOSE 8080
CMD ["run", "-d", "-c", "/etc/krakend/krakend.json"]
```
krakend.json:
```
{
  "version": 3,
  "name": "test api",
  "timeout": "15000ms",
  "cache_ttl": "300s",
  "port": 8080,
  "$schema": "https://www.krakend.io/schema/v3.json",
  "plugin": {
    "folder": "./plugins/",
    "pattern": ".so"
  },
  "extra_config": {
    "telemetry/logging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    }
  },
  "endpoints": [
    {
      "endpoint": "/v1/test",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/api/v1/test",
          "method": "GET",
          "host": ["http://host.docker.internal:8081/"],
          "encoding": "no-op"
        }
      ],
      "output_encoding": "no-op",
      "input_headers": ["*"],
      "input_query_strings": ["*"]
    }
  ]
}
```

plugin code:

```
import (
    "context"
    "errors"
    "fmt"
    "html"
    "net/http"
)

// HandlerRegisterer is the symbol the plugin loader will try to load. It must implement the Registerer interface
var HandlerRegisterer = registerer("lura-example")

type registerer string

func (r registerer) RegisterHandlers(f func(
    name string,
    handler func(context.Context, map[string]interface{}, http.Handler) (http.Handler, error),
)) {
    f(string(r), r.registerHandlers)
}

func (r registerer) registerHandlers(ctx context.Context, extra map[string]interface{}, _ http.Handler) (http.Handler, error) {
    // check the passed configuration and initialize the plugin
    name, ok := extra["name"].(string)
    if !ok {
        return nil, errors.New("wrong config")
    }
    if name != string(r) {
        return nil, fmt.Errorf("unknown register %s", name)
    }
    // return the actual handler wrapping or your custom logic so it can be used as a replacement for the default http handler
    return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
        fmt.Fprintf(w, "Hello, %q", html.EscapeString(req.URL.Path))
    }), nil
}

func init() {
    fmt.Println("lura-example handler plugin loaded!!!")
}

func main() {}
```

**Logs**
Console output:
`Parsing configuration file: /etc/krakend/krakend.json
[KRAKEND] 2022/04/12 - 11:31:45.871 ▶ DEBUG [SERVICE: Plugin Loader] Starting loading process
[KRAKEND] 2022/04/12 - 11:31:45.876 ▶ DEBUG [SERVICE: Executor Plugin] plugin #0 (plugins/test-plugin.so): plugin.Open("plugins/test-plugin.so"): Error relocating /etc/krakend/plugins/test-plugin.so: unsupported relocation type 1026
[KRAKEND] 2022/04/12 - 11:31:45.877 ▶ DEBUG [SERVICE: Handler Plugin] plugin #0 (plugins/test-plugin.so): plugin.Open("plugins/test-plugin.so"): Error relocating /etc/krakend/plugins/test-plugin.so: unsupported relocation type 1026
[KRAKEND] 2022/04/12 - 11:31:45.877 ▶ DEBUG [SERVICE: Modifier Plugin] plugin #0 (plugins/test-plugin.so): plugin.Open("plugins/test-plugin.so"): Error relocating /etc/krakend/plugins/test-plugin.so: unsupported relocation type 1026
[KRAKEND] 2022/04/12 - 11:31:45.877 ▶ DEBUG [SERVICE: Plugin Loader] Loading process completed
[KRAKEND] 2022/04/12 - 11:31:45.879 ▶ DEBUG [SERVICE: Gin] Debug enabled
[KRAKEND] 2022/04/12 - 11:31:45.882 ▶ INFO Starting the KrakenD instance
[KRAKEND] 2022/04/12 - 11:31:45.883 ▶ DEBUG [ENDPOINT: /v1/test] Building the proxy pipe
[KRAKEND] 2022/04/12 - 11:31:45.884 ▶ DEBUG [BACKEND: /api/v1/test] Building the backend pipe
[KRAKEND] 2022/04/12 - 11:31:45.885 ▶ DEBUG [ENDPOINT: /v1/test] Building the http handler
[KRAKEND] 2022/04/12 - 11:31:45.886 ▶ DEBUG [ENDPOINT: /v1/test][JWTSigner] Signer disabled
[KRAKEND] 2022/04/12 - 11:31:45.886 ▶ INFO [ENDPOINT: /v1/test][JWTValidator] Validator disabled for this endpoint
[KRAKEND] 2022/04/12 - 11:31:45.887 ▶ INFO [SERVICE: Gin] Listening on port: 8080
[KRAKEND] 2022/04/12 - 11:31:50.875 ▶ DEBUG [SERVICE: Telemetry] Registering usage stats for Cluster ID KREtKJNNM42ACczzLJGyxyp6wgSS+UOhXGCKEfTFPoc=`

**Comment by kpacha** [comment]
you should compile the plugin with the same image used to compile the binary.

https://github.com/devopsfaith/krakend-ce/blob/master/Makefile#L22-L24
https://github.com/devopsfaith/krakend-ce/blob/master/Dockerfile#L1-L3

**Comment by Sikarnas** [comment]
I updated docker file, but the same error is still present :(

`FROM golang:1.17.8-alpine3.15 as builder

RUN apk add make gcc musl-dev binutils-gold

COPY ./test-plugin/ /test-plugin
RUN cd /test-plugin && go build -buildmode=plugin -o test-plugin.so .


FROM devopsfaith/krakend:2

COPY --from=builder /test-plugin/test-plugin.so /etc/krakend/plugins/
COPY krakend.json /etc/krakend/krakend.json

EXPOSE 8080
CMD [“run”, “-c”, “/etc/krakend/krakend.json”]`

**Comment by Sikarnas** [comment]
fixed by adding
`FROM --platform=linux/amd64  golang:1.17.8-alpine3.15 as builder` as base builder image was set to arm by default.
