### ISSUE TITLE
How to return a json collection from an embedded collection

### ISSUE THREAD

**Issue by MKITConsulting** [devopsfaith/krakend-ce#489]
**Describe what are you trying to do**

Is there a method to transform a JSON Object with an embedded collection to a JSON Array?

This is the backend response to be transformed:

```
{
   "mycollection": [
      {"myitem": 1},
      {"myitem": 2},
      ...
   ]
}
```

The desired endpoint response should be:

```
[
   {"myitem": 1},
   {"myitem": 2},
   ...
]
```

When I use `"target": "mycollection"` on the backend then the result will be an empty `[]`. If I then add `"output_encoding":"json-collection"` it will also stay empty. If I furthermore add `"is_collection": true` to the backend the request will fail with an error:

`json: cannot unmarshal object into Go value of type []interface {}`

This seems logic if the `"is_collection"` property runs before the `"target"` transformation. Is there a method to transform the data like described above? (maybe with another interception that just removes the part `{ "mycollection": ` and the last `}`)

**Comment by kpacha** [comment]
the `json-collection` renderer returns the array contained at the `collection` key, so if you rename the key `mycollection` to `collection` it will do what you want

Here you have an example:
```
{
  "endpoint": "/foo",
  "output_encoding": "json-collection",
  "backend": [
    {
      "url_pattern": "/bar",
      "host": ["http://foobar.tld"],
      "mapping": {
        "mycollection": "collection"
      }
    }
  ]
}
```
