### ISSUE TITLE
Flexible configuration

### ISSUE THREAD

**Issue by jcirionotero** [devopsfaith/krakend-ce#498]
**Describe what are you trying to do**
Create a flexible configuration following documentation steps.

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
  "version": 3,
  "port": {{ .service.port }},
  "name": "{{ .service.name }}",
  "timeout": "{{ .service.timeout }}",
  "cache_ttl":  "{{ .service.cache_ttl }}",
  "output_encoding": "{{ .service.output_encoding }}",
  "extra_config": {{ marshal .service.extra_config }},
  "endpoints": [
      {{ range $idx, $endpoint := .endpoint.profile }}
      {{if $idx}},{{end}}
      {
      "endpoint": "{{ $endpoint.endpoint }}",
      "method": "{{ $endpoint.method }}",
      "backend": [
          {
              "url_pattern": "{{ $endpoint.backend_url_pattern }}",
              "method": "{{ $endpoint.backend_method }}",
              "host": [
                "{{ $endpoint.backend_host }}"
              ],
              "extra_config": {
                  {{ include "rate_limit_backend.tmpl" }}
              }
          }
      ]}
      {{ end }}
  ]
}
```
**Commands used**
How did you start the software?
```
#Example:
FC_ENABLE=1 \ 
FC_SETTINGS="config/settings" \
FC_PARTIALS="config/partials" \
krakend check -t -d -c "config/krakend.json"
```

**Logs**
Parsing configuration file: config/krakend.json
ERROR parsing the configuration file:	'config/krakend.json': invalid character '{' looking for beginning of object key string, offset: 30, row: 2, col: 12

**Comment by kpacha** [comment]
did you inspect the generated configuration? adding `FC_OUT=out.json` to your command will allow you to persist it and then linting it, looking for possible errors.

**Comment by jcirionotero** [comment]
For some reason that file is not generated!!!

**Comment by alombarte** [comment]
Hi @jcirionotero ,

Please escape all new lines:

```
FC_ENABLE=1 \
FC_SETTINGS="config/settings" \
FC_PARTIALS="config/partials" \
FC_OUT=out.json \
krakend check -t -d -c "config/krakend.json"
```
