### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by ricmoreira** [devopsfaith/krakend-ce#59]
Hello,

I'm getting an error, after running:
`make all`

The error:

> Building the binary...
> cmd/krakend-ce/main.go:12:2: import "krakend-ce/vendor/github.com/devopsfaith/krakend-ce" is a program, not an importable package
> make: *** [build] Error 1

I've just cloned the repository and hit the make command.
Any idea why this is happening?

**Comment by alombarte** [comment]
Olá @ricmoreira ,

Have you built the product as per the [instructions](https://github.com/devopsfaith/krakend-ce#build)?

    make prepare
    make

If you launch `make all` it is assumed that `dep` is already installed. Let me know if this is the case.

**Comment by ricmoreira** [comment]
Olá @alombarte ,

Yes, I already have dep installed

**Comment by alombarte** [comment]
We will need more info Ricardo. Here is a screencast with a clean folder.

[![asciicast](https://asciinema.org/a/zsa9Ny8nGrq0m0E3QhIimdKuV.png)](https://asciinema.org/a/14)

Can you do something similar?
https://asciinema.org/a/zsa9Ny8nGrq0m0E3QhIimdKuV

**Comment by kpacha** [comment]
hi @ricmoreira 

please, remove the vendor folder and try again

Cheers

**Comment by ricmoreira** [comment]
Hello @kpacha ,
It didn't work for me but I'll close this issue as it seems that is something related to my environment.
Thanks.

**Comment by kpacha** [comment]
@ricmoreira , join our [slack](https://gophers.slack.com/messages/krakend) channel.

maybe someone there could help you
