### ISSUE TITLE
add feature to connect to backend via ssh

### ISSUE THREAD

**Issue by softwarelimits** [devopsfaith/krakend-ce#60]
Hi, first I would like to say that krakend looks really awesome - this is the kind of software I love! Slick, quick, minimal stack, but great features, smart configuration,  simply brilliant! I was researching a few of the api gateway monstrosities that exist and I believe krakend can easily lead the pack! Thank you very much for your efforts and for making this a real open source project!

Please allow me to add some issues / ideas to make it even more awesome!

This first one is already very clear from the issue title, so I took the opportunity to show my appreciation here :)

**Comment by alombarte** [comment]
Thank you very much for your appreciation and I am happy that you are liking the product so far.

I am not quite sure about the use case of this request. Are you trying to use the API gateway as a bastion host? Are you trying to get data from an SFTP? 
 I am just trying to understand your point here and how would be this connected to an API Gateway.

Thanks

**Comment by softwarelimits** [comment]
The use case is to access API endpoints that are available only on 127.0.0.1 on a remote server. These endpoints have no authentication (for $reasons) and the access is managed via ssh keys, what turns out to be a very simple and quick solution for building API endpoint authentication for legacy systems (or systems that are still in a prototype status and still have no auth feature) _without adding another layer of user management_ . 

So the access happens via `ssh api@backend 'curl http://127.0.0.1/api/end/point'`

Of course it would be possible to create ssh tunnels upfront for every endpoint, but for development, quick iteration and convenience it would be really nice if krakend just could make the ssh connection herself . 

Ah, and of course it should then read and understand `~/.ssh/config` - it would not make sense without that.
