### ISSUE TITLE
add feature to do something with the payload content

### ISSUE THREAD

**Issue by softwarelimits** [devopsfaith/krakend-ce#62]
add feature to **do something** with the payload content, e.g. simple calculations or regex replacements.

You have an example in the docs:
```json
{
  "apiVersion":"2.0",
  "data": {
    "updated":"2010-01-07T19:58:42.949Z",
    "totalItems":800,
    "startIndex":1,
    "itemsPerPage":1,
    "items":[]
  }
}
```
I think it would be extremely useful to not only capture the `data`, but also **calculate the sum** for all `totalItems`. 

I believe this feature will be of giant usefulness even with a very simple set of possible operations, like simple math and regex string replacement. *Huge* possibilities to save many loc in any aggregation backend. 

For me it is a pain to decide at which point in the infrastructure this kind of aggregation should happen - building another service just for aggregation will lead to convoluted api request chains with lots of problems when things go wrong. Having simple aggregation tasks happen in the api gateway would be a fantastic solution.

**Comment by kpacha** [comment]
@softwarelimits I think https://github.com/devopsfaith/krakend-ce/issues/113 will cover this
