### ISSUE TITLE
add a plugin system that allows me to do anything i want with api payload

### ISSUE THREAD

**Issue by softwarelimits** [devopsfaith/krakend-ce#64]
Add a plugin system that allows me to do anything i want with api payload, not only combine and capture.

Again, combine this issue with my previous ones. Users might define their own events like "field x contains y" to trigger any kind of action. 

Actions might be anything, defined in a plugin. 
Some pre-defined standard actions should come with the system, like "send email", "write to file", "do another request with combined fields from request A and B" to update some data in a service, etc.

Of course I see that this will potentially kill performance - as an optional feature it still will be extremely useful.

**Comment by kpacha** [comment]
@softwarelimits , please take a look at the new features we are exploring for the project:

- customizable proxy middlewares with the lua interpreter (https://github.com/devopsfaith/krakend-ce/issues/113)
- customizable http request executors via plugins (https://github.com/devopsfaith/krakend/pull/255)
- customizable http handlers via plugins (https://github.com/devopsfaith/krakend/pull/256)

cheers!
