### ISSUE TITLE
Kubernetes - Create a helm chart to install krakend

### ISSUE THREAD

**Issue by alombarte** [devopsfaith/krakend-ce#67]
Create a chart to install krakend using helm in kubernetes.

Image: devopsfaith/krakend
ConfigMap to load the `krakend.json`

**Comment by mikescandy** [comment]
have a look at https://github.com/mikescandy/krakend-helm
be aware that:

i started using helm on tuesday
i still have to find a better way to pass the configuration
works on my machine (tm)

**Comment by alombarte** [comment]
Thank you very much @mikescandy!!
I'll have a look soo, this is an interesting addition as everyone is doing their own helm charts.

**Comment by alombarte** [comment]
Thank you very much @mikescandy .

I've added your Helm Chart to our [krakend-contrib](https://github.com/devopsfaith/krakend-contrib) repository.
