### ISSUE TITLE
Can't use etcdV3 for service-discovery ?

### ISSUE THREAD

**Issue by Michael2008S** [devopsfaith/krakend-ce#72]
My etcd version is :
```
etcd Version: 3.3.11
```
My config is : 

```
        "github_com/devopsfaith/krakend-etcd": {
            "machines": [
                "http://127.0.0.1:2379"
            ],
            "dial_timeout": "5s",
            "dial_keepalive": "30s",
            "header_timeout": "1s"
        },
```

```
      "backend": [{
        "url_pattern": "/gcrpc/gcrpc.user.User/List",
        "encoding": "no-op",
        "sd": "etcd",
        "host": [
          "/micro-rpc-api"
        ]
      }],
```

But it can't get the value,the Jaeger tell me :

```
"dial tcp: lookup micro-rpc-api: no such host"
```

**Comment by kpacha** [comment]
hi, @Michael2008S , welcome to the KrakenD community!

so far, KrakenD is not using the v3 client.

on the other hand, your configuration is incorrect: you mixed the SD layer with the backend consumption. Here you have the documentation and an example:

- https://www.krakend.io/docs/service-discovery/etcd/
- https://github.com/devopsfaith/krakend-etcd/blob/master/example/krakend.json

cheers!

**Comment by Michael2008S** [comment]
@kpacha  So the the krakenD is useing the V2 Client?

And my config is correct.I just show section it int the  issue.

**Comment by kpacha** [comment]
Yes, it is using v2 (https://coreos.com/etcd/docs/latest/v2/api.html)

This config is telling the gateway to make a call to the `etcd` keys api requesting the nodes registered under the key `/micro-rpc-api` and then it keeps a watcher monitoring that key. So I'd suggest to remove the initial `/`.

I'd also include the `"disable_host_sanitize": true` at the backend level, so the config parser won't try to fix the malformed host.

You can check what the response looks like with a simple `curl http://127.0.0.1:2379/v2/keys/micro-rpc-api`

**Comment by kpacha** [comment]
btw, issue added to the krakend-etcd project: https://github.com/devopsfaith/krakend-etcd/issues/1
