### ISSUE TITLE
Support for API request quantity?

### ISSUE THREAD

**Issue by silakanveli** [devopsfaith/krakend-ce#83]
E.g situation where it.is.nesessary to restrict API usage like 100.000 request only.

**Comment by kpacha** [comment]
hi @silakanveli , please take a look at the documentation

https://www.krakend.io/docs/endpoints/rate-limit/
https://www.krakend.io/docs/backends/rate-limit/

also, here you have the component responsible https://github.com/devopsfaith/krakend-ratelimit

cheers!
