### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by silakanveli** [devopsfaith/krakend-ce#84]
Is there support for websocket proxying?

**Comment by kpacha** [comment]
right now, the websocket module is not opensourced. we licensed it as part of the enterprise features.

**Comment by exu** [comment]
Hi, Any changes on this ? Still only in enterprise ?

**Comment by alombarte** [comment]
Yes, WebSocket capabilities are only for Enterprise users.

**Comment by Dhua-v** [comment]
What about this https://www.krakend.io/blog/open-sourcing-enterprise-features/

Not having websocket support means, you took us all to the ocean in Titanic for free and hit it with websocketberg.

The WS are more needed then rest things you good engineers are open sourcing.

**Comment by kpacha** [comment]
1. WS is not a feature from the API Gateway land. Also, our implementation requires some backend customization (and it usually requires dedicated support from us)
2. As the linked post says, we open sourced the entire framework and all the common components required to build an API Gateway without limitations (no max requests, concurrency, number of endpoints, etc). These were the enterprise features back when we took that decision.
3. We are developing and maintaining the project and giving support for free. You can extend and customize it all you want, for free. Do you want us to move to other (payed) projects and let KrakenD die? I'm sure you'll understand that engineers (good or bad) are people and we need to eat and pay bills too

**Comment by Dhua-v** [comment]
Hy, 3rd one is really hurting . I want to help. See I am in a sales team and know how to monetize things.
1. Giving additional support must not be free for the sake of humanity.
2. Custom on demand plugins must be monitized.
3. patreon. People really care about the people who helped them build themselves.
And a big one, 
one way grpc stream is much effecient than websockets, and people are shifting to that very fast.

I know you are all well aware of even more things, but wanted to share my opinion.

Thanks.
