### ISSUE TITLE
how to write my cookie to the browser?

### ISSUE THREAD

**Issue by Michael2008S** [devopsfaith/krakend-ce#89]
I try to set my cookie in my backend side with echo framework code :
```
func (s *Auth) SetLoginCookie(c echo.Context, path, actoken, rftoken string) {
	// 写入 cookie
	cookie := new(http.Cookie)
	cookie.Name = access_token
	cookie.Value = actoken
	cookie.Secure = true
	cookie.HttpOnly = true
	cookie.Path = path
	cookie.Domain = s.cfgCookies.Domain
	cookie.Expires = time.Now().Add(24 * time.Hour)
	fmt.Println("cookie:", cookie)
	c.SetCookie(cookie)
}
```
with the krakend config ：

```
    {
      "endpoint": "/gcapi/iam.IAM/login",
      "method": "POST",
      "output_encoding": "JSON",
      "backend": [{
        "url_pattern": "/gcapi/iam.IAM/login",
        "encoding": "JSON",
        "disable_host_sanitize":true, 
        "sd": "etcd",
        "host": [
          "micro-rpc-iam"
        ]
      }]
    },
```

But I can't set the cookie in the chrome browser.

When I use the nginx to proxy the backend ,I can write it to my chrome browser.

How to set krakend Config to write the cookie ??

**Comment by kpacha** [comment]
hi, @Michael2008S 

the regular pipes drop every header included into the backend response(s)

If you are not using any other feature (merging, duplicated concurrent requests, encoding, etc), you can use the `no-op` proxy, so the requests and responses will be proxied as received.

**Comment by Michael2008S** [comment]
@kpacha  It work ,thanks.
